/* Beginner-facing copy; dates, relationships and sources stay in the source cards. */
var BEGINNER_MIDDLE = { revisions: {} };
(function () {
  function revise(id, name, description, title1, text1, title2, text2, note) {
    var revision = { description: description, sections: [{ title: title1, text: text1 }, { title: title2, text: text2 }] };
    if (name) revision.name = name;
    if (note !== undefined) revision.note = note;
    BEGINNER_MIDDLE.revisions[id] = revision;
  }
  revise('sui', null,
    'The Sui dynasty began in 581 and conquered the southern Chen dynasty in 589, bringing north and south under one court. Its rulers built the transport and government systems needed to hold this large territory together. Their demands also helped turn people against them.',
    'Connecting north and south', 'Winning territory was only the first step. Officials needed records of households, ways to collect grain and reliable routes for moving supplies and armies. The canal network connected regions that had spent generations under different rulers. Sui government also drew on practices inherited from those earlier states; reunification did not mean that every district immediately worked in the same way.',
    'The cost of imperial ambition', 'Canal construction and repeated campaigns against Goguryeo in 612–614 demanded labour and supplies from communities. The same power that made enormous projects possible could place unbearable pressure on the people supporting them. Sui lasted only until 618, but later dynasties inherited important parts of its government and transport network. Their usefulness outlived the court that built them.');
  revise('tang', null,
    'The Tang dynasty ruled for nearly three centuries, linking a powerful court with armies, trading routes, religious communities and distant neighbours. Its capital, Chang’an, attracted people and ideas from beyond the empire. Behind its famous poetry and art lay a government that changed greatly over time.',
    'A connected capital', 'Merchants, travellers and religious teachers carried objects and knowledge across political borders. Xuanzang brought Buddhist manuscripts home and worked with others to translate them. The court supported some of these exchanges, but many depended on people and routes beyond its control. Even military conflict did not necessarily stop trade or diplomatic visits.',
    'Rebuilding after rebellion', 'The An Lushan Rebellion transformed the balance of power between the emperor and provincial commanders. To survive, the court accepted new military arrangements and changed how it raised money. These compromises limited its authority but also helped it keep governing. Tang cultural life continued through the next century and a half; the rebellion was a turning point, rather than an immediate end.');
  revise('wu-zhou', 'Wu Zetian’s Zhou dynasty',
    'In 690, Wu Zetian took the imperial title and founded her own Zhou dynasty, interrupting Tang rule. A woman occupying the emperor’s position broke established expectations. Keeping that position required a working government, loyal supporters and ways to persuade others that her rule was legitimate.',
    'Choosing officials', 'Wu expanded recruitment through examinations, opening opportunities beyond established court connections. Successful candidates could owe their advancement to her support. This did not mean that ability alone determined promotion: she also favoured relatives and sought the prestige of aristocratic family connections. New routes into office worked alongside older forms of privilege.',
    'Poetry and court connections', 'Her support for writers made the court an important place to seek recognition. Access was uneven, and writers formed new poetic communities as they pursued opportunities or faced exclusion. Poetry belonged to this world of friendships, patronage and political ambition. Wu’s government depended on the relationships around her as well as on her own unusual position.');
  revise('five-dynasties', null,
    'Between Tang’s fall in 907 and Song’s foundation in 960, five dynasties succeeded one another in the north. Some regional states lasted much longer. Military commanders could make and unmake emperors, but government did not start again from nothing with each new ruling family.',
    'Armies and personal loyalty', 'Commanders depended on relationships with their troops and on access to money and supplies. These ties could help a ruler take power, then allow another commander to overthrow him. Offices, armies and regional centres often survived a change of dynasty, even when the people at the top changed quickly.',
    'The foundations of Song', 'Later Zhou strengthened its military and government and expanded its territory before Song was founded. Song inherited that work and continued the struggle to bring regional states under one court. The year 960 therefore marks a new dynasty, not an instant end to division. Reunification depended on campaigns and negotiations that continued after the Five Dynasties period.');
  revise('song', null,
    'Founded in 960, Song brought much of the former Tang heartland under one court while sharing East Asia with powerful neighbouring empires. Growing markets, printed books and examinations helped shape its society. Trade and learning flourished alongside the continuing demands of war.',
    'Markets and education', 'Specialized producers supplied towns and cities through expanding markets. Printing made study texts more available, while examinations offered educated families a route into government. These developments created opportunities, but preparation still required time, teachers and money. Commercial growth also left families exposed to debt, failed harvests and taxes.',
    'Survival in the south', 'Jin forces took the northern capital in 1127, but the Song ruling house rebuilt its government in the south. Southern farming, cities and transport routes supplied the money and grain needed to maintain armies. The dynasty continued until 1279, resisting first Jin and then the Mongols. Wealth gave it resources to fight; turning those resources into lasting security remained a difficult political and military task.');
  revise('yuan', null,
    'Kublai Khan proclaimed the Yuan dynasty in 1271 and completed the conquest of Southern Song in 1279. His government connected China to Mongol networks across Eurasia. People of many backgrounds worked for the court, though their rights, duties and opportunities differed.',
    'Movement and unequal opportunity', 'Officials, artisans and religious specialists travelled to serve rulers and patrons. Some found employment and protection; others moved because of conquest, displacement or forced service. The court’s cultural variety grew through both opportunity and coercion. Connections across great distances did not mean that everyone in the empire enjoyed equal standing.',
    'China and the Mongol world', 'Yuan rulers used Chinese forms of government while keeping close political ties to Mongolia and the steppe. Their claims to wider Mongol authority did not make every other Mongol khanate obey them. When Ming forces took Dadu in 1368, Yuan rule over the Chinese heartland ended. Its rulers and their successors continued to govern farther north.',
    '1271 marks the Yuan proclamation; 1279 marks the final conquest of Southern Song. Northern Yuan rule continued after 1368.');
  revise('liao', null,
    'The Khitan-led Liao empire governed pastoral communities and farming regions north of Song. Its rulers claimed to be emperors in their own right. Liao helped shape the borders, diplomacy and trade of the region for more than two centuries.',
    'Different ways of governing', 'The court used different arrangements for different populations and tasks. Mobile court practices existed alongside Chinese-style administration in farming regions. This allowed rulers to draw on several kinds of resources and expertise. It also meant managing competing powerful families and deciding who owed military service and who held office.',
    'Peace with Song', 'The agreement of 1005 established mutual recognition and annual transfers from Song. Payments could be controversial, but they offered an alternative to the costs and destruction of repeated war. Jurchen forces conquered Liao’s heartland in 1125. Khitan survivors carried their power west, where Western Liao continued. The fall of the original court did not end Khitan political history.',
    '916 marks the imperial proclamation. Some chronologies begin in 907, when Abaoji became leader. Western Liao continued after 1125.');
  revise('western-xia', null,
    'Li Yuanhao proclaimed Western Xia in 1038, building on an older Tangut power base in the northwest. Its territory connected farming districts, the steppe and the Hexi corridor. These routes made it a trading partner and military rival of neighbouring states.',
    'Books in Tangut', 'The Tangut script gave the government a written language for administration and supported a rich Buddhist culture. Translators, scribes and printers produced works that connected the court to wider religious traditions. Surviving books reveal an important centre of learning, although Buddhist and archaeological evidence tells us more about some parts of society than others.',
    'Living between powerful neighbours', 'Western Xia fought and negotiated with Song, Liao and Jin. Payments and recognition could secure breathing room without ending the Tangut court’s ability to govern its own territory. These changing relationships helped sustain the state for nearly two centuries. Mongol conquest ended it in 1227, after a long history of Tangut participation in the region’s balance of power.');
  revise('jurchen-jin', null,
    'Aguda founded the Jurchen Jin dynasty in 1115. Its armies defeated Liao and captured the Song capital in 1127. Jin then governed much of northern China while Southern Song continued beyond a contested frontier.',
    'From conquest to government', 'Jin rulers kept Jurchen military and social institutions while using Chinese administrative practices to govern farming communities. Questions of land, service and official appointments shaped how these arrangements worked together. Adopting a form of government did not automatically erase differences between conquerors and conquered, or the privileges associated with them.',
    'Life in the north', 'People under Jin rule cultivated land, maintained towns and adapted to war and changes of government. Their history continued alongside the better-known cultural life of Southern Song. Mongol attacks brought another major upheaval, ending the dynasty in 1234. Song helped fight its northern rival, but Jin’s destruction left Song facing the expanding Mongol power.');
  revise('early-yuan', 'Yuan foundation',
    'Kublai Khan proclaimed the Yuan dynasty in 1271, eight years before the final defeat of Southern Song. He already ruled northern China and claimed authority as Great Khan. Southern Song still controlled territory that his new dynasty claimed.',
    'What the new name meant', 'A Chinese dynastic title presented Kublai’s rule as part of an established tradition of imperial succession. It addressed officials and subjects who understood authority through that tradition. The proclamation announced the government he intended to build; it did not mean that his armies had already taken every claimed region.',
    'Eight more years of resistance', 'Southern Song defended rivers and fortified positions. Overcoming those defences required supplies, sustained campaigning and expertise from several populations under Mongol command. Yuan and Song therefore existed at the same time. The change of dynasties was a prolonged military struggle, with the outcome still being fought over after the Yuan name had been announced.',
    '1271–1279 covers the overlap between the Yuan proclamation and the final Southern Song conquest. It is part of Yuan history, not a separate dynasty.');
  revise('reunification', 'Sui reunification',
    'Sui forces conquered the southern Chen dynasty in 589. The victory brought the lower Yangtze and other southern regions under the northern court, ending a major political division.',
    'Governing the conquered regions', 'Defeating a rival emperor did not make local officials and communities disappear. Sui needed appointments, cooperation and dependable ways to gather and move supplies. These were slower tasks than capturing a capital. Political reunification began a larger effort to make northern and southern government work together.',
    'What the south brought', 'Southern courts had spent centuries developing their own institutions and cultural life. Sui inherited regions with established resources, skills and powerful local relationships. The reunited empire depended on these foundations while redirecting them toward a new imperial centre. Southern history did not begin with the northern conquest.');
  revise('an-lushan', null,
    'An Lushan’s revolt began in December 755 and grew into a prolonged civil war. Tang forces defeated the main rebellion by 763, but the government that survived had a different balance of power between the emperor and provincial commanders.',
    'Saving the dynasty strengthened commanders', 'The court created more military commands to organize resistance. Many provincial armies fought for Tang, so stronger regional military power grew partly from the effort to save it. Commanders needed soldiers, supplies and dependable income. Once they controlled these resources, the emperor could not simply take every wartime power back.',
    'Government after the war', 'The restored court increasingly raised money through taxes on commerce and consumption. These changes helped support continued government, even as powerful provinces limited what the emperor could demand. Tang lasted for another century and a half, with important cultural achievements as well as conflict. Survival required compromises that both sustained the dynasty and constrained it.',
    '755–763 CE. Losses in tax registers include people the government could no longer count; they cannot be treated directly as a death toll.');
  revise('sutra', 'Diamond Sutra',
    'The Diamond Sutra scroll dated 868 is an exceptionally early surviving printed book. Its dedication names Wang Jie as the sponsor. He had the Buddhist scripture made for his parents’ benefit and for wider distribution.',
    'Printing for religious merit', 'Making copies of a scripture could spread Buddhist teaching and bring religious merit to the donor and others. Wang Jie’s dedication connects the printed object to his family and to readers beyond it. The reason to reproduce a text mattered as much as the method: religious giving helped create demand for copies.',
    'A date we can trust', 'The dedication gives this surviving scroll a clear place in time. Printing already existed before 868, so the date does not mark its invention. What survives is a particular act of sponsorship, bringing together a sacred text, skilled production and a named donor. It offers a close view of how printing served religious life.');
  revise('chanyuan', null,
    'In 1005, Song and Liao agreed to end a period of frontier warfare. Song promised annual payments of silver and silk, and the two courts recognized one another’s imperial standing. The settlement made coexistence possible without either side conquering the other.',
    'The cost of peace', 'Annual payments were easy to criticize, but war also required money for armies and garrisons and disrupted livelihoods along the border. The treaty offered a way to secure the frontier through negotiation. Accepting another emperor meant placing practical limits on each court’s claims to supreme authority.',
    'A durable but changeable agreement', 'Repeated embassies and more predictable relations followed. Rivalry and border disputes did not vanish, and the agreement depended on a changing regional balance of power. Song later allied with Jin against Liao, helping overturn the order that the treaty had supported. A century of relative peace was a significant achievement, but it did not make the settlement permanent.');
  revise('jingkang', 'Fall of Kaifeng',
    'Jin forces captured Kaifeng in 1127. They took Emperor Qinzong, the retired Emperor Huizong and members of the Song court north as prisoners. Northern Song ended, but a surviving prince established a new Song court that same year.',
    'An alliance backfires', 'Song had joined the rising Jin against Liao, hoping to recover territory. Once Liao was defeated, Song faced a more dangerous neighbour. Removing an old rival had also removed a state that stood between Song and another expanding power. The earlier alliance left Song in a much more difficult position.',
    'Rebuilding in the south', 'Officials and refugees carried skills, possessions and memories south. A new court drew on the region’s existing economic strength to rebuild government. The captive emperors complicated the new ruler’s claim to authority, and recovering the north remained a charged political issue. Southern Song preserved the dynasty while changing its territory, resources and relationship with its northern enemy.',
    '1127 marks Kaifeng’s fall and the emperors’ captivity after campaigns in 1125–1127. Song continued in the south until 1279.');
  revise('catalog-S_ST', 'Sui and Tang',
    'Sui and Tang together span the rebuilding of a united empire and nearly three centuries of change. Tang inherited northern military and government traditions from Sui, along with a territory that had recently been reunited.',
    'An inherited foundation', 'The change of dynasty in 618 brought new rulers and priorities, while useful offices and practices continued. Governing a large empire still meant appointing officials, collecting resources and moving grain and armies. These shared foundations help explain why the two dynasties are often studied together.',
    'A changing empire', 'The An Lushan Rebellion transformed Tang government. New military commands and ways of collecting taxes changed the relationship between the court and the provinces. Later Tang rulers worked within arrangements very different from those of early Sui. Across this long period, institutions survived by changing, rather than operating in one fixed form.',
    '581–907 groups two successive dynasties, Sui and Tang.');
  revise('catalog-G_ISLAM', 'Muhammad’s first revelation',
    'Islamic tradition dates Muhammad’s first revelations to 610. The migration to Medina, known as the Hijra, followed in 622. The early Muslim community grew through several stages before the later expansion of Muslim-ruled states.',
    'A growing community', 'Religious belief developed alongside new political relationships and institutions. Later expansion brought Muslim communities into contact with other regions and traditions. Forms of government and material culture changed through those encounters; the whole process cannot be assigned to a single founding year.',
    'Later connections with China', 'Trade and diplomacy eventually connected Muslim societies with Chinese ports and courts. These connections developed after the first revelations. The seventh century saw important changes across Eurasia, but 610 is not a date for the arrival of Islam in China.',
    '610 is the traditional date of the first revelation, not the arrival of Islam in China.');
  revise('catalog-C_BEIJING_YUAN', 'Dadu, the Yuan capital',
    'In 1272, Kublai Khan’s northern capital received the name Dadu. He had proclaimed the Yuan dynasty the year before. Planning and construction of the city had already begun.',
    'Between China and Mongolia', 'The capital connected the emperor’s Chinese farming territories with his Mongol power base. Its court and monumental layout expressed ambitions that reached across both worlds. Governing from a permanent city did not mean abandoning the northern relationships on which Mongol power depended.',
    'Supplying an imperial city', 'Officials, guards, artisans and visiting envoys needed food and materials. Transport from productive regions mattered as much as walls and palaces. The court brought people with different skills and backgrounds together, although some moved under obligations imposed by conquest. Dadu’s grandeur rested on this continuing movement of people, supplies and expertise.');
  revise('catalog-S_SONG', 'Song and neighbouring empires',
    'Song shared its world with Liao, Western Xia and Jin. These courts governed their own territories and claimed authority in their own right. Their relationships included war, trade, diplomatic missions and negotiated payments.',
    'Life across borders', 'Borders regulated movement but did not stop goods and information from passing between states. Treaties allowed rulers to coexist even when each court claimed a superior position. No single emperor could turn every such claim into control over the whole region.',
    'Overlapping dynasties', 'Jin conquered Liao’s heartland and Northern Song territory while Song continued farther south. Yuan was proclaimed before Southern Song finally fell. These were simultaneous states, not simply rulers taking turns over the same land. Their changing alliances and rivalries helped determine what each government could achieve.',
    '960–1279 covers a changing group of neighbouring states. They did not all exist throughout the entire period.');
  revise('catalog-R_NSONG', null,
    'Zhao Kuangyin founded Song in 960 and brought much of the divided territory to its south under the new dynasty. The court governed from Kaifeng until Jin forces captured it in 1127.',
    'Keeping generals under control', 'The court needed large armies to defend its territory, but powerful commanders could also threaten the ruling family. Officials had to organize money, appointments and military command so that generals could fight effectively without taking the throne. Stronger control from the centre brought both protection for the emperor and difficulties at the frontier.',
    'Education and office', 'Examinations encouraged families to invest in classical learning. Printing made books more available, yet study still required time, teachers and support. Achievement could open doors, while family resources and connections continued to matter. Scholarship became a major route to influence without giving every household an equal chance.');
  revise('catalog-R_SSONG', null,
    'After the loss of Kaifeng in 1127, the Song court survived in the south and eventually settled at Lin’an, today’s Hangzhou. A smaller territory still provided substantial wealth from agriculture, cities and trade.',
    'A growing capital', 'The court increased demand for homes, services, luxury goods and official employment in an already prosperous region. Merchants and craftspeople supplied this expanding urban world. Some southern artworks deliberately recalled northern styles, helping the displaced court and its patrons express continuity with the past.',
    'Paying for resistance', 'Taxes and maritime connections supported prolonged defence against Jin and later the Mongols. Fortifications, diplomacy and transport by water helped turn resources into military strength. The final Mongol conquest followed decades of warfare. Southern Song’s prosperity supported a durable government, although wealth alone could not ensure that its borders would hold.');
  revise('catalog-E_SONG_SOUTH', 'Southern Song foundation',
    'Zhao Gou, a surviving son of Huizong, became Emperor Gaozong in 1127 after the capture of the northern court. His accession kept the Song ruling house in power while its government searched for a defensible base.',
    'A difficult succession', 'Gaozong’s father and the former reigning emperor remained alive in captivity. He had to claim authority while presenting himself as the protector of their dynasty. Recovering the north therefore raised a question beyond territory: the return of captive emperors could also affect his own position.',
    'Rebuilding a government', 'Officials, documents, tax collection and armed forces had to be gathered around the new ruler. The court moved repeatedly before settling for the long term at Lin’an. Art and ceremony helped present the new government as the rightful continuation of Song. Behind those claims lay the practical work of rebuilding institutions after the destruction of their former centre.');
  revise('catalog-R_FIVE_LATER_LIANG', null,
    'Zhu Wen founded Later Liang in 907 after gaining control over the Tang emperor. He had once fought as a rebel, then served as a Tang commander. Taking the imperial title ended Tang formally, but rival powers contested his new court.',
    'A commander changes sides', 'Zhu Wen’s career crossed the boundaries between rebellion, service and rulership. His military power survived changes of allegiance. Connections with troops and access to resources could matter more than loyalty to a single dynasty throughout a lifetime.',
    'A contested throne', 'The imperial title allowed Zhu Wen to make appointments and demand recognition, but other commanders still controlled their own resources. Later Liang had to fight for territory and acceptance. Replacing the emperor did not immediately bring the divided regions under one government.');
  revise('catalog-R_FIVE_LATER_TANG', null,
    'Li Cunxu defeated Later Liang and founded Later Tang in 923. He drew on a Shatuo military background while claiming to restore Tang authority. The conquest of Sichuan in 925 enlarged his dynasty’s territory.',
    'The appeal of the Tang name', 'A restoration claim offered a familiar reason to support the new ruler. Yet this was a new military coalition, rather than the uninterrupted continuation of the Tang court that fell in 907. A shared dynastic name could express political ambition without proving direct continuity.',
    'The limits of conquest', 'New territory brought supplies and income, along with commanders who needed supervision and rewards. Military victories did not settle relationships within the ruling coalition. Internal conflict remained a danger even as the dynasty’s reach expanded.');
  revise('catalog-R_FIVE_LATER_JIN', null,
    'Shi Jingtang founded Later Jin in 936 with Khitan military support. In return, he ceded the Sixteen Prefectures, including the area around today’s Beijing, and accepted a subordinate relationship to the Khitan ruler.',
    'The price of support', 'The alliance helped Shi Jingtang take the throne, but its obligations continued after his victory. His government depended on a bargain that restricted its freedom to act. Successors inherited these terms even when they wanted a different relationship with the Khitan court.',
    'A lasting territorial consequence', 'The concessions changed the strategic position of later governments as well as Shi’s own. Conflict over the relationship contributed to Later Jin’s destruction and the Khitan occupation of its capital in 947. A deal made to win a domestic power struggle had reshaped the wider region.');
  revise('catalog-R_FIVE_LATER_HAN', null,
    'Liu Zhiyuan founded Later Han in 947 after Khitan withdrawal left a gap in northern power. His early death put a young successor opposite powerful commanders. Guo Wei took over in 951, ending the dynasty.',
    'A throne without the same loyalties', 'Liu’s authority rested on relationships built during his own military career. His successor inherited his title but could not automatically inherit the trust of commanders or the ability to reward them. Turning a founder’s personal authority into a stable succession proved difficult.',
    'The Northern Han branch', 'A related Liu-family court continued in Shanxi as Northern Han. The short northern dynasty and the longer-lived regional state shared a family connection but followed different political paths. Later Han ended in 951; Northern Han survived until 979.');
  revise('catalog-R_FIVE_LATER_ZHOU', null,
    'Guo Wei founded Later Zhou in 951. His successor Chai Rong continued to strengthen its armies and government and extend its territory. Song inherited much of this work when it replaced Later Zhou in 960.',
    'Preparing for expansion', 'Campaigns required reliable command, income and a workable order of attack. Proposals included concentrating on the south first, though a proposed strategy was not a guarantee of how events would unfold. Military and administrative preparation began before the Song founder took the throne.',
    'What survived the dynasty', 'A change of ruling family did not erase the armies, tax arrangements and experience built under Later Zhou. These resources helped Song continue expansion. The dynasty was brief, but its contribution lasted beyond the nine years in which its own family held the highest offices.');
  revise('catalog-R_TEN_WU_YANG_WU', null,
    'Yang Xingmi built regional power while holding late Tang titles. His recognition as a prince in 902 is commonly used to mark the beginning of Wu. The Xu military family later dominated the Yang rulers before Southern Tang was founded in 937.',
    'Power before independence', 'The title recognized authority that Yang had already been building. Appointment by the Tang court and control of local troops could reinforce one another. A regional state could grow through imperial offices and then survive beyond the empire that had granted them.',
    'From Wu to Southern Tang', 'Replacing the Yang ruling family with Xu/Li leadership changed who claimed the throne. It did not remove the region’s established government and resources. Southern Tang inherited this foundation, so the two states were closely connected despite their different dynastic names.');
  revise('catalog-R_TEN_FORMER_SHU', null,
    'Wang Jian founded Former Shu in Sichuan in 907 after building strong regional military power. Later Tang conquered it in 925. Sichuan’s protected geography helped sustain independence without cutting the court off from other states.',
    'The advantages of Sichuan', 'Difficult approaches could slow invading armies, while a productive region supplied the court. These advantages still needed officials, resources and cooperation from commanders. Mountains could make conquest harder; they could not settle conflicts within a government or guarantee its survival.',
    'A court among rivals', 'Former Shu maintained diplomatic relations and claimed imperial standing. Support for cultural life helped its rulers establish prestige alongside their military and political claims. It belonged to a competitive world of regional courts, each seeking recognition and security.');
  revise('catalog-R_TEN_WUYUE', null,
    'The Qian family governed Wuyue in the lower Yangtze region from 907 to 978. Regional wealth, diplomacy and religious support helped it outlast many neighbouring states. Its final submission to Song was negotiated.',
    'Recognition and local control', 'Wuyue accepted titles and recognition from northern courts while preserving substantial control at home. This arrangement offered another route to survival besides claiming authority over the whole empire. Diplomatic compromise could protect the ruling family and the resources of its region.',
    'Changing religious support', 'Early rulers supported a range of Buddhist and Daoist institutions. Under the last king, support became more concentrated on particular Chan Buddhist lineages. Religious life developed through changing relationships between rulers and communities, rather than a single policy maintained unchanged for the whole dynasty.');
  revise('catalog-R_TEN_CHU_MA_CHU', null,
    'Ma Yin’s Chu ruled from Hunan and drew income from regional production and trade, including tea. The Ma family’s court ended in 951, but some local commanders continued to hold power afterward.',
    'Tea across borders', 'Tea connected growers and merchants with customers and courts beyond Chu. Income from this trade helped sustain the state alongside diplomacy with stronger neighbours. Political division did not sever commercial routes; a regional government could depend on exchange across its borders.',
    'After the Ma family', 'The end of the ruling house did not immediately bring all of Hunan under another state’s administration. Local military leaders could retain control after the dynasty fell. This is why a history of autonomous Hunan can extend beyond the narrower dates assigned to Ma Chu.');
  revise('catalog-R_TEN_MIN', null,
    'The Wang family’s Min state developed in Fujian, drawing resources partly from coastal trade. Conflict within the ruling house divided it before its conventional end in 945. Some local centres continued under separate leaders.',
    'A trading coast still needed government', 'Sea routes brought opportunities, but rulers also needed to govern inland districts, maintain support and manage succession within the family. Commercial resources could strengthen a court without protecting it from internal conflict. Min’s troubles grew within a region that remained connected to maritime exchange.',
    'Different local endings', 'Ports and districts did not all change rulers at the same moment. Some local authorities survived the Wang court’s fragmentation. The disappearance of the Min dynastic name therefore marks one political ending, rather than an immediate break in every community’s institutions.',
    '909–945 is the conventional dynastic span. Some local port rulers survived the fragmentation of the Wang court.');
  revise('catalog-R_TEN_SOUTHERN_HAN', null,
    'Southern Han ruled from Guangzhou and participated in sea trade and regional commerce. Its surviving coins and tax records reveal some of the everyday work behind a regional imperial court.',
    'Coins and salt taxes', 'Lead coins were issued in Guangzhou from 917. Silver ingots wrapped in receipts record salt-tax payments, including the metal’s weight and purity. Such details show officials keeping track of the value they collected. These finds reveal particular practices, even though they cannot tell us the size of the whole economy.',
    'Ruling a coastal state', 'The court claimed imperial standing before its subjects and other rulers. Merchants and local leaders also dealt with it through trade, taxation and practical needs. Southern Han depended on these relationships as well as on the authority of its rulers. Its coastal position became a source of strength through the work of connecting commerce with government income.');
  revise('catalog-R_TEN_JINGNAN_NANPING', null,
    'Jingnan, also called Nanping, was a small state centred on Jiangling and important river routes. Its rulers maintained a separate court for decades while dealing with stronger neighbours.',
    'The value of location', 'A court on useful routes could gain influence by managing connections and exchange. Trade and diplomatic payments operated together. Jingnan’s importance came partly from its position between other states, rather than from commanding a vast territory or the largest army.',
    'Room to govern', 'Accepting another ruler’s titles and making payments could coexist with real control at home. Jingnan’s leaders had limited bargaining power, but enough to preserve a local court for a time. Their independence rested on a changing set of relationships rather than complete freedom from outside pressure.');
  revise('catalog-R_TEN_LATER_SHU', null,
    'Meng Zhixiang founded Later Shu in Sichuan in 934, turning a governorship under Later Tang into an independent court. Under Meng Chang, the state sustained regional government and literary life until Song conquered it in 965.',
    'An imperial office becomes a throne', 'When northern supervision weakened, a regional commander could use his existing position to seek greater independence. Later Shu grew from offices and resources already established in Sichuan. The authorities these institutions answered to changed, while much of the machinery of local government continued.',
    'Two Shu dynasties', 'Later Shu ruled much of the same region as Wang Jian’s Former Shu, but belonged to a different family. Regional culture and institutions could survive a change of dynasty and find new patrons. The shared name describes a connection to Sichuan, not the return of the earlier ruling house.');
  revise('catalog-R_TEN_SOUTHERN_TANG', null,
    'Southern Tang inherited Wu’s regional government in 937. Its rulers claimed imperial standing and expanded into neighbouring territory before losing ground to northern powers. The last ruler, Li Yu, is especially remembered for his poetry.',
    'Claiming the Tang inheritance', 'The dynasty used ancestry claims and the Tang name to present its rule as legitimate. That connection was politically constructed and argued over. The name alone does not prove a straightforward family line from the earlier Tang emperors.',
    'A court beyond its poems', 'Li Yu’s literary fame is one part of the state’s history. Its rulers also maintained armies, collected income and negotiated with rivals. Poetry and government existed in the same court, but literary achievement does not by itself explain military defeat. Southern Tang’s end came through a struggle with stronger northern power.',
    '937–975 follows the conquest-year convention. Some chronologies use 976 because of dating conventions.');
  revise('catalog-R_TEN_NORTHERN_HAN', null,
    'Northern Han preserved a Liu-family court in Shanxi after Later Han fell in 951. It relied on Liao support while claiming imperial authority of its own. Song conquered it in 979.',
    'A stronger ally', 'Liao ties offered protection and recognition, while limiting the court’s choices. Depending on an ally did not mean giving up every claim to authority at home. Northern Han’s rulers combined an imperial title with the practical need for support from a larger neighbour.',
    'The northern kingdom', 'Despite its location, Northern Han is traditionally counted among the Ten Kingdoms. It also survived beyond Song’s foundation in 960. Its history helps explain why neither the name Ten Kingdoms nor the end of the Five Dynasties describes a single tidy boundary in place or time.');
  revise('catalog-S_TEN', null,
    'The Ten Kingdoms were regional states around the transition from Tang to Song. They began and ended at different times and did not all exist together. Northern Han, despite the common association of these kingdoms with the south, lay in the north.',
    'Life beyond the northern courts', 'Some kingdoms lasted much longer than the rapidly changing Five Dynasties in the north. Their governments supported farming, sea trade, religious institutions and cultural life. Warfare mattered, but its effects differed across regions; political division did not make every place equally unstable.',
    'Different paths to Song rule', 'The states varied in size and in their relationships with stronger neighbours. Some were conquered, while others negotiated submission. Each ruling house relied on its own combination of local resources, military support and diplomacy. Song reunification brought these different regional histories together over time.',
    '902–979 is a broad span for the regional kingdoms, extending beyond the northern Five Dynasties period of 907–960.');
  revise('sui-grand-canal', 'Grand Canal',
    'Emperor Yang joined and enlarged older waterways into a vast transport network. Work on the Tongji Canal began in 605, and the Jiangnan extension was completed in 610. These projects connected regional routes around Luoyang rather than creating one entirely new canal.',
    'Grain for capitals and armies', 'Sui had reunited north and south in 589. The canals helped make that territory governable by carrying southern grain toward northern political centres. A northern branch supplied frontier armies. Harvests collected far from the court could now feed officials and soldiers elsewhere, linking local production to the needs of a much larger empire.',
    'The labour behind the waterway', 'Construction demanded enormous amounts of labour. These burdens helped give Emperor Yang a reputation for destructive excess. Yet Tang and later dynasties continued to benefit from the network. Its lasting usefulness and its immediate human cost belong to the same story: generations of rulers inherited infrastructure that people under Sui had been compelled to build.');
  revise('movable-type', null,
    'Bi Sheng made individual clay characters that could be arranged for printing and used again. Shen Kuo described this work during the Qingli period, 1041–1048. His account preserves both Bi Sheng’s name and the practical details of the method.',
    'Reusable characters or a whole page', 'Movable characters could be rearranged for different texts, but setting them took work. Woodblocks preserved a complete page for reprinting and could combine writing with images. Both methods remained useful because different printing jobs had different costs. Reusability did not make movable type the best choice for every book.',
    'A craftsman in a scholar’s book', 'Much of what we know about Bi Sheng comes through Shen Kuo. By recording the materials and procedure, Shen preserved knowledge that might otherwise have remained within a workshop. The account tells us that this technique was being practised in the stated period; it does not supply a precise day when movable type was first invented.');
  revise('qingming-scroll', null,
    'Zhang Zeduan’s Northern Song handscroll moves from a rural approach into a busy riverfront and city. Boats, workers, shops and customers fill its scenes. The original survives in the Palace Museum in Beijing.',
    'Follow the river', 'Water transport brings supplies toward the city, while streets connect people doing different kinds of work. At the bridge, interacting tasks and hazards draw the viewer into the activity. The city’s prosperity appears through people moving goods and serving customers, as well as through its buildings.',
    'What a painting can show', 'The artist selected and arranged these scenes. They offer a rich view of urban life, but cannot serve as a complete record of Kaifeng’s population or economy. Later artists made their own versions for different audiences and purposes. Those copies reveal the worlds in which they were produced, so they should be distinguished from the Northern Song original.');
  revise('xuanwu-gate', 'Xuanwu Gate coup',
    'Li Shimin’s path to the throne passed through an ambush in 626. His followers killed Crown Prince Li Jiancheng and their brother Li Yuanji at the palace’s northern gate. Their father later abdicated, and Li Shimin became Emperor Taizong.',
    'Securing the throne and its story', 'The killings left Taizong with a difficult claim to justify. His court brought collaborative historical writing into the palace and gave him a larger role in accounts of the dynasty’s foundation. Control of the government also gave the victor influence over how the struggle would be remembered.',
    'The celebrated emperor', 'Taizong later acquired a reputation for good government. That achievement and the violent succession are both parts of his reign. The deaths of his brothers are well established, while accounts presenting his victory as inevitable or entirely justified need more caution. Later readers inherited a story shaped partly by the court that benefited from the coup.',
    '626 CE.');
  revise('xuanzang-return', 'Xuanzang’s return',
    'Xuanzang returned to Chang’an in 645 carrying Buddhist manuscripts. He had begun his journey despite an imperial travel prohibition. The traveller who left without permission now received recognition at the imperial centre.',
    'The work of translation', 'Bringing manuscripts home began another long task. Translators needed to compare texts, decide on meanings and work together with continuing institutional support. Xuanzang sought to resolve differences among the Buddhist writings already available in China. His account of the western regions also preserved knowledge of societies beyond Tang rule.',
    'Learning from beyond the empire', 'Xuanzang studied Buddhist thought at Nalanda (那烂陀寺), a major monastery and centre of learning in India, before bringing texts back to China. Buddhism was already established in China before Xuanzang travelled. He helped transform that existing tradition by bringing new texts and expertise into it. Chang’an’s intellectual life depended partly on knowledge acquired elsewhere and made accessible through collective work. Later religious biographies emphasized his heroic journey, while the translation enterprise required many people after he arrived home.');
  revise('talas', 'Battle of Talas',
    'In 751, Tang forces were defeated by an Abbasid army at Talas in Central Asia. The defeat showed the difficulty of projecting military power far from the imperial court. It did not end contact between the two worlds.',
    'Contacts after the fighting', 'Abbasid embassies continued to visit the Tang court after the battle. Du Huan, taken captive, eventually returned by merchant ship with observations of life abroad. Diplomats and merchants could keep moving even while armies fought. Military rivalry and exchange were part of the same connected region.',
    'Did captives spread papermaking?', 'A famous story credits captured Chinese papermakers with bringing the craft to the Islamic world. The details remain disputed. Paper was already used in Central Asia before 751, and the battle’s exact role in spreading production is uncertain. Talas cannot securely be treated as the single moment that transferred the technology or instantly transformed the region’s religion.');
  revise('two-tax', 'Two-Tax reform',
    'In 780, Yang Yan proposed taxing households where they actually lived and grading their payments by wealth. Collection took place in summer and autumn. The government was trying to raise income from a population that no longer fitted its older records.',
    'Finding people and property to tax', 'The proposal covered settled farmers and travelling merchants. Instead of relying only on inherited household categories, officials would assess the property and activity they could identify. This changed both how the court collected money and the basis on which households owed it.',
    'Who carried the burden?', 'The official Lu Zhi warned that the reform made emergency wartime demands permanent. He also argued that farming property was easy to find while mobile wealth could escape assessment. A more adaptable system was therefore not necessarily fairer. The name Two Taxes refers to the two collection seasons, rather than simply to two kinds of taxable goods.',
    '780 CE. Surviving memorials record both Yang Yan’s proposal and Lu Zhi’s criticism.');
  revise('huichang', 'Huichang suppression of Buddhism',
    'In 845, Emperor Wuzong ordered a major suppression of Buddhism. Clergy were forced back into lay life, and the state took control of monastic resources. Other religious communities were also targeted.',
    'Religion, labour and property', 'Wuzong’s edict accused religious institutions of consuming wealth and labour while avoiding duties to families and the ruler. Taking their property and returning clergy to ordinary registration would redirect resources toward the state. Religious hostility and the emperor’s Daoist commitments worked alongside these material interests.',
    'A deeply rooted tradition', 'The court described Buddhism as foreign, although it had long been embedded in Tang society. That accusation helped justify persecution; it did not describe the loyalties of every believer. Official reports of destruction also came from the government carrying it out, so their totals cannot be treated as independently verified counts.',
    '845 marks the major suppression, following earlier restrictions. Transmitted totals for clergy affected conflict.');
  revise('huang-chao', 'Huang Chao’s occupation of Chang’an',
    'Huang Chao’s forces entered Chang’an at the beginning of 881. Their occupation, interrupted by renewed fighting, continued until 883. War damaged the farming that supplied the city, and famine added to the suffering caused by violence.',
    'Holding a capital', 'Possession of Chang’an gave Huang Chao a powerful symbol of imperial authority. Keeping a government alive required more: food for inhabitants, control of the surrounding countryside and dependable military support. Capturing the palace did not automatically provide these things.',
    'A city damaged by war', 'The destruction reached beyond court politics into the livelihoods that sustained urban life. Tang survived until 907, so people living through the occupation did not yet know its eventual dynastic outcome. Chang’an’s immediate crisis was one of fighting, disrupted supplies and hunger, as well as a struggle over who would rule.');
  revise('tang-end', 'Tang’s fall and Later Liang’s foundation',
    'Zhu Wen established Later Liang in 907, ending Tang and beginning the northern Five Dynasties sequence. He had previously fought in Huang Chao’s rebellion and then become a Tang military commander.',
    'From rebel to emperor', 'Zhu Wen carried military power through several changes of allegiance. The troops and connections that supported an imperial servant could later support a claimant to the throne. Tang’s formal end confirmed a shift toward regional commanders that had already been developing.',
    'Different regional experiences', 'Northern dynasties changed frequently, while some southern kingdoms lasted longer and supported considerable prosperity. Tang’s fall therefore did not produce the same conditions everywhere. The Five Dynasties and Ten Kingdoms were overlapping governments in different regions, rather than fifteen rulers succeeding one another over a single united territory.');
  revise('tang-code', 'Tang Code',
    'The official commentary completed in 653 explained how officials should apply the Tang Code. It connected punishments with rules for deciding cases. The code made social relationships a central part of written law.',
    'The relationship changed the punishment', 'An offence was judged through the conduct involved and the relationship between the people concerned. Kinship, rank and position could affect its legal meaning and penalty. Officials therefore needed guidance for cases where several rules and relationships overlapped. The commentary made hierarchy part of a systematic legal framework.',
    'A lasting legal model', 'Later Chinese codes and legal systems elsewhere in East Asia drew on Tang precedents. Written rules could travel and outlast the dynasty that developed them. But a code describes what officials were supposed to do, rather than proving what happened in every dispute. Local circumstances and actual enforcement could differ from the order prescribed on the page.');
  revise('li-bai-du-fu', 'Li Bai and Du Fu',
    'Li Bai and Du Fu wrote in a world of friendship, travel, court connections and political ambition. Their poetry includes responses to war, displacement and disappointed hopes around the An Lushan Rebellion, alongside humour and intimate exchanges.',
    'What a poem could do', 'Poems maintained friendships, marked journeys, sought recognition and commented on government service. Writing belonged to social life as well as personal expression. Both poets worked within this world, even though later readers often contrasted Li Bai’s inspired wandering with Du Fu’s concern for suffering.',
    'War in a poet’s voice', 'Du Fu’s war poems convey how catastrophe could be experienced and understood. Their words are shaped by selection, literary references and a speaking voice; they are not population records. Later collections and commentaries helped make particular poems classics. Their lasting power comes partly from how carefully individual experience was turned into language.');
  revise('tang-women-riding', 'Women riders in Tang China',
    'Tang tomb figures show women on horseback, and evidence of riding sports places some women within an active courtly culture. Horses, leisure and elaborate burial goods required wealth. These objects chiefly illuminate the lives and ideals of privileged circles.',
    'Riding and status', 'Riding and polo could make women visible participants in elite life. Court fashion and the prestige of horses helped shape those opportunities. This evidence challenges the idea that elite women were always secluded, but does not establish equal legal rights or tell us how women in poorer households lived.',
    'Why place a rider in a tomb?', 'Burial figures were chosen to furnish or evoke an afterlife and express the deceased person’s standing. Their clothing and poses show what patrons wanted represented alongside them. They can reveal valued activities and styles, while remaining carefully selected images rather than a complete picture of ordinary streets.',
    'About 700–750 is a broad context. The cited objects span the seventh and eighth centuries and mainly represent elite life.');
  revise('lu-yu-tea', 'Lu Yu’s Tea Classic',
    'In the later eighth century, Lu Yu gathered knowledge about tea plants, processing, utensils, water and preparation into the Tea Classic. People already drank tea. His book helped turn practical expertise and judgments of taste into a lasting written authority.',
    'The work behind a cup', 'Tea depended on cultivation, processing, fuel, water and the tools used to prepare it. Lu Yu treated these choices as things a knowledgeable drinker could judge. Taste was connected to materials and methods, so the book recorded detailed practical knowledge alongside ideas about refinement.',
    'A guide with a long afterlife', 'The Tea Classic explains how Lu Yu wanted tea understood and prepared. It does not show that every Tang household followed his instructions. Later readers built further practices and ideas around the book, expanding its influence beyond its first audience. The lasting tradition grew over time rather than appearing fully formed in one uniform ceremony.',
    'About 760–780 is an approximate writing and development range; 780 is a common completion date. Tea drinking predates Lu Yu.');
  revise('song-paper-money', 'Song paper money',
    'In the 1020s, the Song government took over the issuing of paper certificates in Sichuan. Known as jiaozi, they developed from merchant arrangements that made payments easier than carrying heavy strings of coins.',
    'Why accept a piece of paper?', 'The notes depended on trust in the issuer and on rules for using and redeeming them. Government backing could make them more dependable, while issuing money also gave officials a way to fund spending. Their value came from these arrangements, not simply from the printed sheet.',
    'Money with boundaries', 'Early notes were valid within particular regions and conditions. They did not immediately become one currency accepted everywhere. Coins, commodities and different paper issues continued side by side. Successful use depended on administration, control over how much was issued and the payments people could make with it. Paper money solved a practical problem, while creating new responsibilities for its issuer.');
  revise('song-wang-anshi', null,
    'Wang Anshi launched the New Policies in 1069 under Emperor Shenzong. They sought to change government finance, administration and military support. One proposal offered farmers public loans before harvest, to be repaid alongside seasonal taxes.',
    'Loans before the harvest', 'Wang argued that public reserves could provide useful credit and reduce farmers’ dependence on private lenders. Stronger households could also support a stronger state. In practice, officials facing lending and collection targets might prioritize income over a borrower’s circumstances. The same programme could offer help or impose pressure depending on how it was carried out.',
    'A dispute over the state’s role', 'Critics questioned whether officials could run these programmes well and whether intervention would add burdens. They were not all opponents of change. The argument concerned what good government should do with money and how far it should enter economic life. Changes at court repeatedly altered the policies’ prospects.',
    '1069 marks the launch of the New Policies. The crop-loan memorial sets out the reformers’ case, rather than an independent account of its results.');
  revise('song-shen-kuo', null,
    'Shen Kuo’s Dream Pool Essays, also called Brush Talks, gathered observations about astronomy, geography, technology, medicine and other subjects. The work is commonly dated to about 1088, though completion is estimated between 1088 and 1095.',
    'Clues that challenged an explanation', 'Fossil bamboo found where bamboo no longer grew suggested an earlier, different environment. The changing timing of tides challenged a simple explanation based on the sun. Shen compared ideas with observations that did not fit, then tried to explain the mismatch. His interest was in the reasoning as well as the surprising object or event.',
    'Knowledge for practical work', 'As a scholar-official, Shen brought calculation and observation to government problems too, including how far carriers could supply an army. Some explanations were mistaken, and inherited ideas about the universe shaped his thinking. The book preserves both careful inquiry and the limits of the knowledge available to him.',
    'About 1088 is approximate; completion is estimated between 1088 and 1095.');
  revise('song-zhu-xi', 'Zhu Xi and White Deer Grotto Academy',
    'During his Nankang appointment beginning in 1179, Zhu Xi revived White Deer Grotto Academy. His rules connected learning with the effort to improve one’s character and conduct toward others, rather than treating study only as preparation for office.',
    'Learning as daily practice', 'Teachers, students and books came together in an academy where ideas could be practised and discussed. Zhu linked moral development with understanding the patterns of the world. His influence spread through teaching routines, relationships and shared texts as well as through his own writing.',
    'Authority came later', 'Zhu faced controversy and political hostility during his life. His interpretations of the Four Books later gained exceptional official influence, especially in examinations. A contested approach to learning became a standard against which candidates were judged. That later authority preserved his work while limiting which answers students could safely give.',
    '1179 marks the academy’s revival during Zhu Xi’s Nankang appointment. Official adoption of his interpretations in examinations came later.');
  revise('song-quanzhou', 'Quanzhou port',
    'A Maritime Trade Office was established at Quanzhou in 1087. The Fujian port’s Song and Yuan prosperity depended on workshops, bridges, docks, officials and religious communities, connected across a landscape extending well inland.',
    'From workshop to ship', 'Ceramic kilns and iron producers supplied goods for trade. Roads and waterways carried them toward the harbour. The port depended on workers and transport far beyond the waterfront, so its overseas connections began with local production and the journey to the docks.',
    'A place where communities stayed', 'Religious buildings and monuments show that different communities established a lasting presence. Officials regulated trade and collected income, while merchants maintained the services and relationships that made commerce possible. Quanzhou grew through these combined efforts. Its prosperity depended on government organization and on networks that extended beyond what officials alone could create.',
    '1087 dates the trade office, not the city’s foundation. Quanzhou’s trading system developed over centuries.');
  revise('yuan-religions', 'Religion under Yuan rule',
    'Yuan rulers supported religious specialists from several traditions, with Tibetan Buddhism particularly influential at court. Buddhist, Daoist, Muslim and Christian communities took part in an empire that moved people and knowledge across great distances.',
    'What rulers and clergy offered each other', 'Religious specialists could provide learning, rituals and claims to sacred authority. Rulers could grant resources, privileges and protection. Communities competed for access to this support, and imperial favour could change. The presence of several religions did not give all of them equal standing or an independent right to the same treatment.',
    'Art across long distances', 'Artisans and patrons brought styles and techniques into new settings. Some travelled for opportunity; others moved because of conquest or forced service. The resulting works reflect skilled labour and particular commissions. Their variety reveals the empire’s far-reaching connections, along with the unequal conditions under which people contributed to them.');
  revise('yuan-blue-white', 'David Vases',
    'An inscription on the David Vases records Zhang Wenjin’s donation to a Daoist temple in 1351. Made at Jingdezhen, the vessels carry blue decoration beneath the glaze. They show that highly accomplished blue-and-white porcelain existed before the Ming dynasty.',
    'A date written on the object', 'Ceramics without dates are often compared through their shapes, materials and decoration. These vases provide a firm reference point. They helped overturn an older belief that porcelain of this mature kind belonged only to Ming times. A securely dated object can change how many other surviving pieces are understood.',
    'A gift for a family’s protection', 'Zhang Wenjin requested protection and blessings for his family. The vases began as a religious gift, bringing skilled manufacture into a relationship between a household and a temple. They later became famous under a collector’s name. Their inscription preserves the earlier donor and purpose, long before they entered the modern art market.');
  revise('niu-li-disputes', 'Niu–Li court disputes',
    'Early ninth-century court conflicts are commonly called the Niu–Li struggle, after Niu Sengru and Li Deyu. Officials fought over appointments and policy, rising and falling as influence at court changed. It is uncertain whether they belonged to two stable, clearly separated factions.',
    'Changing alliances', 'A familiar explanation places examination graduates on one side and hereditary aristocrats on the other. Actual careers and personal relationships do not divide so neatly. Connections, views on policy and access to rulers shifted over time. A dispute over one appointment did not necessarily reflect the same two permanent camps as every other dispute.',
    'Why the label needs care', 'Later accounts gave these conflicts a continuous story, sometimes presenting them as a warning about factional politics or as a struggle between social groups. The conflicts themselves were real, but their organization into one long contest is disputed. Keeping the familiar name need not imply certainty about who consistently belonged on either side.',
    'About 820–850 covers the principal disputes. The existence and membership of two stable factions remain contested.');
  revise('yue-fei', 'Yue Fei',
    'Yue Fei was a leading Southern Song commander against the Jurchen Jin. His successful campaigns, recall and execution in 1142 made him a lasting symbol of loyalty. His career unfolded amid disagreements about recovering territory, negotiating peace and controlling powerful generals.',
    'Campaigns and court decisions', 'Recovering the north required money, supplies and continued military risk. The court also sought a settlement it could sustain and worried about its control over commanders. These pressures help explain the choices surrounding Yue’s career without justifying his execution. His death cannot be reduced to proof that victory would otherwise have been certain.',
    'The remembered loyal general', 'Later generations found different meanings in Yue’s loyalty: service to his dynasty, personal moral courage and modern national identity. Poems, tattoo stories and family anecdotes helped carry that reputation. Their evidence is uneven, so famous stories should not all be treated as equally reliable accounts from his lifetime.');
  revise('song-gunpowder', 'Gunpowder in the Wujing Zongyao',
    'The Wujing Zongyao, a military reference work completed in 1044, recorded gunpowder recipes and military uses. It preserves knowledge developed through earlier experiments. Weapons that used fire came before the mature firearms familiar from later centuries.',
    'From recipe to weapon', 'Ingredients, proportions and preparation all mattered. Armies also needed supplies, manufacturing and training to turn a written formula into something useful in battle. Recording instructions helped knowledge travel beyond one workshop, but the presence of a recipe does not mean every army had the equipment or experience to use it effectively.',
    'Knowledge crossed battle lines', 'Song’s opponents also acquired weapons, engineers and techniques. An innovation could spread to rivals rather than securing a permanent advantage for its first users. Sieges and other military demands shaped which uses developed. Gunpowder warfare grew through repeated adaptations as different armies learned how to produce and deploy it.');
  revise('red-turbans', 'Red Turban rebellions',
    'Rebellions beginning in 1351 challenged late Yuan rule. Religious hopes for a renewed world helped bring followers together, but the groups called Red Turbans were not one unified army. Zhu Yuanzhang emerged from this wider struggle and eventually founded Ming.',
    'From rebellion to government', 'Promises of renewal could attract supporters. Holding territory then required grain, taxes and cooperation with influential local families. Leaders changed alliances and political language as they tried to build lasting governments. A movement organized for revolt could not govern simply by growing larger.',
    'Rivals for power', 'Zhu Yuanzhang had to defeat competing forces as well as overcome Yuan authority. As imperial control weakened, several leaders pursued their own projects, and military advantage shifted repeatedly. Shared symbols and connections linked Red Turban groups, but their armies could also compete. Ming’s eventual victory was the outcome of that struggle, not a destination agreed by every rebel.');
  revise('sui-examinations', 'Imperial examinations under Sui',
    'The Sui period is associated with the emergence of imperial examinations, with 605 often used for the advanced-scholar examination. Written tests became one route toward government service. Recommendations, family standing and other routes remained important.',
    'What candidates studied', 'Testing made demonstrated knowledge relevant to promotion. Over time, the subjects examined and the answers accepted shaped education and family ambitions. This influence grew gradually. Early Sui examinations did not yet have the much greater role that examinations would acquire under later dynasties.',
    'Opportunity with limits', 'Preparation took time, teachers and material support. Rules about eligibility and nomination could also restrict participation. Examinations changed how officials were chosen without making access equal. The system lasted through repeated changes in its design, rather than following one complete plan created under Sui.',
    '605 is a conventional date. Earlier recruitment tests existed, and definitions of the first imperial examination differ.');
  revise('zhenguan-government', 'Taizong’s Zhenguan era',
    'Taizong’s Zhenguan era, 627–649, became a famous model of imperial government. Later collections portrayed him debating policy and listening to criticism from ministers. Those texts preserved ideals of good rule as well as memories of a particular reign.',
    'Speaking honestly to an emperor', 'Ministers were expected to point out dangers, but the emperor still held the power to appoint and punish them. Honest advice depended on a ruler’s willingness to listen within that unequal relationship. Accounts of Taizong accepting criticism later gave officials examples they could use when urging other monarchs to heed advice.',
    'A model across East Asia', 'The Essentials of Governance circulated beyond Tang China and influenced later political debate. Its selected conversations offered lessons, rather than an unedited record of everything said at court. Taizong’s authority also rested on military and administrative institutions and followed a violent succession struggle. The admired model captures one important part of that larger history.');
  revise('kaiyuan-era', 'Xuanzong’s Kaiyuan era',
    'Xuanzong’s Kaiyuan era, 713–741, is remembered as a high point of Tang prosperity. Court support for the arts, skilled production and imperial reach contributed to its reputation. That prosperity was not shared equally by every region or household.',
    'The work behind fine objects', 'Elite possessions reveal skilled workshops and resources drawn toward wealthy patrons. Storehouses and court commissions helped organize production. Finished objects preserve the tastes of their owners more clearly than the lives of the people who supplied materials and labour. Cultural splendour depended on this less visible work.',
    'Prosperity before the rebellion', 'The An Lushan Rebellion began later, in 755. Comparing its destruction with Kaiyuan abundance can make the whole period look like a simple warning about luxury. Military arrangements, appointments and government demands also changed over time. The era’s achievements were real, but neither its prosperity nor the later disaster made the outcome inevitable.',
    '713–741 is the Kaiyuan era, not Xuanzong’s entire reign. Shengshi means a flourishing age; the An Lushan Rebellion began in 755.');
  BEGINNER_MIDDLE.revisions["an-lushan"].note = "755 marks the outbreak; the main rebellion continued until 763. Losses in tax registers include people the government could no longer count and cannot be read directly as a death toll.";
  BEGINNER_MIDDLE.revisions["catalog-R_FIVE_LATER_JIN"].note = "936–947 is the chronology used here. Some older tables place the endpoint one year earlier. Later Jin is distinct from both the earlier Sima Jin and the later Jurchen Jin.";
  BEGINNER_MIDDLE.revisions["catalog-R_FIVE_LATER_HAN"].note = "947–951 is the chronology used here. Some older tables place the endpoint one year earlier. Northern Han survived separately until 979.";
  BEGINNER_MIDDLE.revisions["catalog-R_TEN_CHU_MA_CHU"].note = "907–951 covers Ma Chu’s broader state history; 927 is a later kingdom milestone used in some chronologies. Autonomous rule in Hunan continued beyond the Ma court’s fall in 951.";
  BEGINNER_MIDDLE.revisions["yuan-blue-white"].note = "1351 is the inscription’s dedication date, not the invention of blue-and-white porcelain. Earlier examples exist; these vases securely date an accomplished work.";
})();
if (typeof module !== 'undefined' && module.exports) module.exports = BEGINNER_MIDDLE;
