/* Beginner-facing English revisions. Historical data stays in the source records. */
var BEGINNER_EARLY = (() => {
  const revisions = {};
  const add = (id, name, description, title1, text1, title2, text2, note) => {
    const entry = { description, sections: [{ title: title1, text: text1 }, { title: title2, text: text2 }] };
    if (name) entry.name = name;
    if (note !== undefined) entry.note = note;
    revisions[id] = entry;
  };
  add('xia', null,
    'Xia is the first dynasty in the traditional account of Chinese history. Later books name its kings, but no royal records from their own time have been securely identified. Its familiar dates are therefore much less certain than those of the later Shang.',
    'The evidence at Erlitou',
    'Excavations at Erlitou reveal a major early Bronze Age centre, with large buildings for powerful families and workshops requiring skilled workers. People there could gather considerable wealth and labour. Whether they called their kingdom Xia is another question. The place and broad dates fit some later accounts, but that alone cannot identify its rulers. The settlement is real; its connection with Xia remains debated.',
    'Why later rulers told the story',
    'Later accounts describe Xia losing power because its rulers failed to govern well. Shang then takes its place. This gave later generations a way to explain why one ruling family could rightfully replace another. The tradition may preserve memories of an older world, while also expressing what later writers believed a ruler should do.',
    '2070–1600 BCE is a conventional, approximate chronology, not a securely documented sequence of reigns. Erlitou has not been proven to be Xia.');
  add('shang', null,
    'Shang sites preserve large settlements and elaborate bronze vessels. At Anyang, writing on bones and turtle shells records the concerns of late Shang kings. The earlier walled centre at Zhengzhou shows how much work rulers could organize, though the dates and identities of the earliest Shang rulers are less secure.',
    'Bronze, ancestors and power',
    'Making large bronze vessels required metal, fuel and highly skilled workers. Rulers used the vessels in offerings and feasts that displayed rank and honoured powerful ancestors. Their beauty depended on a ruling family’s ability to command resources. Large tombs reveal a harsher side of that power: people were also killed in human sacrifices.',
    'What the writing tells us',
    'The inscriptions bring us close to royal decisions, but mostly record what troubled the king and the people who interpreted signs for him. They tell us much less about ordinary households. Archaeology helps fill those gaps and reveals other Bronze Age centres beyond the court’s reach. Shang territory should not be confused with the borders of China today.',
    'About 1600–1046 BCE is the conventional range. Late Shang writing is much more securely documented than the dynasty’s precise beginning.');
  add('western-zhou', null,
    'After defeating Shang, Zhou rulers claimed that Heaven had given them the right to govern: the Mandate of Heaven. Their power depended on regional lords and influential families. Land grants and family ties helped hold this order together, though it did not work identically everywhere.',
    'Promises cast in bronze',
    'A lord receiving an appointment or reward could have it recorded on a bronze vessel used in ceremonies for ancestors. The inscription celebrated the king’s favour and helped the recipient’s descendants claim their place. Family relationships mattered, but warfare, marriage and service also bound lords to the court. The king needed these alliances to exercise power at a distance.',
    'Explaining the conquest',
    'Stories of the Zhou founders gave later rulers and noble families respected ancestors to follow. They also explained how overthrowing Shang could be justified: a ruling family might lose Heaven’s support. This argument served a dynasty born through conquest. As conditions changed, later generations retold the founding story to support their own claims about good government.');
  add('eastern-zhou', null,
    'The Zhou royal court moved east in 770 BCE. Kings kept their respected title, but regional rulers increasingly controlled their own armies, taxes and decisions. The Spring and Autumn and Warring States periods describe successive parts of this long era of competition.',
    'Stronger states around a weaker king',
    'Rival courts developed ways to collect taxes, recruit soldiers and settle disputes. The Zhou king could lose power while government elsewhere became more forceful. Officials, teachers and military advisers travelled between courts seeking support for their ideas. Competition brought destructive wars, but also new ways to organize armies and govern larger territories.',
    'Competing ideas of good rule',
    'Rulers and thinkers still appealed to Zhou ceremonies and admired figures from the past. They disagreed about what those examples meant. Confucian and Mohist teachings, among others, grew in this world of rival answers. There was no single philosophy shared by everyone. Later labels make the arguments look more neatly divided than they were when teachers and their followers first debated them.');
  add('late-warring', null,
    'The Zhou royal family lost its rule in 256 BCE, but the rival kingdoms continued fighting. Qin defeated its remaining major rivals in 230–221 BCE. These years belong to the Warring States period; they are not a separate dynasty.',
    'Keeping armies supplied',
    'Qin needed more than able commanders to win repeated wars. Farming households supplied grain and workers; officials arranged transport and deliveries between regions. Documents excavated at Liye help reveal these networks. Behind military victories lay the daily work of offices that moved supplies and kept track of responsibilities. Without that work, armies could not keep campaigning.',
    'A victory that was not guaranteed',
    'The other kingdoms defended their own rulers and formed alliances to survive. Qin’s eventual victory can make their defeat seem inevitable, but they had different possible futures in view. Conquest ended their independent courts. It did not immediately erase regional customs, languages or loyalties. The new empire had to govern people whose lives had developed under separate states.',
    '256–221 BCE covers the years after the Zhou royal house fell. The full Warring States period began earlier, and Qin’s conquests involved several campaigns.');
  add('qin', null,
    'In 221 BCE, Qin defeated its major rivals and created an empire governed through appointed officials. The dynasty fell in 206 BCE, but later rulers kept many of its methods. Its government lasted far longer in practice than its ruling family did.',
    'Making a large empire work',
    'Common measures, written records and official procedures helped officials compare goods and carry out orders across long distances. They could also help trade. For rulers, these standards made it easier to collect resources and direct people. Excavated records show many offices handling routine transfers. Even a powerful emperor depended on officials doing this work in local communities.',
    'The burden on households',
    'Military campaigns, construction and compulsory service demanded much from ordinary families. After the First Emperor died in 210 BCE, struggles over succession and rebellion broke the dynasty. Later Han writers stressed Qin’s cruelty, and their accounts need to be read alongside excavated evidence. Han’s continued use of Qin methods shows how much survived the collapse, despite the sharp criticism of its rulers.');
  add('han', null,
    'Han rulers rebuilt an empire after the wars that destroyed Qin. Its history includes Western Han, the interruption of Wang Mang’s Xin dynasty, and the restored Eastern Han. Across these centuries, government changed, classical learning grew and connections across Eurasia expanded.',
    'Sharing and gathering power',
    'Some regions were governed by appointed officials; others were kingdoms held by members of the imperial family. Disputes over these arrangements gradually increased the court’s power. Farming households supplied much of the tax income and labour. Officials still needed local knowledge and the help of influential families to turn orders from the emperor into action.',
    'Life behind the fine objects',
    'Han tombs preserve textiles, lacquerware and images of farms, servants and entertainments. They show what wealthy people valued, along with signs of the work supporting their lives. Learning from ancient texts became more important in government, but punishment and inherited privilege remained powerful. The familiar story of a cruel Qin followed by a kind Han overlooks both the methods they shared and disagreements within Han itself.',
    '206 BCE marks Liu Bang becoming king of Han; 202 BCE marks his imperial accession. Xin interrupted Han rule in 9–23 CE and appears separately.');
  add('xin', null,
    'Wang Mang replaced Han in 9 CE and founded the Xin dynasty. He tried to change landholding, slavery, currency and the government’s role in the economy, claiming to restore an ideal ancient order. Rebellion ended his reign in 23 CE. Further warfare followed before Han rule was restored.',
    'Old ideals, disruptive changes',
    'Invoking the past allowed Wang Mang to argue for sweeping reforms. But his measures disturbed powerful interests and familiar ways of doing business. Repeated changes to money created a practical problem: issuing a new currency did not ensure that people could or would use it. Officials needed the ability to carry out reforms, and the public needed reasons to trust them.',
    'A reign under pressure',
    'Floods drove people from their homes and deepened rural hardship. These disasters added to resistance and difficulties carrying out policy. The reforms’ failure had several causes. Calling Wang Mang a modern socialist is also misleading: his model was an ancient society with fixed ranks. Later Han histories judged a ruler their own dynasty had replaced.');
  add('division', 'Age of Division',
    'Between Han and Sui, rival courts ruled different parts of China. Wars drove migration, while powerful families and religious communities carried practices and learning across borders. The Age of Division is a name for this period of several competing governments.',
    'Government continued across the divide',
    'Successor states employed officials and kept methods inherited from earlier rulers. Their kings and emperors argued over who deserved to rule the empire. Even when no court controlled it all, the idea of imperial rule remained powerful. Political borders did not bring all learning, trade or government work to a halt.',
    'New regional centres',
    'Migration helped reshape society around the lower Yangtze River. In the north, courts maintained military and religious ties with Inner Asia. These regions developed their own centres of power and culture. People living through these changes did not know that a future dynasty would reunite much of the country. Their choices involved the rival courts and opportunities of their own time.');
  add('three-kingdoms', null,
    'Wei, Shu and Wu emerged as Han power collapsed. Each court claimed a right to inherit or continue imperial rule, but their territories and resources were unequal. Their formal division followed decades of fighting; it did not suddenly begin in 220.',
    'Three rival courts',
    'All three used people and methods inherited from Han. Shu claimed to restore Han, while Wei received the imperial title through a transfer from the last Han emperor. Wu established its own southern court. These were rival governments competing over an imperial inheritance, rather than three permanent national identities.',
    'What an army could sustain',
    'Commanders needed food, transport and enough people to keep campaigning. Rivers, farming settlements and cooperation with local powerful families helped determine where armies could go and how long they could stay. Later stories celebrate clever plans and memorable heroes. Those plans still faced material limits: even a talented commander could not feed soldiers or replace exhausted resources through ingenuity alone.');
  add('jin-early', null,
    'The Sima family’s Jin dynasty reunited the main successor states in 280. Fighting within the ruling family and upheaval in the north soon broke that unity. A Jin court survived in the south until 420, so the dynasty lasted much longer than its period of broad control.',
    'Princes with armies',
    'Giving imperial relatives troops and regional authority could help protect the ruling family. It also gave rival princes resources to fight one another when succession became disputed. Winning territory had not settled how power would pass between rulers or who would command the armies. Family protection became a source of destructive conflict.',
    'Starting again in the south',
    'The southern court kept the Jin name, but depended on families who had moved south and powerful people already living there. It had to build new agreements to govern. The names Western Jin and Eastern Jin describe this major change in territory and support, as well as a move of the court. The later dynasty could not simply recreate the world it had lost.');
  add('sixteen', null,
    'The Sixteen Kingdoms were competing northern states of the fourth and early fifth centuries. Their rulers drew on mixed armies and shifting alliances within former Jin territories. Older accounts use the derogatory label “Five Barbarians” for Xiongnu, Jie, Xianbei, Di and Qiang groups. These were not five united peoples carrying out one invasion.',
    'How rulers built support',
    'Founders from different communities adopted imperial titles, recruited officials and governed mixed populations. Their family origins alone cannot explain how their states worked. Alliances among commanders, inherited methods of government and support for religious communities helped rulers gather authority. Loyalties could shift as courts rose and fell.',
    'How historians count the Sixteen Kingdoms',
    'Later historians selected sixteen regimes to organize a much more crowded history. The name does not mean sixteen governments all existed at once, and other significant states can also be counted. Looking at individual courts reveals different choices about governing and survival. The period included more than warfare: officials and communities continued building institutions even while rulers competed.');
  add('north-south', 'Northern and Southern Dynasties',
    'From 420, successive southern dynasties ruled alongside courts in the north. Both regions developed centres of government and culture. Migration, diplomacy and war connected them, even while rulers competed for territory and the right to govern.',
    'The southern courts',
    'Courts at Jiankang relied on military commanders, powerful families and the resources of the Yangtze region. Their history includes struggles at home as well as efforts to conquer the north. Their government and culture developed under these local conditions. Measuring them only by whether they reunited China would miss much of what people built and contested in the south.',
    'Experiments in northern government',
    'Northern rulers tried different ways to register households, distribute land and organize troops. They also supported religious communities. Some of these practices influenced later dynasties, but no single plan directed them toward Sui reunification. Different courts were trying to solve the immediate problem of ruling diverse populations after earlier empires had broken apart.');
  add('oracle', null,
    'Late Shang diviners heated prepared animal bones or the lower shells of turtles, then interpreted the cracks as signs. Inscriptions could record a question, prediction and sometimes what happened. Especially at Anyang, these objects preserve the earliest large body of securely documented Chinese writing.',
    'What worried a king',
    'Harvests, childbirth, weather and warfare appear alongside offerings to ancestors. Royal decisions involved both practical action and beliefs about ancestral powers. Repeated forms in the writing show that trained people prepared and kept these records. They give us unusually close contact with questions asked at the court.',
    'Writing already had a past',
    'A dated inscription shows that writing existed by then; it cannot tell us when writing began. Other materials survive less well, and the complicated script suggests earlier development that is hard to trace. These records also preserve a royal viewpoint. They cannot tell us everything ordinary people said or cared about, and many characters remain difficult to read.');
  add('confucius', 'Confucius',
    'Confucius, traditionally dated 551–479 BCE, taught while Zhou kings lost power and noble families fought for influence. Teachings associated with him connect good government with learning, character and proper conduct. The Analects gathered these teachings across generations; it is not a word-for-word record made by the teacher himself.',
    'Learning how to behave',
    'Ritual meant more than performing a ceremony correctly. Conduct needed judgment and care for others, and repeated practice could help people develop those habits. Education therefore mattered to government. A ruler should first learn to control his own behaviour. Those serving him also had a duty to offer advice and, at times, criticism.',
    'Many later interpretations',
    'Later followers drew different lessons from these teachings, including personal improvement, family duties and the responsibility to challenge rulers. Imperial support gave some interpretations greater authority. The long history of Confucianism contains disagreements as well as shared texts. Later social hierarchies cannot all be treated as the direct wishes of one man.',
    '551 BCE is the traditional birth date. The Analects contains different layers of writing, and the exact attribution of individual sayings remains debated.');
  add('unification', 'Qin unification',
    'Qin’s conquest of Qi in 221 BCE completed its defeat of six major rival kingdoms. Ying Zheng took the title First Emperor. The conquered communities already had their own officials, customs and institutions. Qin now had to bring them under one ruler.',
    'After the armies won',
    'Qin extended its standards and appointed officials across the conquered territories. Local staff still had to register households, move supplies and interpret instructions. Defeating rival armies and governing their people were different tasks. The empire depended on directing existing networks of offices and workers toward the new emperor.',
    'Keeping the empire together',
    'The title First Emperor announced an authority intended to last. After his death in 210 BCE, struggles over succession exposed how fragile the government could be. Han later rebuilt a united empire using methods inherited from Qin. The conquest of 221 BCE established a model that later rulers would return to, even though Qin’s own ruling family could not preserve it.');
  add('paper', null,
    'Cai Lun, a court official, is traditionally credited with presenting an improved papermaking process in 105 CE. The account names bark, hemp waste, rags and fishing nets among the materials. Older paper has been excavated, so his achievement was an improvement recognized at court, rather than the first invention of paper.',
    'A more convenient writing material',
    'Paper could be lighter than bamboo or wooden writing strips and cheaper than silk. It offered new possibilities for copying texts and sending letters, and later for printing. Older materials did not disappear immediately. Writers needed a reliable supply of usable paper, which depended on skilled workers as well as a recipe.',
    'The workers behind the name',
    'Cai Lun’s court connection helped preserve his name in written history. The many craftspeople who developed paper are harder to identify. Paper spread through repeated improvements and exchanges between people. Its movement westward cannot be fully explained by one inventor or one famous battle. Different places adopted it for different uses over time.');
  add('catalog-E_XIA_1', null,
    'Later tradition describes Yu founding Xia as the beginning of dynastic rule. The familiar date of 2070 BCE comes from a reconstructed chronology. No contemporary document confirms a foundation in that year, so this event belongs to a tradition whose details remain uncertain.',
    'Earning the right to rule',
    'In the story, Yu restores a habitable world after terrible flooding. His service to people gives him the right to govern. Power then passes to his son, introducing rule by a hereditary family. Later thinkers could use this tension to ask a lasting question: should a ruler choose the most capable successor, or should the office stay in the family?',
    'Searching for traces',
    'Excavated settlements, elite buildings and evidence of ancient floods can help reconstruct the world in which these stories developed. They cannot establish that a named hero founded a dynasty in a particular year. Connecting a flood deposit, a settlement and a much later account requires evidence for each connection. Xia’s archaeological identity remains unsettled.');
  add('catalog-F_XIA_1', null,
    'Yu the Great is a legendary hero remembered for controlling a catastrophic flood and bringing order to the land. Later traditions place him before or at the founding of Xia. His position in this early period does not give us a verified birth date.',
    'A ruler working with water',
    'Stories describe Yu channelling rivers and opening passages. He earns authority through practical work for a wider community. Later rulers could draw on this example when explaining their own water projects and duties. If managing water was part of a ruler’s responsibility, failure could also become a judgment on his government.',
    'The limits of the evidence',
    'Different accounts of Yu were assembled long after the events they describe. Geological evidence can identify ancient floods, but cannot name the person who responded to them. Yu’s identity and lifetime remain uncertain. His influence on later political and religious life is much easier to trace: generations used his story to think about service, leadership and the difficult relationship between people and water.',
    'Yu is legendary; no verified dates are known. His identity and connection with particular floods are not securely established.');
  add('catalog-E_SHANG_2', null,
    'King Wu’s defeat of Shang became the founding victory of Zhou. Bronze inscriptions and later books preserve memories of the conquest, although its exact date remains disputed. Rebellion and further campaigns, associated with the Duke of Zhou, followed the first victory.',
    'Building a new ruling order',
    'Zhou rulers had to reward allies and decide how to deal with the people who had served Shang. They kept some Shang ceremonies and drew on useful specialists. Changing the ruling family did not erase everything the old court had built. The new dynasty needed relationships and places of authority that could survive beyond the battlefield.',
    'Why Heaven could change sides',
    'Later accounts explain Shang’s defeat by saying its rulers lost virtue and Heaven’s favour passed to Zhou. This made rebellion against a king acceptable when he no longer deserved to govern. The same argument could later be turned against other rulers. The conquest became both an event in political history and a story through which generations debated the duties of government.');
  add('catalog-R_ZHOU', null,
    'Zhou began with a royal network built after the conquest of Shang. Over nearly eight centuries, it changed into a world of competing kingdoms around a weakened king. Western and Eastern Zhou name two phases of the royal house, whose power and circumstances changed greatly.',
    'A respected title, less control',
    'As the king’s reach shrank, Zhou titles, ceremonies and ancestors still carried weight. Powerful regional rulers could seek recognition from a court that could no longer reliably command their armies. Respect for the royal house helped shape relationships even after much of its practical power had passed elsewhere.',
    'An example for later teachers',
    'Later thinkers described Zhou as a model of good government. They used its poems, rituals and stories to answer problems in their own time. Different teachers selected different lessons, so the Zhou past was continually interpreted. What later generations called the Zhou ideal was shaped by those arguments as well as by the institutions of the early dynasty.');
  add('catalog-SR_SA', 'Spring and Autumn Period',
    'During the Spring and Autumn period, strong regional rulers competed to lead alliances while still seeking recognition from the Zhou king. The Five Hegemons, or leading lords, traditionally include Duke Huan of Qi and Duke Wen of Jin. Lists differ over the other three.',
    'Alliances and ceremonies',
    'Marriages, visits and sworn agreements helped rulers establish rank and obligations. Ceremonies were part of political competition, even when participants broke their promises. A lord’s knowledge of the proper forms could give him influence. These leading lords headed competing states; they did not replace Zhou with a single new dynasty.',
    'An uneven change',
    'Fighting within noble families and wars between states gradually shifted power. Larger states developed more direct ways to govern their territories, alongside older family privileges. The transition to the Warring States period happened unevenly. The dates used to divide the periods help organize the history, but cannot mark one moment when every community’s government changed.',
    '770–481 BCE is the dating used here. Other accounts use 476/475 BCE and other boundaries; 481 BCE does not mark a universal change in government.');
  add('catalog-SR_WS', 'Warring States Period',
    'Larger states absorbed weaker neighbours during the Warring States period. Seven became the main rivals: Qin, Chu, Qi, Yan, Han, Zhao and Wei. Other states also survived, and the seven did not all emerge at once.',
    'Drawing households into war',
    'Rulers registered families, collected taxes and required military service. Farming and effective local government supplied armies that could conquer more land. These methods differed between states. Inherited privilege, ceremonies and local interests continued to matter, even as governments gained more direct control over ordinary people’s work and service.',
    'Competing ideas about restoring order',
    'Thinkers offered rival answers to the violence around them. Some stressed moral education, others care for all people, strong institutions or rewards and punishments. Their disagreements addressed practical problems of cooperation and rule. Later writers grouped these arguments into schools, but the texts within each group could differ. Teachers also depended on supporters who helped their ideas travel between courts.',
    '481 BCE is the start used here; 475 BCE and 403 BCE are other common boundaries. These dates mark different ways of dividing the period, not rival dates for one event. The seven main states were not the only ones.');
  add('catalog-F_SUN', null,
    'The Art of War, attributed to Sunzi, examines how information, preparation and advantage affect warfare. Its thirteen chapters consider when to fight and how to conserve resources. The text and its later influence are better documented than the life of its traditional author, Sun Wu.',
    'Winning without wasting strength',
    'A long campaign or costly siege could weaken a ruler even if his army won. Intelligence and deception offered ways to act with less risk. The text treats restraint as a practical military choice. It accepts warfare while asking commanders to avoid unnecessary losses and expense.',
    'A text people argued with',
    'Other early thinkers, including Xunzi, questioned deception on moral and practical grounds. Ancient Chinese writers did not all share one view of strategy. Modern adaptations sometimes turn sayings from the Art of War into business advice. Its advice addressed rulers and armies facing supply limits, uncertainty and the cost of war.');
  add('catalog-G_ALEX', null,
    'Alexander the Great (356–323 BCE) conquered the Achaemenid Persian Empire and led Macedonian armies into Central Asia and northwestern South Asia. He lived during China’s Warring States period, but his campaigns did not reach China.',
    'After Alexander’s death',
    'When he died in 323 BCE, his commanders fought over his empire and founded successor kingdoms. Those later societies helped develop Hellenistic culture through their cities, royal support and exchanges with regional traditions. The empire broke apart, but the movement of artistic ideas and practices continued under its successors.',
    'Two histories in the same century',
    'Alexander and Warring States rulers faced some similar problems: feeding armies, securing support from powerful people and governing conquered populations. Similarities make comparison useful, but do not prove contact or influence. Connections between the Mediterranean, Central Asia and China grew through many later intermediaries. Placing Alexander here helps locate Chinese history within a wider world without suggesting that every contemporary event was directly connected.');
  add('catalog-S_QH', 'Qin and Han government',
    'Qin created an empire in 221 BCE. After civil war, Han rulers rebuilt it and adapted many Qin methods. Looking at the two dynasties together shows how government practices could survive a change of ruling family, even when policies and circumstances changed.',
    'The daily work of empire',
    'Officials registered households, kept legal records and arranged the movement of goods. At the local level, they turned imperial commands into decisions about taxes, compulsory service and disputes. The emperor held the highest authority, but needed these offices and their staff to reach ordinary families. Surviving documents show how much imperial rule relied on routine work.',
    'An ambition later rulers inherited',
    'Later dynasties repeatedly sought to govern one empire, even after periods of division. Qin and Han offered examples of how such rule might work. Their methods were adapted to changing military needs, tax income and society. The persistence of that ambition did not mean uninterrupted unity: rival states could all claim a right to the same imperial inheritance.');
  add('catalog-R_HAN_W', null,
    'Western Han combined districts governed by appointed officials with kingdoms held by royal relatives. Emperor Wu, who reigned 141–87 BCE, expanded campaigns against the Xiongnu and sent diplomatic missions west. These commitments helped connections later called the Silk Roads grow, while increasing the costs of government.',
    'Keeping powerful allies in check',
    'Giving supporters kingdoms helped the early rulers secure their position. Those kingdoms could later threaten the court. After the rebellion of seven kingdoms in 154 BCE, the emperor further reduced their independence. Arrangements that had rewarded allies after conquest became problems for later rulers seeking firmer control.',
    'Taxes, monopolies, and the cost of expansion',
    'Emperor Wu’s armies and frontier activity required continuing supplies and money. Government monopolies and other ways of raising revenue provoked disagreement. Support for classical learning accompanied these policies without replacing law or military force. Critics could object to the burden on households while still supporting imperial government. Debate about good rule included the practical question of what people should have to pay.',
    '206 BCE–9 CE is the conventional range used here. Liu Bang became emperor in 202 BCE. Institutions and territorial reach changed substantially during Western Han.');
  add('catalog-R_HAN_E', null,
    'Liu Xiu proclaimed a restoration of Han in 25 CE and ruled from Luoyang. Civil war had changed alliances and local power, so bringing back the Han name did not restore everything that had existed before. The dynasty lasted until 220 CE, with commanders increasingly controlling its final decades.',
    'Rival groups at the imperial court',
    'Imperial relatives, empresses’ families, eunuchs and officials competed for access to the ruler. Appointments linked palace struggles to supporters and resources outside it. Powerful local families supplied knowledge and influence that the court needed, but could not always control. These relationships affected how government worked far beyond the palace.',
    'Life beyond the final wars',
    'The dynasty’s collapse can overshadow two centuries of writing, skilled production and contact between regions. Ban Zhao’s historical work and Zhang Heng’s technical inquiries belong to this longer history. The final breakdown raises a separate question: how did the court lose its ability to manage succession, armed commanders and competing interests? Earlier achievements did not vanish because that political order eventually failed.');
  add('catalog-E_QIN_2', 'Qin weights and measures',
    'In 221 BCE, the First Emperor ordered common weights and measures across the new empire. Standard weights carrying the decree survive. They show one practical part of Qin’s wider effort to bring conquered territories under a common government.',
    'Agreeing on an amount',
    'Officials and traders needed to know whether two quantities were equivalent. A government standard could reduce uncertainty in trade and tax collection. The inscription on a weight also announced imperial authority. An everyday transaction could therefore put the emperor’s rule into practice far from the court.',
    'An order still needed people to follow it',
    'A decree cannot prove that every district immediately used the same measures. Qin records show local offices handling transfers and keeping accounts within a larger system. Standards had to reach those offices and be used in daily work. The same caution applies to official writing: common written forms did not make everyone speak alike. Unification involved continuing work across a varied population.');
  add('catalog-E_HAN_1', null,
    'In 136 BCE, Emperor Wu gave official support to the study of the Five Classics, a group of ancient texts used to discuss learning and government. He founded an imperial academy in 124 BCE. These steps strengthened classical learning at court without making other teachings disappear.',
    'Learning could open a door to office',
    'Knowledge of classical texts helped people take part in government and find examples for court decisions. It could also support criticism. A learned official might argue that a ruler’s spending or treatment of the people fell short of respected ancient models. Court support gave these debates a recognized place in political life.',
    'Government kept several traditions',
    'Calling this a complete victory for Confucianism oversimplifies Han rule. Courts continued to use administrative law, punishment and other intellectual traditions. Some specialists also interpreted relationships between human affairs and the wider universe. Certain texts and teachers became more influential, but their meanings remained contested. Han government was shaped by this mixture, rather than by one exclusive doctrine.',
    '136 BCE marks official promotion of the Five Classics. The imperial academy followed in 124 BCE; neither step imposed one exclusive teaching everywhere.');
  add('catalog-E_HAN_2', null,
    'Zhang Qian set out on his first western mission in 138 BCE, seeking allies for the Han court in Central Asia. His reports gave Han rulers information about distant peoples, resources and possible diplomatic partners. Earlier exchanges and the people living along the routes had already made long-distance travel possible.',
    'Looking for allies',
    'The Han court wanted allies against the Xiongnu. Its envoys gathered information about distant peoples and resources while carrying gifts. Merchants used opportunities created by these political relationships, though wars could also obstruct movement. Trade and diplomacy developed within the same world as military rivalry.',
    'Many routes and many hands',
    'Goods could pass through several owners along changing routes. Travellers needed water, food grown at oases and arrangements with local authorities. The later name Silk Road can make this seem like one highway, although many routes and commodities were involved. The communities between large empires kept these connections working; no single traveller created them all.');
  add('catalog-E_BUD_ENTRY', 'Buddhism comes to China',
    'Travellers, merchants and religious teachers brought Buddhism into the Han world from South and Central Asia. The date around 50 CE is approximate. Evidence becomes clearer during the first and second centuries CE, especially with the translation of Buddhist teachings into Chinese.',
    'Finding words for new ideas',
    'Translators had to explain rebirth, liberation from suffering and disciplined religious life using unfamiliar languages and existing Chinese words. This involved choices and discussion. An Shigao, a translator active in the second century, gives us a firmer historical reference than a single story about Buddhism’s arrival.',
    'Communities grew gradually',
    'Buddhist practitioners at one centre do not prove that the wider population shared their beliefs. Support from rulers also varied. Religious communities needed patrons, teachers and continuing contact across borders. Later stories placed Buddhism within Chinese imperial history, while the religion spread through the slower work of translating, teaching and sustaining communities.');
  add('catalog-C_QIN', null,
    'Thousands of terracotta soldiers, horses and other figures form part of the First Emperor’s enormous burial complex. Construction began before Qin unified the rival kingdoms and continued into the end of his reign. The date 210 BCE marks his death, rather than the making of every figure.',
    'An army for the afterlife',
    'The soldiers belong to a much larger complex of burial facilities and supporting structures. Together they express an ambition to continue imperial command after death. Making them required organized production, transport and skilled labour. The finished figures let us see some of the work behind the emperor’s plans.',
    'What remains unknown',
    'Faces and equipment vary, while repeated parts reveal organized manufacture. A distinctive face does not necessarily portray a particular living soldier. The central burial chamber remains unexcavated, so later descriptions of its contents are not archaeological observations. The objects reveal much about craftsmanship and representations of military life, while leaving questions about individual figures and the burial itself unanswered.');
  add('catalog-R_WEI', null,
    'Cao Pi became emperor in 220, and Cao Wei controlled much of northern China. He inherited the military and farming arrangements built under Cao Cao. The Sima family gradually took real power before founding Jin in 266.',
    'Food for an army',
    'Agricultural colonies supplied soldiers and helped organize displaced people and land. Farming was closely tied to the demands of war. A court needed more than a large area on a map: grain and revenue had to be collected and moved reliably. These arrangements helped sustain Wei’s military strength.',
    'Power inside the government',
    'Senior offices, army commands and positions governing on an emperor’s behalf gave powerful families ways to gather influence. The Sima family’s rise came through Wei’s own government. The dynasty was eventually replaced from within, rather than simply defeated by an outside enemy. Keeping the imperial title did not ensure that the Cao rulers still controlled the offices and armies supporting it.');
  add('catalog-R_SHU', null,
    'Liu Bei’s court in Sichuan claimed to restore Han rule. Zhuge Liang helped govern Shu and led northern campaigns against Wei in 228–234. Mountain routes and limited resources restricted those ambitions. Wei conquered Shu in 263.',
    'Protected by the mountains, limited by them',
    'Sichuan had productive farmland and approaches that could be defended. The same difficult terrain made it hard to supply armies sent beyond Shu’s home territory. Claiming descent from Han could attract support, but could not remove the cost of mobilizing a smaller population. Geography offered protection while limiting prolonged expansion.',
    'Zhuge Liang in history and stories',
    'Later plays and fiction made Zhuge Liang famous for extraordinary foresight and ingenious plans. His historical work also involved recruiting people, organizing government and keeping the state able to fight. The northern expeditions were sustained military efforts under difficult conditions. His later reputation grew from that service, but fictional feats cannot be read as direct accounts of the campaigns.');
  add('catalog-R_WU', null,
    'The Sun family built Wu around the lower Yangtze River. Sun Quan became king in 222 and claimed the imperial title in 229. Wu outlasted both Shu and Wei, until Jin conquered it in 280.',
    'Ruling with local families',
    'Military leaders needed the support of powerful families whose estates and followers provided resources. Marriages and official appointments helped connect them to the court. These ties did not erase their independent influence. Wu’s rulers governed through agreements with people who already held power in the region, and those relationships could produce conflict as well as cooperation.',
    'The cost of expansion',
    'As Wu extended control into hill regions, it drew communities into taxation and military service. Official accounts might describe this as bringing order or developing productive land. For the people affected, it could mean being forced under a new authority. Growth in the southern economy therefore came with burdens on communities whose experience is harder to see in court records.');
  add('catalog-E_3K_1', null,
    'In 220, Cao Pi accepted the Han emperor’s abdication and founded Wei. Han’s control had already weakened over many years. Cao Cao had built a powerful military government while keeping the emperor and issuing decisions in his name.',
    'The emperor’s name still mattered',
    'Controlling the emperor allowed Cao Cao to authorize appointments and campaigns without immediately replacing Han. The abdication later gave Cao Pi a claim to a lawful transfer of rule. The ceremony presented the new dynasty as legitimate to officials and rivals. Possessing military power and being accepted as the rightful ruler were connected, but different, problems.',
    'Several successors to Han',
    'Shu and Wu developed their own courts and claims after the transfer. Han’s methods of government and imperial language remained useful to several rival states. The dynasty’s formal end did not make its inheritance disappear. The date 220 marks the end of the Han ruling house within a division of power that had already advanced much further on the ground.');
  add('catalog-E_3K_2', null,
    'At Red Cliffs in winter 208–209 CE, forces associated with Sun Quan and Liu Bei stopped Cao Cao’s advance along the Yangtze. Cao Cao controlled the Han emperor and dominated the north. His defeat allowed southern rivals to survive while Han still formally existed.',
    'Fighting on the river',
    'Naval experience mattered, along with disease, supplies and the difficulty of campaigning far from familiar ground. The defeat stopped Cao Cao from immediately extending northern dominance southward. It did not create the Three Kingdoms in one day. Wei, Shu and Wu emerged through later campaigns and competing claims to rule.',
    'The battle in later stories',
    'Fiction turned Red Cliffs into a setting for brilliant plans and memorable personalities. Surviving historical accounts support a more limited picture, and several famous tricks remain disputed. Those later stories shaped how people remembered the battle, especially its lessons about loyalty and intelligence. They need to be distinguished from evidence of what the armies actually did.');
  add('catalog-R_JIN_W', null,
    'The Sima family founded Western Jin after gradually taking power within Wei. Jin conquered Wu in 280 and briefly ended the Three Kingdoms division. Later conflicts among imperial princes and military leaders weakened the court, which lost Luoyang and then Chang’an.',
    'A takeover built through service',
    'The Sima family gained offices and military commands before changing the imperial title. Its rise had therefore begun long before Jin’s formal founding. The new rulers inherited Wei’s officials and resources, along with relationships that were difficult to manage. A new dynastic name did not settle every contest for power.',
    'Reaching ordinary households',
    'Changes in farming settlements and the landholdings of powerful families affected what the court could demand. To collect labour and military service, officials needed household records and cooperation from local intermediaries. The struggles between princes were part of this wider problem. A government also needed reliable access to the people and resources that supported its armies.');
  add('catalog-E_JIN_1', null,
    'Chang’an fell in 316, ending the remaining Western Jin court. Luoyang had already fallen in 311. These successive defeats displaced political leaders and helped shift power between northern and southern centres.',
    'A collapse in stages',
    'The court lost effective control over territory and resources before its final defeat. Cities, armies and communities experienced the breakdown at different times. The date 316 makes a clear endpoint for Western Jin, but the fighting and displacement formed a longer sequence. Ancient accounts of devastation also cannot be treated as reliable modern population counts.',
    'Jin continued in the south',
    'Sima Rui’s southern government kept the Jin name. It needed support from families who had fled the north and influential families already established in the south. Ancestry helped its claim, but cooperation made rule possible. The fall of the western court was therefore also part of the formation of a different Jin society and government around the Yangtze.');
  add('catalog-E_BUD_SPREAD', null,
    'Buddhist texts and communities existed in China before the fourth century. During the Age of Division, more translations, images and support from patrons helped Buddhism grow in different regions. About 350 is a reference point for this gradual, uneven expansion.',
    'The work behind a growing religion',
    'Translators and readers kept texts in use. Patrons and craftspeople paid for and made images. Monasteries needed resources and protection. Buddhism took root through these relationships within local society, with different results in different regions. Its growth involved continuing work by communities, rather than the simple arrival of a complete set of foreign beliefs.',
    'Negotiating with rulers',
    'Monks’ religious duties and claims to a distinct status raised practical questions for governments. Who should pay taxes, perform service or show allegiance to a ruler? Court support did not settle every tension. Buddhism’s expansion included negotiations and conflicts as well as devotion, intellectual exchange and the creation of art.');
  add('catalog-R_JIN_EASTERN_JIN', null,
    'Sima Rui re-established a Jin court south of the Yangtze. Families who had moved from the north and powerful southern families shaped its government. Jiankang became a centre of politics and culture, while efforts to recover the north continued unevenly.',
    'An emperor who needed allies',
    'Prestigious families held offices and military resources that the emperor needed. Their cooperation allowed the court to function, but also limited his direct control. These families had competing interests. Describing Eastern Jin as government by an aristocracy is useful only if we remember that the aristocracy itself did not always agree.',
    'Migration and cultural life',
    'People carried texts, skills and ideas south with them. Their arrival helped create new settings for literature and art. These achievements grew within a society changed by displacement and new alliances. They belong to the same history as the court’s struggle to secure support, rather than forming a separate story untouched by war and migration.');
  add('catalog-R_SIXTEEN_HAN_ZHAO_FORMER_ZHAO', null,
    'Liu Yuan founded a state using the Han name in 304, as Western Jin power broke down. Later rulers adopted the name Zhao. Historians commonly group these changing phases as Han Zhao or Former Zhao.',
    'Claiming an imperial inheritance',
    'The Han name and claims about ancestry connected the new court to an established tradition of empire. They offered a way to seek support beyond the founder’s original followers. The court could use inherited titles and institutions rather than rejecting everything associated with earlier rulers. Its past was part of its argument for governing in the present.',
    'One name covers several changes',
    'Rulers, capitals and territory changed during the state’s history. The combined name makes those phases easier to follow, but can also hide their differences. Later Zhao was a separate regime, despite the shared word Zhao. Military alliances shifted, and rival courts repeatedly sought the same imperial authority.');
  add('catalog-R_SIXTEEN_LATER_ZHAO', null,
    'Shi Le and his successors made Later Zhao a major power in the north. The Buddhist monk Fotudeng developed close relationships with its rulers. Court support helped Buddhist institutions gain influence during the state’s short political life.',
    'A monk at court',
    'Religious biographies credit Fotudeng with ritual powers and influence over rulers. Miracles in these stories cannot be independently confirmed. The accounts do show what people expected religious figures to offer, including protection for rulers and their government. Personal access to the court helped religious communities secure support, alongside the spread of texts and teachings.',
    'What survived the state',
    'Monks, disciples and stories could travel beyond Later Zhao’s borders. The court fell, but the Buddhist communities and institutions it supported survived. Political defeat did not necessarily end the traditions that had benefited from royal support.');
  add('catalog-R_SIXTEEN_FORMER_YAN', null,
    'Former Yan grew from a northeastern base under the Murong family into a major northern state. Its rulers expanded by force while using titles and recognition from other courts to strengthen their position.',
    'Claiming authority in stages',
    'A ruler might first accept recognition as a prince before claiming to be emperor. Recognition from another court could help secure support while greater ambitions remained difficult to achieve. Former Yan’s development combined diplomacy with military expansion. Its different titles record stages in the growth of power, rather than a state that appeared fully formed on one founding date.',
    'Looking from the northeast',
    'The northeast can appear distant when viewed from another dynasty’s capital. For the Murong rulers, it was the centre from which they gathered resources and built alliances. Starting from their own base makes their choices easier to understand. They were organizing a state with its own supporters and ambitions within a wider contest for imperial rule.');
  add('catalog-R_SIXTEEN_FORMER_QIN', null,
    'Under Fu Jian, Former Qin brought much of northern China under one ruler. Eastern Jin defeated its army at the Fei River in 383. Former Qin survived the battle, but the alliance supporting its expanded territory quickly began to break apart.',
    'Conquest did not settle every loyalty',
    'Military victories brought different commanders and communities under Fu Jian without giving them identical interests. Their support could depend on rewards or the ruler’s ability to compel obedience. A serious defeat exposed those unsettled relationships. Former Qin’s greatest territorial extent therefore does not tell us how securely every region was governed.',
    'Why one defeat had wider effects',
    'Stories of the Fei River often stress clever tactics and enormous armies. The reported troop numbers remain uncertain. After the defeat, commanders and communities withdrew their support, and Former Qin fragmented even though it survived until 394.');
  add('catalog-R_SIXTEEN_LATER_QIN', null,
    'The Yao family ruled Later Qin from Chang’an. After Kumarajiva arrived in 401, Yao Xing supported the monk and his collaborators in translating Buddhist texts. Later Qin ended in 417, while the translations continued to shape readers long afterward.',
    'A team of translators',
    'Turning Buddhist works into Chinese required discussion and interpretation. Collaborators had to choose how to express ideas clearly, rather than merely replace words from one language with another. Court resources and protection made this work possible. A politically insecure ruler could still provide conditions for a major intellectual undertaking.',
    'Readers beyond the court',
    'Later communities used these translations in circumstances far removed from the court that had supported them. Texts could move beyond a state’s borders and remain influential after its fall. Their history therefore extends beyond Later Qin’s dates. Not every work traditionally attributed to Kumarajiva can be confidently assigned to him, and traditional totals also need caution.');
  add('catalog-R_NS_LIU_SONG', null,
    'Liu Yu founded Liu Song in 420 after a successful military career. Its court ruled from Jiankang. Emperor Wen, who reigned 424–453, sought to restore government after the founding wars. Later struggles over succession repeatedly disrupted the dynasty.',
    'A commander becomes ruler',
    'A general serving an existing dynasty could gather enough troops and resources to replace its ruling family. An abdication ceremony then presented the change as a lawful succession. Liu Song’s founding belongs to this recurring pattern: new dynasties could grow from powerful positions inside an older government.',
    'Paying for defence',
    'In 450, Northern Wei troops reached Guabu near the Yangzi. The war strained the court’s finances. Wen cut officials’ salaries by one-third and imposed levies on wealthy households and Buddhist clergy. Defence therefore placed demands on people far from the fighting. Keeping the court secure also required managing princes, commanders and powerful families whose cooperation could change whenever a new ruler took power.');
  add('catalog-R_NS_SOUTHERN_QI', null,
    'Xiao Daocheng founded Southern Qi in 479. Its court tried to keep track of households and supervise royal princes governing the regions. Both tasks affected how much money, labour and military support the government could collect.',
    'Why household lists mattered',
    'A household missing from official records might pay less tax or provide less labour to the court. A local powerful family could gain more control over those people instead. Keeping registers was therefore a struggle over who could make demands on households. The court’s claim to rule a region was stronger on paper than in practice if it could not reach its people.',
    'Watching the princes',
    'Officials handling household documents helped supervise princes’ establishments. The court needed ways to monitor relatives entrusted with regional power. These arrangements might restrain a prince while giving more influence to the officials watching him. Southern Qi faced a familiar problem: delegating authority made government possible, but also created people with power of their own.');
  add('catalog-R_NS_LIANG', null,
    'Xiao Yan founded Liang in 502 and supported Buddhist communities and learning at court. Accepting the defecting commander Hou Jing brought a dangerous military leader into southern politics. Hou Jing captured Jiankang in 549 and shattered the court’s authority.',
    'Religion and royal support',
    'Supporting religious and literary institutions helped the emperor present himself as a moral and cultural leader. It also connected the court to communities and resources beyond its own offices. Liang’s Buddhist life involved these political relationships as well as the ruler’s personal beliefs.',
    'The danger of accepting an ally',
    'A commander arriving from the north could offer military advantages. He also brought troops and ambitions the court could not fully restrain. Hou Jing’s rise exposed the risks of relying on commanders whose loyalties could change. Blaming the disaster simply on religion or court luxury leaves out that struggle over military power. The principal dynasty ended in 557, though a smaller Liang court survived longer.');
  add('catalog-R_NS_CHEN', null,
    'Chen Baxian founded Chen in 557 after years of devastation and divided military power. The last of the southern dynasties, it ruled a reduced territory before Sui conquered it in 589.',
    'Rebuilding after war',
    'The court needed to restore tax collection, appoint officials and bring regional commanders into workable relationships. Its territory was smaller than that of earlier southern rulers, but rebuilding government still required effort. Later accounts often focus on the final defeat and can obscure this work of recovery after destructive wars.',
    'What reunification required',
    'Sui’s victory ended the independent southern court. It did not immediately remove the differences in society and government that had developed during centuries of separation. The conquerors inherited those regional conditions and had to find ways to govern across them. Chen’s end therefore marks a military change within a longer process of bringing northern and southern systems together. Sui itself had already been founded in 581.');
  add('catalog-R_NS_NORTHERN_WEI', null,
    'The Tuoba-led Northern Wei completed its conquest of northern China in 439. Reforms to landholding and household records increased the government’s demands on resources. Moving the court to Luoyang in 494 brought major changes in political and cultural life.',
    'Land in return for obligations',
    'The equal-field system, introduced in 485, allocated land according to household categories and linked farming to taxes and labour service. Household records helped officials identify who owed what. These rules show what the government wanted to achieve, but do not prove that land was redistributed uniformly or that every district followed the same practice.',
    'A changing court',
    'Rulers adopted Chinese court practices and supported large Buddhist monuments to strengthen their authority. These changes did not erase Xianbei identities or remove political tensions. Governing a diverse population involved choices about whose practices and interests the court would favour. Reforms could bring some groups closer to the government while creating new sources of conflict.');
  add('catalog-R_NS_EASTERN_WEI', null,
    'Eastern Wei kept the Wei imperial title after the northern court split, while the Gao military family held effective power. Its eastern territories contained substantial farmland, cities and experienced armies.',
    'The emperor and the commanders',
    'Keeping the dynastic name gave the Gao family an established authority through which to govern. The emperor’s title and actual control belonged in different hands. To understand the state, we need to follow the family and commanders who supplied its troops and ran its government, as well as the person on the throne.',
    'Resources needed organization',
    'Eastern and Western Wei inherited different territories and alliances. The eastern state’s wealth did not guarantee victory over its rival. Rulers still had to organize supplies and hold commanders together. Eastern Wei was a substantial state with resources of its own, rather than simply a powerless fragment. In 550, Northern Qi replaced the imperial title while Gao-family power continued.');
  add('catalog-R_NS_WESTERN_WEI', null,
    'After the northern split, Western Wei developed under the military leadership of Yuwen Tai. It had fewer resources than its eastern rival. Its rulers tried new arrangements for government and the army that influenced Northern Zhou and later Sui.',
    'Working with fewer resources',
    'The western government had reasons to change recruitment and command because it could not rely on greater wealth or manpower. These changes answered immediate pressures. They were not a complete plan for later dynasties: successors adapted the arrangements to different populations and military needs.',
    'An old title, new power',
    'The Wei name connected the court with the preceding dynasty, while Yuwen leaders organized its effective power. The emperor’s family and the military alliance therefore tell different parts of the story. The court could preserve an inherited title while another family gathered the authority eventually used to replace it. Later military systems should not be assumed to have existed here in their finished form.');
  add('catalog-R_NS_NORTHERN_QI', null,
    'The Gao family replaced Eastern Wei with Northern Qi in 550. It ruled a wealthy eastern region until Northern Zhou conquered it in 577. Relations within the ruling family mattered to its survival alongside wars with its neighbours.',
    'Family ties at the centre of power',
    'Empress Dowager Lou’s role shows how marriage and kinship helped organize authority within the ruling household. Women participated in decisions that affected succession and the state’s future. Treating palace life only as a background to male rulers misses those relationships. The question of who would inherit power involved the wider family and its connections.',
    'Wealth was not enough',
    'Farmland and other resources could support a strong government only if rulers maintained effective command and reliable alliances. Rival centres of influence could still divide a wealthy court. Northern Qi’s defeat cannot be explained by comparing resources alone. Dramatic tales about individual emperors also leave out the practical question of who controlled the state’s wealth and armies.');
  add('catalog-R_NS_NORTHERN_ZHOU', null,
    'The Yuwen family founded Northern Zhou after Western Wei in 557. It conquered Northern Qi in 577. Sui inherited this enlarged northern state when it took power in 581.',
    'Strength built before the founding',
    'Northern Zhou’s armies grew from the western alliance that had supported Western Wei. Recruitment and command depended on those earlier political relationships. Later rulers continued to adjust the arrangements they inherited. Following these connections explains how military power could grow across a change of dynastic name, rather than appearing suddenly when a new emperor took the throne.',
    'Victory did not secure the family',
    'Defeating Northern Qi expanded the state without guaranteeing that the Yuwen family would keep ruling it. Another group could use the enlarged government and its resources to take power. Sui’s succession illustrates that difference: strong armies and offices could survive while the family at the top changed. The northern conquest came before the later conquest of the south in 589.');
  add('laozi', 'Laozi and the Daodejing',
    'Laozi, the “Old Master,” is associated with the Daodejing, a short book central to later Daoist traditions. His identity and lifetime are uncertain. The approximate Warring States dates here concern the book’s formation, rather than a securely documented person’s lifespan.',
    'The value of restraint',
    'The text questions forceful ambition, excessive desire and rulers’ confidence that they can impose order. Its idea of wuwei, often translated as non-action, does not simply mean doing nothing. It asks how action might avoid needless interference and ambitions that defeat themselves. Readers disagree about exactly how this advice should guide either a person’s life or a government.',
    'A book in different forms',
    'Guodian manuscripts preserve related passages by around 300 BCE. Copies found at Mawangdui arrange material differently from the familiar later text. The book developed through copying and compilation. The story of a sage writing it all at a frontier pass belongs to later tradition and cannot replace this evidence of different early versions.');
  add('mozi', 'Mozi',
    'Mozi and his followers challenged aggressive war, luxury and inherited privilege during the Warring States era. He probably taught in the later fifth century BCE, though his exact dates are unknown. The surviving book Mozi includes arguments developed by followers as well as teachings associated with the master.',
    'Care beyond the family',
    'Mohists argued that concern for people should extend beyond family and political borders. Judged by the suffering it caused, aggressive war was hard to defend, whatever glory a ruler claimed. They also criticized lavish funerals and musical displays. Labour and resources, they argued, should benefit people broadly rather than mainly enhance the standing of the powerful.',
    'Order and capable officials',
    'This wider care went together with support for hierarchy, common moral standards and the promotion of capable officials. Mohists appealed to Heaven and spirits while also arguing carefully about practical consequences. Their ideas do not fit neatly into a modern political party. They pressed opponents to explain whose welfare deserved attention and which uses of resources could be justified.',
    'Around 430 BCE marks Mozi’s approximate period of activity, not his birth or death. His precise dates are unknown.');
  add('mencius', 'Mencius',
    'In the fourth century BCE, Mencius developed teachings about moral growth and humane government. Dialogues with rulers in the book bearing his name connect a ruler’s authority with his treatment of people. Followers and later editors transmitted the text, and his conventional life dates remain approximate.',
    'People needed secure livelihoods',
    'Mencius’s claim that human nature is good concerns capacities that need to be developed. It does not mean everyone always behaves well. He connected conduct with living conditions: a ruler who leaves people insecure and then punishes their misconduct cannot blame character alone. Providing for people and helping them learn were parts of the same responsibility.',
    'A throne did not settle the question',
    'The text permits harsh criticism of rulers who abandon their duties. It assumes monarchy and different social roles, rather than modern government by the people. Even so, holding the throne did not automatically make a ruler worthy of it. Later readers could use this argument to advise a ruler or condemn his failures.');
  add('zhuangzi', 'Zhuangzi',
    'The Zhuangzi uses stories, humour and unexpected viewpoints to question familiar judgments. Zhuang Zhou probably lived in the later fourth century BCE, but other writers contributed to the surviving book. The approximate dates here describe its early development, rather than one established lifespan.',
    'Usefulness depends on who is judging',
    'Its stories ask who decides what has value. A tree that a carpenter finds useless may survive because no one wants to cut it down for timber. What looks like a disadvantage from one position can look different from another. Tales of skill and transformation similarly invite readers to reconsider the purposes behind their judgments.',
    'Living under demanding rulers',
    'Doubts about ambition and public office had force in a world where rulers could demand service and punish failure. The text also explores action that is skilled and responsive, less restricted by fixed categories. Later readers have interpreted it in very different ways. A slogan such as “everything is relative” misses the variety and movement of its arguments.');
  add('xunzi', 'Xunzi',
    'Xunzi defended learning, ritual and deliberate self-improvement in the third century BCE. He disagreed with Mencius about the relationship between human nature and moral conduct. His dates are uncertain; he was still alive after his patron Lord Chunshen was killed in 238 BCE.',
    'Learning to handle desire',
    'Unchecked desires could bring people into conflict over limited resources. Teachers and inherited practices helped people respond differently. Ritual organized expectations, emotions and distinctions between roles so that cooperation became possible. For Xunzi, good conduct was an achievement developed through practice, rather than simply the release of goodness already present within us.',
    'Human responsibility for government',
    'Xunzi distinguished Heaven’s regular patterns from the success or failure of human rule. People had to take responsibility for the institutions they created. He valued disciplined effort, hierarchy and accomplished earlier teachers. Some later Confucian traditions gave him less prominence, but his disagreements show how widely early thinkers could differ while working with Confucius’s inheritance.',
    'About 310 BCE is an estimated birth date. 238 BCE marks his latest securely documented activity, not a known death year. His description of human nature depends on a distinction between natural desires and learned moral conduct.');
  add('han-fei', 'Han Fei',
    'Han Fei, who died in 233 BCE, examined how rulers could control ministers and subjects. The Han Feizi discusses standards, rewards, punishments and methods of government. Later writers called him a Legalist, though this label groups thinkers who did not form one organized school.',
    'Officials had interests of their own',
    'A minister might hide information, exaggerate success or turn delegated duties into personal power. Han Fei wanted ways to compare an official’s performance with his stated responsibilities. Government should work through repeatable arrangements instead of depending on unusually wise rulers and perfectly loyal servants.',
    'Rules in the ruler’s hands',
    'Common standards could weaken inherited exemptions, but their purpose was stronger royal control, rather than equal political rights. The ruler kept command of rewards and punishments. This created a difficult dependence: he needed capable officials while fearing the independence their ability might give them. Han Fei’s writing explores tensions inside powerful government, not a modern system of constitutional limits.',
    'About 280 BCE is a conventional approximate birth date; 233 BCE is his death year. The surviving collection has disputed layers. Legalism is a later classification, not modern rule of law.');
  add('mawangdui-manuscripts', 'Mawangdui Manuscripts',
    'A tomb near Changsha, sealed in 168 BCE, preserved silk manuscripts with other burial materials. Excavations in 1972–1974 revealed the collection at Mawangdui. The copies must be older than the tomb’s closure, but the works they contain may have been composed much earlier.',
    'What one collection held',
    'Philosophical writings appear alongside medical and technical materials and maps. The collection shows interests in government, health, the wider universe and bodily practices within one wealthy setting. It broadens our view beyond a few famous thinkers and books. It does not show a standard course of study followed by everyone in Han China.',
    'Different versions of a familiar book',
    'The Laozi manuscripts differ in wording and order from the later text. A book now encountered in a familiar form once circulated in alternatives. These copies help us see how texts changed as people transmitted them. A later edition’s authority does not mean that all earlier readers knew exactly the same words or arrangement.');
  add('sima-qian', 'Sima Qian and the Shiji',
    'Sima Qian’s Shiji, or Records of the Grand Historian, brings together chronological accounts, tables, studies of government and society, and biographies. Written in the later second and early first centuries BCE, its 130 chapters include merchants, advisers and defeated rivals alongside emperors.',
    'Competing views of the past',
    'An emperor’s account can show a different world from a study of the economy or the life of someone he defeated. Readers have to connect these parts. The structure allows questions about behaviour, social position and how people gathered wealth and power, alongside the sequence of major events.',
    'History as criticism',
    'The economic chapters can be read as criticism of imperial expansion under Emperor Wu. That is an interpretation, rather than proof that every passage carries one hidden message. An official historian’s access to the court did not necessarily make him a simple spokesman for it. Writing about earlier events could also expose difficulties in the government of his own time.',
    'About 109–91 BCE is the usual composition range, not an exact publication schedule. Different portions and later transmission have their own histories.');
  add('salt-iron-debate', 'Salt and Iron Debate',
    'In 81 BCE, a court conference debated Emperor Wu’s policies, including government monopolies on salt and iron. Huan Kuan later compiled the Discourses on Salt and Iron as an account of the exchanges. The debate asked what government should do and who should bear its costs.',
    'The price of frontier policy',
    'Supporters of government involvement in the economy argued that revenue paid for frontier commitments and public power. Critics pointed to hardship and the damaging effects of pursuing profit. Decisions about distant armies could affect the goods people produced and bought at home. Military policy and household burdens belonged to the same argument.',
    'A debate preserved by a later writer',
    'The speakers argued within a monarchy and a largely farming society. Modern labels such as capitalism and socialism do not neatly describe their positions. The surviving book also arranges arguments for later readers. It is evidence of political disagreement, but cannot recover every participant’s exact words or the full range of official opinion.');
  add('ban-zhao', 'Ban Zhao',
    'Ban Zhao helped finish the Book of Han after her brother Ban Gu died in 92 CE, and taught at the imperial court. Her Admonitions for Women became widely read. Her career shows a woman exercising authority through learning within a society that restricted women’s roles.',
    'Ban Zhao’s case for educating girls',
    'Ban Zhao questioned giving education to boys while neglecting girls. She based her argument on women’s duties in marriage and ritual life, rather than calling for that social order to be abolished. Her writing could support learning for women while also expecting their subordination. Both parts matter to understanding what she argued.',
    'Advice and everyday life',
    'Rules about how women ought to behave cannot show that every household followed them. The text reflects expectations in a particular wealthy setting; its later readers gave it a wider influence. Ban Zhao’s own achievement also warns against treating ancient women as one identical group. Access to education and court relationships could differ greatly.');
  add('zhang-heng', 'Zhang Heng’s earthquake detector',
    'In 132 CE, Zhang Heng presented an instrument intended to indicate the direction of a distant earthquake. He also worked in astronomy, mathematics and literature. Observing natural events mattered at court because they could carry practical and political meaning.',
    'News of distant disaster',
    'An earthquake might damage a region far from the capital. It could also be interpreted as a warning about government. A device registering an event that people nearby had not felt offered a way to learn about the wider empire. Technical observation and beliefs about nature therefore worked together in this setting.',
    'What the device could do',
    'No original instrument survives. Modern reconstructions rely on descriptions that leave its mechanism uncertain. It was reportedly a detector of an earthquake and its direction, rather than an instrument drawing a continuous record or calculating magnitude. It did not predict earthquakes. These limits matter when judging the achievement: a modern reconstruction cannot establish every detail of how the Han device worked.');
  add('nine-chapters', 'Nine Chapters on the Mathematical Art',
    'The Nine Chapters on the Mathematical Art collects problems about land areas, quantities, distribution, engineering and calculation. It developed over generations. Later explanations, especially Liu Hui’s commentary in 263 CE, became part of how readers learned from it.',
    'Methods for new problems',
    'Surveying a field or dividing resources required more than one numerical answer. A procedure could be used again with different quantities, helping learners solve new problems. The book connects general mathematical reasoning to situations familiar to officials and producers. Its practical settings do not make its methods merely mechanical.',
    'Learning through explanation',
    'The problems, operations and later commentaries worked together. Comparing their organization only with Greek geometry can overlook the reasoning expressed in a different form. Understanding the book requires attention to how its procedures were explained and taught. Its changing layers also make a single publication date misleading: the collection and the explanations added to it belong to different times.',
    'About 100 BCE–100 CE is a broad Han-period reference, not an established formation range. Proposed origins include around 200 BCE and alternative dating between 100 BCE and 50 CE. Different layers have different dates; Liu Hui’s commentary dates to 263 CE.');
  add('orchid-pavilion', 'Wang Xizhi’s Orchid Pavilion gathering',
    'In 353, Wang Xizhi joined a spring purification gathering associated with the Orchid Pavilion. Participants drank, composed poems and exchanged writing. His preface became a celebrated model of calligraphy. The original no longer survives; later copies carry its reputation.',
    'A gathering remembered through writing',
    'The poems grew from a shared occasion, and the preface gave that meeting a lasting written form. Later paintings presented such gatherings as admired examples of educated friendship and taste. One event became a model through which later readers and artists imagined their own relationship with a cultural tradition.',
    'What copies preserve',
    'Tracing, copying and carving allowed Wang’s work to reach later viewers in different materials. Those viewers encountered both the appearance of brushwork and inherited judgments about its quality. A surviving copy is part of that chain of transmission, rather than direct access to Wang’s own hand. The story that the original was buried with Tang Taizong remains unverified by archaeology.');
  add('mogao-caves', 'Mogao Caves',
    'Tradition dates the Mogao caves near Dunhuang to 366, when a monk’s vision inspired a sanctuary. The complex grew over many dynasties. Donors, artists, monks and travellers created its paintings, sculptures and manuscripts through connections reaching beyond any one court.',
    'Making a sanctuary at a crossroads',
    'Dunhuang lay on routes linking China and Central Asia. Local communities sustained institutions that could receive texts and images, then adapt them. Donors commissioned caves to express devotion. The art changed through choices made by patrons and workshops over generations, drawing on several traditions rather than copying a single foreign model.',
    'The manuscript chamber',
    'A chamber discovered in 1900 preserved documents in several languages. They connect religious life with government work and everyday activities. Their survival gives an unusual view of the region, but the collection is not a sample of every community along the routes. The circumstances in which these materials were gathered, preserved and later dispersed also shape what they can tell us.');
  add('kumarajiva-translations', 'Kumarajiva’s Buddhist translations',
    'Kumarajiva, a learned monk from Kucha, reached Chang’an around 401 after journeys shaped by rival rulers and military coercion. With Later Qin support, he led teams translating Buddhist texts into Chinese. Their work helped readers study and debate difficult teachings.',
    'Many people behind one name',
    'Translation involved spoken explanations, discussion, recording and revision. Monks and assistants connected knowledge of the original teachings with skill in written Chinese. The court provided resources and a place to work. Kumarajiva’s name became famous, but the translations depended on collaborators as well. Rival states could support important centres of religious learning even during political division.',
    'A long life among readers',
    'Communities adopted the translations for study, debate and ritual. Their continuing use gave them authority beyond the court where they were produced. Later catalogues also attributed works to Kumarajiva with varying reliability. A text’s influence does not establish its authorship, and not every work carrying his name can be assigned to him with equal confidence.');
  add('tao-yuanming', 'Tao Yuanming',
    'Tao Yuanming, also called Tao Qian, wrote about rural life, poverty and leaving official service. His return home in 405 became an influential subject. Later readers admired the apparent simplicity of his poetry and made him a model of personal integrity.',
    'The choice to leave office',
    'Retirement could be presented as freedom from the compromises of government work. Tao’s writing placed the household and cultivated land at the centre of that choice. His poems are shaped by an author’s concerns, rather than describing all rural society. Later admirers could make difficult individual circumstances look like a reassuring ideal of simple living.',
    'The poet later readers knew',
    'Copying and editorial choices changed the body of writing readers encountered. Paintings of Tao’s homecoming added more interpretations. Artists living through dynastic conquest could find their own dilemmas in his withdrawal. His reputation therefore grew through later reading and art as well as his fifth-century poems. The reasons for his retirement should not be taken directly from later anecdotes.');
  add('yungang-caves', 'Yungang Caves',
    'The main early Yungang cave project near the Northern Wei capital developed around 460–525. Huge Buddha images, including five caves associated with the monk Tanyao, joined Buddhist devotion with imperial support. Their scale shows the resources rulers could direct into religious building.',
    'Belief and royal power',
    'Carving the caves required workers, materials and continuing organization. Royal support expressed devotion while presenting the court as able to carry out extraordinary projects. These purposes could reinforce each other. Belief need not have been a disguise for politics: supporting Buddhism could bring religious merit and also strengthen a ruler’s public standing.',
    'Choices made by workshops',
    'Carvers and patrons combined artistic forms associated with South and Central Asia with local preferences. Their choices changed over time. These were adaptations by people working within connected worlds, rather than an inevitable march from foreign art toward a final Chinese form. Changes at Yungang also belong to the history of Northern Wei’s shifting political centre.');
  add('longmen-caves', 'Longmen Caves',
    'Near Luoyang, Longmen’s most intensive carving ran from the late fifth to the middle of the eighth century. Northern Wei and Tang patrons commissioned Buddhist images and inscriptions. Different generations added to the site, rather than completing one ruler’s single plan.',
    'Cave workers, donors, and inscriptions',
    'At Binyang, donor processions showed rulers approaching the Buddha. Other inscriptions record commissions and hopes attached to them. The caves therefore tell us about the people supporting religious art as well as the makers’ skill. Images connected living donors, the dead and political authority within places of worship.',
    'Inscriptions and patronage',
    'Medical prescriptions carved at Yaofangdong reveal practical concerns alongside devotion. Later changes and damage have also shaped the site. Some donor reliefs now displayed abroad once belonged to larger arrangements of figures and architecture. Understanding where they stood helps recover relationships that an isolated museum object cannot fully show. Each cave has its own sequence of work within Longmen’s long history.');
  add('zhou-gonghe', 'King Li’s expulsion and the Gonghe period',
    'Traditional histories place the expulsion of King Li of Zhou around 841 BCE, followed by a period known as Gonghe. The people involved are often called inhabitants of the capital. The ancient term guoren does not simply mean modern citizens or the whole farming population.',
    'Removing a king',
    'The king’s removal exposed conflict within the royal community, but did not abolish the monarchy. Later accounts made it a warning about oppressive rule, especially a ruler’s response to criticism. These stories reveal later ideas about government. They are not independently verified records of everything said during the confrontation.',
    'A useful date, disputed details',
    '841 BCE became the conventional starting point for a continuous year-by-year chronology in traditional Chinese histories. Details remain uncertain, including who governed during Gonghe. Some accounts describe a regency; others identify a particular lord as ruler. The name should not be read in its much later sense of a modern republic.',
    '841–828 BCE is the conventional range. Some reconstructions place the expulsion in 842. Accounts disagree over whether Gonghe was a regency or rule by a named lord.');
  add('zhou-capital-crisis', 'Fall of the Western Zhou capital',
    'In the traditional chronology, an attack involving the lord of Shen and Quanrong forces killed King You in 771 BCE. King Ping established his court in the east in 770, the conventional beginning of Eastern Zhou. Rival claims to the throne and military alliances both shaped the crisis.',
    'Allies could turn against the king',
    'Regional lords and groups described as outsiders belonged to connected political networks. They could take sides in a royal succession struggle. Zhou power depended on alliances that might be redirected against its ruler. Losing the western centre weakened the resources supporting the monarchy, even though the royal title remained respected.',
    'The story of the warning fires',
    'Later tradition blamed the king’s favourite Bao Si and the misuse of warning beacons. This memorable tale turns a political breakdown into a lesson about a king misled by a woman. Its details are less secure than the conventional dates. Reconstructing the crisis also requires attention to rival rulers and military commitments, rather than relying on the anecdote alone.');
  add('shang-yang', 'Shang Yang’s reforms',
    'Reforms traditionally dated to 356 and 350 BCE link Shang Yang with Qin’s growing strength. They rewarded farming and military achievement, tightened supervision of households and extended direct control by officials. More of ordinary people’s work could then be directed toward the ruler’s needs.',
    'Rewards and punishments',
    'Rewards offered opportunities beyond inherited privilege. Punishments and collective responsibility, which held groups answerable for members’ conduct, tightened control. Both aimed to direct effort toward farming and war. Powerful households lost some independence. The possibility of advancement in selected activities therefore came alongside stronger restrictions on people’s lives.',
    'Changes that outlasted the reformer',
    'Shang Yang was executed in 338 BCE, but important changes survived him. Qin’s later conquests also depended on generations of rulers, officials and soldiers. The Book of Lord Shang contains layers of writing associated with his tradition, rather than a verbatim list of his policies. A proposal in the book does not prove it was applied everywhere in Qin.');
  add('qin-great-wall', 'Qin’s northern walls',
    'After unification, Qin campaigns and construction extended control along the northern frontier. Earlier states had already built walls; Qin adapted and connected parts of them. Much of the familiar stone and brick Great Wall belongs to later periods, especially the Ming.',
    'Keeping a wall working',
    'Fortifications needed soldiers, communications and dependable supplies. People had to build them, transport provisions and serve on difficult terrain. These projects show the emperor’s ability to demand labour and resources, along with the costs for those assigned to the frontier. Communities brought under new control also faced changes in how they were governed.',
    'A changing frontier',
    'Walls could direct movement and support military occupation without stopping every exchange. Their routes changed as rulers faced different conditions and enemies. The Great Wall is therefore a long history of separate projects, not one fixed national boundary built once. Qin’s northern expansion and later defensive programmes belong to different political circumstances.');
  add('yellow-turbans', 'Yellow Turban Uprising',
    'In 184, followers associated with the religious leader Zhang Jiao rose against Han rule. Their yellow head coverings gave them their name. Healing practices, hopes for a changed world and economic hardship helped draw supporters. Government forces defeated the main leaders that year, though related armed groups continued much longer.',
    'Beliefs connected people',
    'Shared religious practices linked communities beyond a single place. They helped people explain suffering and imagine another future. The movement’s intended government is less clear than the accounts of its defeat, mostly written by opponents. Neither dismissing it as superstition nor calling it a modern democratic revolution does justice to that uncertainty.',
    'More power for commanders',
    'The court relied on commanders and local forces to fight the uprising. Mobilizing them helped armed leaders build greater independent influence. Han did not end in 184; it formally lasted until 220. The rebellion and its suppression added to existing court conflict, rural insecurity and changes in who controlled the soldiers.');
  add('eight-princes', 'War of the Eight Princes',
    'The War of the Eight Princes groups several struggles among members of the Sima imperial family between 291 and 306. Palace takeovers grew into wider wars as princes sought control of the emperor and government. Their fighting weakened the unity Western Jin had achieved in 280.',
    'Family protection became rivalry',
    'Giving royal relatives armies could protect the dynasty from powerful ministers outside the family. It also gave those princes the means to fight each other. Competing claims and commands made succession dangerous. The arrangements meant to secure the dynasty therefore helped rivals challenge control of its centre.',
    'Damage beyond the court',
    'Campaigns disrupted communities and drew other armed groups into the contests. The later division of the north grew through civil war, recruitment, displacement and new alliances, rather than one sudden invasion. Western Jin survived beyond 306, but emerged weaker. Its later loss of the capitals formed further stages in that breakdown, ending the western dynasty in 316.');
  add('xiaowen-reforms', 'Northern Wei reforms',
    'In the late fifth century, Northern Wei changed land and household administration as well as life at court. Empress Dowager Feng and Emperor Xiaowen both shaped the reforms. The court moved from Pingcheng to Luoyang in 494, followed by changes to elite names, dress, language and marriage.',
    'Different rules for different purposes',
    'Household registration and land allocation aimed to strengthen access to farm resources. Court rules changed how powerful families behaved and displayed rank. These were political choices about governing, not simply a whole people deciding to become Chinese. Families could negotiate or resist measures that affected their position.',
    'A move with uneven effects',
    'Relocating the court changed its relationship with northern military communities. Older identities did not disappear, and government did not become uniform overnight. Some groups were now better placed to share in court rewards than others. Reforms intended to strengthen imperial rule could therefore create new divisions as well as closer connections. Feng’s role also prevents attributing the whole programme to Xiaowen alone.');
  add('zhuge-northern-expeditions', null,
    'Between 228 and 234, Zhuge Liang led repeated campaigns from Shu against Wei. Shu’s court in Sichuan claimed to restore Han rule, but faced a much larger rival. Mountain routes and the work of supplying soldiers limited what its armies could achieve.',
    'Getting food to the troops',
    'An army crossing difficult terrain needed provisions while leaving its home territory able to support the next campaign. A chance to win a battle mattered only if troops and supplies could reach it. Supply limits repeatedly forced the armies to withdraw. Comparing the cleverness of individual commanders cannot fully explain what Shu could sustain.',
    'The commander and his later reputation',
    'Zhuge Liang died in 234, ending his leadership of the campaigns. Shu survived until 263. Later stories made him a model of extraordinary foresight and loyalty. His historical work involved keeping a smaller state capable of pursuing a large military ambition. That sustained effort can be appreciated while keeping later fiction separate from accounts of the campaigns themselves.');
  add('fei-river', 'Battle of the Fei River',
    'In 383, Eastern Jin defeated Fu Jian’s Former Qin army at the Fei River. Former Qin had united much of the north and wanted to extend its rule south. Defeat disrupted that ambition and hastened the breakup of an alliance containing competing loyalties.',
    'One ruler, different interests',
    'Conquest had brought commanders and troops under Fu Jian without making all their interests the same. Their willingness to remain depended on rewards, confidence and the centre’s ability to demand obedience. Losing a battle could change those calculations. Defections and rival ambitions then made the consequences much larger than the immediate military loss.',
    'The south survived',
    'Victory allowed Eastern Jin and powerful southern families to continue developing government around the Yangtze. Former Qin did not disappear that day; it lasted until 394 as its territory fragmented. Traditional accounts contain dramatic tactics and enormous troop totals that remain uncertain. The choices commanders and rulers made after the battle determined its wider effects.');
  revisions['catalog-E_QIN_2'].note = '221 BCE dates the weights-and-measures edict. Other standardization measures developed over time; they were not all completed that year.';
  revisions['catalog-E_HAN_2'].note = 'Zhang Qian’s first mission is commonly dated 138–126 BCE; some sources use 139 BCE for departure.';
  revisions['catalog-E_BUD_ENTRY'].note = 'About 50 CE represents early contact, not a verified introduction year. The familiar imperial dream story is a later tradition, not a contemporary arrival record.';
  revisions['catalog-R_WEI'].note = '220–265 is one conventional dating for Wei. The Jin accession falls in 266 in common Gregorian chronologies.';
  revisions['catalog-E_3K_2'].note = '208 CE is the conventional battle date; the campaign extends into winter 208–209. Troop totals, the exact location and several familiar tactics are disputed.';
  revisions['catalog-R_SIXTEEN_LATER_ZHAO'].note = '319–351 is the conventional dynastic range. Stories of supernatural acts belong to religious biographies; they are not independently established events.';
  return { revisions };
})();
if (typeof module !== 'undefined' && module.exports) module.exports = BEGINNER_EARLY;
