// Generate the browser copy from the audited workbook export.
const fs = require('node:fs');
const path = require('node:path');
const source = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/china_history_v11.json'), 'utf8'));
fs.writeFileSync(path.join(__dirname, 'catalog_data.js'),
  '// Generated by build_catalog.js from the audited v11 export.\nconst HISTORY_CATALOG = ' +
  JSON.stringify(source.all, null, 2) + ';\nif(typeof module!=="undefined")module.exports=HISTORY_CATALOG;\n');
