/* Early China: dates distinguish remembered antiquity, surviving texts and political events.
 * Research checked 2026-09-05. Sources remain attached to each individual reading card.
 */
const EARLY_RESEARCH = (() => {
  const wiki = title => ['https://en.wikipedia.org/wiki/' + title.replaceAll(' ', '_'), 'Wikipedia · ' + title.replaceAll('_', ' ') + ' (reference overview)'];
  const sep = (slug, title) => ['https://plato.stanford.edu/entries/' + slug + '/', 'Stanford Encyclopedia of Philosophy · ' + title];
  const refs = {
    xia:['https://www.cambridge.org/core/journals/early-china/article/abs/erlitou-and-the-search-for-the-xia/56BB0C6F4CA7EE7F1FD3F67CA95895A9','Robert L. Thorp · Erlitou and the search for Xia'],
    xiaTradition:['https://ctext.org/shiji/xia-ben-ji','Sima Qian · Annals of Xia (later tradition)'],
    erlitouEconomy:['https://www.cambridge.org/core/elements/abs/shang-economy/6BF123B7BC3F1453C86172D7F529C0AE','Roderick Campbell · The Erlitou period'],
    erlitouEnvironment:['https://www.cambridge.org/core/elements/environmental-foundations-to-the-rise-of-early-civilisations-in-china/652E01F16B8F3686B1757284A2BA42E5','Yijie Zhuang · Environmental foundations of early Chinese civilisation'],
    bronze:['https://www.metmuseum.org/essays/shang-and-zhou-dynasties-the-bronze-age-of-china','Metropolitan Museum of Art · Shang and Zhou bronze cultures'],
    anyang:['https://asia.si.edu/exhibition/anyang-chinas-ancient-city-of-kings/','Smithsonian National Museum of Asian Art · Anyang: China’s Ancient City of Kings'],
    yinxu:['https://whc.unesco.org/en/list/1114/','UNESCO World Heritage Centre · Yin Xu'],
    wuDing:['https://www.cambridge.org/core/journals/radiocarbon/article/radiocarbon-dating-of-oracle-bones-of-late-shang-period-in-ancient-china/38A7B64D6D538A3A7B96F912BBEE9592','Radiocarbon · Dating late Shang oracle bones'],
    houmuwu:['https://en.chnmuseum.cn/collections_577/collection_highlights_608/archaeological_discoveries_609/202109/t20210902_251133.html','National Museum of China · Houmuwu Ding'],
    fuHao:['https://smarthistory.org/tomb-of-fu-hao/','Smarthistory · The tomb of Fu Hao'],
    bones:['https://asia.si.edu/explore-art-culture/collections/search/edanmdm%3Afsg_FSC-O-1a-e/','Smithsonian · Oracle-bone fragments, ca. 1250–1050 BCE'],
    memory:['https://www.cambridge.org/core/journals/early-china/article/beginning-of-cultural-memory-production-in-china-and-the-memory-policy-of-the-zhou-royal-house-during-the-western-zhou-period/F63EFDF78EAE29A923ADA7D597B85F43','Early China · Zhou royal memory and bronze inscriptions'],
    ritual:['https://www.cambridge.org/core/journals/early-china/article/abs/scribes-cooks-and-artisans-breaking-zhou-tradition/A16B318BE3C4E27FB3AA7F86D138A26A','Constance Cook · Scribes, cooks and artisans'],
    openstaxZhou:['https://openstax.org/books/world-history-volume-1/pages/5-1-ancient-china','OpenStax World History · Ancient China'],
    harvardBronze:['https://harvardartmuseums.org/collections/object/200497','Harvard Art Museums · Western Zhou ritual food vessel'],
    xunziEnfeoffment:['https://ctext.org/text.pl?node=12359&if=en&remap=gb','Chinese Text Project · Xunzi on the Zhou states'],
    xinian:['https://www.cambridge.org/core/journals/early-china/article/xinian-an-ancient-historical-text-from-the-qinghua-university-collection-of-bamboo-books/426F77FC5F669A0CB240EB650AD1A3FE','Early China · The Xinian and the Gonghe period'],
    zhongguo:['https://www.lhp.sdu.edu.cn/__local/A/EC/81/0CC1965B5469B3C1C017B45315A_F37EC24E_3458DD.pdf','Journal of Chinese Humanities · The earliest Zhongguo'],
    logistics:['https://www.cambridge.org/core/journals/early-china/article/emergence-of-logistics-networks-and-financial-administration-during-the-qin-conquest-230221-bce/88CAA846820D79FE59DE99630ADB3528','Early China · Qin logistics and financial administration'],
    qinMet:['https://www.metmuseum.org/essays/qin-dynasty-221-206-b-c','Metropolitan Museum of Art · Qin dynasty'],
    qinLand:['https://www.cambridge.org/core/journals/journal-of-chinese-history/article/making-use-of-the-land-the-political-ecology-of-chinas-first-empire/5C80E8CC40548B2953F72246C49A6CF7','Journal of Chinese History · Political ecology of the Qin empire'],
    tomb:['https://whc.unesco.org/en/list/441/','UNESCO · Mausoleum of the First Qin Emperor'],
    liSi:['https://afe.easia.columbia.edu/main_pop/ps/ps_china-lisi-legalist-memorials.htm','Columbia Asia for Educators · Li Si memorials in the Shiji'],
    han:['https://www.metmuseum.org/essays/han-dynasty-206-b-c-220-a-d','Metropolitan Museum of Art · Han dynasty'],
    hanSourcebook:['https://ccnmtl.columbia.edu/services/dropoff/china_civ_temp/week01/pdfs/chines2.pdf','Columbia University · Chinese Civilization sourcebook · Han overview'],
    government:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/structure-and-practice-of-government/85B70184514CED4B7F825C92626F971D','Cambridge History of China · Structure and practice of Han government'],
    recruitment:['https://www.cambridge.org/core/books/abs/bureaucracy-of-han-times/civil-service-recruitment/9334C1BD771968D5690197868D38DF38','Hans Bielenstein · The Bureaucracy of Han Times · Civil service recruitment'],
    restoration:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/wang-mang-the-restoration-of-the-han-dynasty-and-later-han/48EC19985183F5A65A477CB7133E8D80','Cambridge History of China · Wang Mang and Later Han'],
    silk:['https://whc.unesco.org/en/list/1442','UNESCO · Chang’an–Tianshan corridor'],
    buddhism:['https://depts.washington.edu/silkroad/exhibit/religion/buddhism/buddhism_silkroad.html','University of Washington · Buddhism on the Silk Routes'],
    paper:['https://www.iranicaonline.org/articles/paper-and-papermaking/','Encyclopaedia Iranica · Paper and papermaking'],
    yu:['https://academic.oup.com/edited-volume/63145/chapter-abstract/568229012','Oxford Handbook of Chinese Archaeology · Geoarchaeology and flood myths'],
    sun:['https://www.cambridge.org/core/journals/early-china/article/sunzi-versus-xunzi-two-views-of-deception-and-indirection/C1C5F934239AF76235BCC5D7B6831735','Early China · Sunzi and Xunzi on deception'],
    warringMet:['https://resources.metmuseum.org/resources/metpublications/pdf/The_Year_One_Art_of_the_Ancient_World_East_and_West.pdf','Metropolitan Museum of Art · The Year One: Warring States and Qin'],
    warringEno:['https://scholarworks.iu.edu/iuswrrest/api/core/bitstreams/51bdb8a8-620f-42ef-8a96-82fc3066efe3/content','Indiana University · The Warring States Period'],
    easternPeriod:['https://82nd-and-fifth.metmuseum.org/toah/ht/04/eac.html','Metropolitan Museum of Art · China, 1000 B.C.–1 A.D.'],
    easternInstitutions:['https://www.cambridge.org/core/elements/institutions-and-environment-in-ancient-southern-east-asia-3000-bce-to-300-ce/CC39D2BB0C5D015C230983E4DB2E3728','Cambridge Elements · Institutions and environment in ancient southern East Asia'],
    easternThought:['https://afe.easia.columbia.edu/main_pop/kpct/kp_4000bce-1000ce.htm','Columbia Asia for Educators · Key points across Chinese history'],
    dujiangyan:['https://whc.unesco.org/en/list/1001','UNESCO · Dujiangyan Irrigation System'],
    legalism:['https://plato.stanford.edu/entries/chinese-legalism/','Stanford Encyclopedia of Philosophy · Legalism in Chinese Philosophy'],
    lordShang:['https://afe.easia.columbia.edu/ps/cup/book_of_lord_shang.pdf','Columbia Asia for Educators · Selections from the Book of Lord Shang'],
    jixia:['https://www.cambridge.org/core/journals/early-china/article/abs/altars-of-the-soil-and-grain-are-closer-than-kin-the-qi-model-of-intellectual-participation-and-the-jixia-patronage-community/A423314171ED9CC423BFBCA2E11E9C9F','Early China · The Jixia patronage community'],
    changping:['https://opus.lib.uts.edu.au/handle/10453/183828','Journal of Chinese Military History · A study of the Battle of Changping'],
    weiqi:['https://www.ucpress.edu/books/go-nation/paper','University of California Press · Go Nation'],
    quYuan:['https://afe.easia.columbia.edu/main_pop/ps/ps_china-quyuan-encounteringsorrow.htm','Columbia Asia for Educators · Encountering Sorrow (Li Sao)'],
    sunHistory:['https://www.cambridge.org/core/books/abs/sun-tzu-in-the-west/brief-history-of-sunzi-in-china/7D72E0D2B07EE4C01679C56D821A0436','Cambridge · A brief history of Sunzi in China'],
    orthodoxy:['https://www.tandfonline.com/doi/full/10.1080/10971467.2020.1800901','Lee Ting-mien · The “victory of Confucianism” reconsidered'],
    hanThought:['https://www.cambridge.org/core/journals/early-china/article/ban-gus-view-on-the-second-victory-of-confucianism-and-the-fall-of-the-former-han/621066E658781FE88139CE2CBD6272A8','Early China · Ban Gu and Han political thought'],
    hanCensus:['https://doi.org/10.25365/jeacs.2025.6.1.roctus','Jasper Roctus · Han registration figures and later Chinese population claims'],
    hanPaper:['https://www.cai.cam.ac.uk/discover/library/online-exhibitions/print-and-material-book/paper','Gonville & Caius College, Cambridge · Paper before and after Cai Lun'],
    hanMusic:['https://www.metmuseum.org/essays/music-and-art-of-china','Metropolitan Museum of Art · Music and art of China'],
    saltIron:['https://afe.easia.columbia.edu/main_pop/ps/ps_china-debate-salt-iron.htm','Columbia Asia for Educators · Debate on Salt and Iron']
  };
  const card = (description, title1, text1, title2, text2, note, sources, extra={}) => ({description, sections:[{title:title1,text:text1},{title:title2,text:text2}],note,sources:sources.map(x=>x[0]),sourceLabels:Object.fromEntries(sources),evidence:'Source-checked historical interpretation',...extra});
  const revisions = {
    xia:card(
      'Xia stands at the beginning of the traditional sequence of Chinese dynasties. Its kings appear in later historical writing; no securely identified contemporary Xia royal archive confirms that sequence. The dates shown here retain the familiar traditional framework while marking a different quality of evidence from that available for late Shang.',
      'A dynasty and an archaeological culture are different claims',
      'Erlitou provides evidence of a major early Bronze Age centre: elite building, craft specialization and substantial concentrations of resources. Calling it Xia adds a historical identification to those archaeological observations. The association remains debated because resemblance in place and broad chronology cannot, by itself, identify the rulers of an excavated settlement. A political society can be real even when its ancient name is uncertain.',
      'Why the tradition mattered',
      'Later accounts made Xia the predecessor whose failure justified Shang’s succession, establishing a pattern that subsequent rulers could repeat. This is evidence about how antiquity was used to explain legitimate government. It is not a reason to discard the tradition, but a reason to ask separately what it remembers and what its later narrators needed it to mean.',
      '2070–1600 BCE is retained as a conventional, approximate chronology, not a securely documented reign sequence. Erlitou is not labelled here as proven Xia.',[refs.xia,refs.xiaTradition,refs.erlitouEconomy,refs.erlitouEnvironment,wiki('Xia_dynasty')],{approx:true,related:['catalog-E_XIA_1','catalog-F_XIA_1','shang','western-zhou','sima-qian']}),
    shang:card(
      'Shang rule is securely visible in late second-millennium BCE inscriptions, royal tombs and settlements. At Anyang, bronze workshops and inscribed bones reveal a court whose warfare, farming, ancestors and ritual obligations belonged to one connected political world. Evidence is richest for the dynasty’s later centuries.',
      'Ritual concentrated power',
      'Large bronze vessels required access to metal, fuel and highly skilled labour. Their use in offerings and feasts made rank visible and linked living rulers with powerful ancestors. These objects therefore document more than artistic accomplishment: they expose the resources a ruling house could assemble and the ceremonies through which authority was reproduced. Monumental tombs also preserve the coercion, including human sacrifice, behind that order.',
      'An archive with a point of view',
      'Oracle inscriptions bring us unusually close to royal decisions, but their survival does not turn them into a census of Shang society. They disproportionately record what worried the king and his diviners. Communities beyond the court, and competing Bronze Age centres outside its immediate reach, must be studied through other archaeological evidence. Shang should not be imagined as a modern territorial nation occupying every place later called China.',
      'The ribbon retains ca. 1600–1046 BCE. Late Shang writing is much more securely attested than the precise beginning of the dynasty.',[refs.anyang,refs.yinxu,refs.bronze,refs.wuDing,refs.houmuwu,refs.fuHao]),
    'western-zhou':card(
      'The Zhou defeated Shang and established a royal order centred in the Wei River valley. They extended power through related and allied houses, settlements and military obligations. Inscribed bronzes record appointments, gifts and service, showing authority being negotiated within a network rather than administered uniformly from one capital.',
      'Gifts made obligations durable',
      'An appointment or reward could be cast into bronze and displayed in ancestral rites. The recipient commemorated royal favour while claiming a place for descendants within the political order. Kinship mattered, but this was not simply a large family: warfare, skilled service, marriage and access to resources sustained the alliances that made the king’s reach possible.',
      'The past became an argument',
      'Memories of the founding conquest connected living elites with exemplary ancestors. As the court’s circumstances changed, those memories could be selected and reshaped. The Mandate of Heaven eventually offered an enduring explanation of why one ruling house might replace another. Reading it only as a timeless doctrine misses its practical value to a dynasty established by conquest and dependent on continued cooperation.',
      '1046 BCE is a widely used conquest date, but early Zhou chronology remains debated. “Feudal” is an imperfect comparison, not an exact match to medieval Europe.',
      [refs.openstaxZhou,refs.harvardBronze,refs.xunziEnfeoffment,refs.xinian,refs.zhongguo,refs.ritual],
      {related:['shang','catalog-E_SHANG_2','eastern-zhou']}),
    'eastern-zhou':card(
      'After the royal centre shifted east in 770 BCE, Zhou kings retained prestige while regional rulers increasingly controlled armies, revenue and policy. The dynasty’s long survival alongside stronger states separates ceremonial legitimacy from practical command. Spring and Autumn and Warring States are subdivisions of this changing political landscape.',
      'Weak kings did not mean weak government everywhere',
      'Rival courts developed their own capacities to tax, recruit, judge disputes and organize territory. The weakening of one centre could therefore accompany stronger government elsewhere. Officials, strategists and teachers moved between patrons, bringing methods and arguments that could circulate across political borders. This competition helps explain why the period produced both destructive warfare and institutional invention.',
      'A shared inheritance with rival interpretations',
      'Rulers and thinkers continued to invoke Zhou ritual and ancient exemplars even when disagreeing about the order they should create. Confucian, Mohist and other arguments emerged from a world of alternatives, not from a single national philosophy. Later classifications make that variety look tidier than it was. The important question is how competing claims to good rule worked within particular courts and communities.',
      '770–256 BCE dates the Eastern Zhou royal house. Warring States politics continues beyond its fall to 221 BCE; the two spans describe different things.',[refs.easternPeriod,refs.warringEno,refs.easternInstitutions,refs.easternThought,refs.dujiangyan,refs.jixia],{related:['western-zhou','late-warring']}),
    'late-warring':card(
      'The Zhou royal house ended in 256 BCE, but the struggle between territorial kingdoms continued. Qin’s final conquests came in 230–221 BCE. This short segment keeps the extinction of the old kingship separate from the later creation of a unified empire; it is not a separate dynasty.',
      'Winning required organization',
      'Qin’s strength involved more than the personal brilliance of a final ruler. Armies depended on households, grain, transport and officials able to move resources between regions. Recently studied Liye documents illuminate those logistical networks. Military success should therefore be read alongside the ordinary administrative work that made repeated campaigns possible, including responsibilities distributed across different offices.',
      'The endpoint was contingent',
      'Looking backward from 221 BCE can make Qin’s victory seem like the fulfilment of a plan shared by everyone. Contemporary rulers were defending different states and pursuing rival coalitions. Their defeat ended those political possibilities without erasing every regional practice or identity. The transition to empire changed the institutions within which people lived; it did not instantly make their languages, customs and loyalties identical.',
      '256–221 BCE is a display subdivision. It does not replace the full Warring States period or imply that conquest happened in a single campaign.',[refs.logistics,wiki('Qin%27s_wars_of_unification')]),
    qin:card(
      'Qin’s conquest of its rivals in 221 BCE produced a new imperial title and a government that extended appointed administration across conquered territories. The dynasty survived only until 206 BCE, yet later rulers retained much of its institutional vocabulary. Its short life and long influence must be explained together.',
      'Integration through practical standards',
      'Measures, documents and official procedures helped make resources and commands comparable across distance. Such arrangements could support commerce, but their immediate political value was to make people and goods accessible to government. Excavated administrative records reveal multiple offices and routine transfers behind the image of an all-commanding emperor. Centralization was an ambition implemented through people, paperwork and negotiation.',
      'Capacity could also become overextension',
      'Campaigns, construction and compulsory service placed heavy demands on households. After the First Emperor’s death in 210 BCE, succession conflict and rebellion broke the regime. Later Han accounts had reasons to emphasize Qin cruelty, so their moral verdict should be tested against material evidence. The durability of Qin institutions suggests that the problem was not administration itself, but how power was exercised, mobilized and transmitted.',
      '221–206 BCE dates the empire; Qin existed as a state for centuries before it. Descriptions of identical rule across every locality overstate what survives in the evidence.',[refs.qinMet,refs.legalism,refs.logistics,refs.qinLand,refs.tomb,refs.liSi]),
    han:card(
      'Han rulers rebuilt an empire after the wars that destroyed Qin. The dynasty encompassed Western Han, Wang Mang’s intervening Xin regime and the Eastern Han restoration. Its legacy includes durable administrative practices, classical scholarship and expanding connections across Eurasia, but four centuries cannot be reduced to a single stable system.',
      'An empire assembled from different arrangements',
      'Commanderies governed by officials coexisted with kingdoms held by members of the imperial family. Court authority grew through repeated disputes over these arrangements, rather than through a complete rejection of aristocratic power. Revenue and labour came largely from agricultural households, while officials relied on local knowledge and influential families to turn imperial instructions into action.',
      'A cultural achievement with social costs',
      'Tombs preserve extraordinary textiles, lacquer and images of farms, servants and entertainments. These illuminate elite ambitions while indirectly revealing the labour on which that world depended. Classical learning became increasingly important in political argument, yet law, punishment and hereditary advantage remained powerful. The familiar contrast between a harsh Qin and a humane Han obscures substantial institutional continuities and conflicts within Han government itself.',
      '206 BCE marks Liu Bang becoming king of Han; 202 BCE marks his imperial accession. The overview includes the Xin interruption 9–23 CE, shown separately.',[refs.han,refs.hanSourcebook,refs.government,refs.recruitment,refs.orthodoxy,refs.silk,refs.hanCensus,refs.hanPaper,refs.hanMusic,refs.saltIron],{nameZh:'汉朝'}),
    xin:card(
      'Wang Mang replaced Han rule in 9 CE, founding the Xin dynasty. His programmes invoked an idealized ancient order while attempting changes to landholding, slavery, currency and state economic activity. Rebellion ended his reign in 23 CE; the subsequent restoration of Han was itself achieved through further warfare.',
      'Radical change in the language of restoration',
      'An appeal to antiquity could justify intervention as readily as conservatism. Wang Mang claimed to recover proper institutions, but the practical changes disturbed established interests and familiar transactions. Repeated monetary reforms show the distance between a ruler’s capacity to issue a new standard and the public’s ability or willingness to use it. Proclamation alone could not supply administrative competence or trust.',
      'Failure had several causes',
      'Flooding, displacement and rural hardship intensified a political crisis already shaped by resistance and difficult implementation. Treating the fall as proof that reform always fails makes the outcome explain itself. Equally, calling Wang Mang a modern socialist imports a later political category into a regime committed to ancient hierarchy. His significance lies in the mixture of moral ambition, coercive authority and limited practical control.',
      '9–23 CE dates the Xin regime. The scale and implementation of individual reforms are debated; later Han histories were written within the dynasty that supplanted him.',[wiki('Wang_Mang'),refs.restoration]),
    oracle:card(
      'Late Shang diviners applied heat to prepared animal bones or turtle plastrons and interpreted the resulting cracks. Inscriptions could record the question, prediction and sometimes the outcome. These objects preserve the earliest large body of securely attested Chinese writing, especially from the court at Anyang.',
      'Questions reveal a government’s anxieties',
      'Harvests, childbirth, weather, warfare and ritual offerings appear together because the king’s security depended on both human action and ancestral powers. The inscriptions show decisions being framed and remembered. Their repeated forms also reveal specialized knowledge and organized record-making. Writing enters the surviving record already connected with people trained to prepare, interpret and preserve authoritative statements.',
      'Survival is not the same as invention',
      'The date of an excavated inscription establishes that writing existed by then; it does not identify the moment someone invented it. Other writing materials preserve less well, and the script’s complexity suggests a preceding development that remains difficult to reconstruct. Nor do royal divination records represent everyone’s speech or concerns. Their extraordinary value comes with a sharply bounded social viewpoint.',
      'Ca. 1250 BCE is a reference point for the surviving late Shang corpus, not a proven invention year. Many characters and readings remain disputed.',[refs.bones,wiki('Oracle_bone_script')],{approx:true}),
    confucius:card(
      'Confucius, traditionally dated 551–479 BCE, taught during the weakening of Zhou royal authority and conflict among aristocratic houses. Texts associated with him connect good government to cultivated character, ritual conduct and learning. The Analects preserves a conversation across generations rather than a transcript taken directly from a single teacher.',
      'Ritual was a way of forming people',
      'Courteous performance was not sufficient on its own: conduct needed appropriate feeling, judgment and concern for others. Repeated practices could train those dispositions. That places education at the centre of politics. A ruler who cannot govern himself is a poor model for those below him, while service to rulers creates obligations to advise and sometimes criticize, not simply obey.',
      'Influence was made after his lifetime',
      'Later communities selected different aspects of this inheritance: ethical self-cultivation, family hierarchy, political remonstrance or textual scholarship. Imperial patronage subsequently gave some interpretations institutional force. Calling every later hierarchy “Confucian” mistakes a long history of argument for the automatic unfolding of one man’s intentions. His enduring importance lies partly in the resources that competing interpreters found in those teachings.',
      '551 BCE is the traditional birth date, retained as the marker. The textual layers and precise attribution of sayings remain subjects of scholarship.',[sep('confucius','Confucius'),wiki('Analects')]),
    unification:card(
      'Qin’s conquest of Qi in 221 BCE completed the defeat of the six major rival kingdoms. Ying Zheng adopted the title First Emperor. This was a decisive political transformation, but the new empire occupied a world of existing communities and institutions; it did not create society from nothing.',
      'Conquest changed who could issue commands',
      'The elimination of rival courts allowed Qin standards and appointed officials to extend farther than before. Local officials still had to identify households, transport supplies and interpret orders. The achievement therefore lay both in defeating armies and in redirecting working administrative networks toward a new sovereign. Military victory and everyday government were related tasks, not interchangeable accomplishments.',
      'Unity was a claim that required maintenance',
      'The new title announced an authority intended to outlast ordinary kingship. Yet the succession after 210 BCE showed how fragile that claim could be when concentrated power passed between rulers. Han later rebuilt unity using institutions inherited from its defeated predecessor. The contrast reveals why 221 BCE matters: it established a powerful political possibility, even though Qin itself failed to make that possibility secure.',
      '221 BCE marks completion of the major conquests. “China unified” is shorthand for those kingdoms, not a claim that Qin controlled the borders of the present-day state.',[wiki('Qin%27s_wars_of_unification'),refs.tomb]),
    paper:card(
      'The court official Cai Lun is traditionally credited with presenting an improved papermaking process in 105 CE. The account describes materials including bark, hemp waste, rags and fishing nets. Archaeological paper predates him, so the marker identifies a remembered improvement and imperial recognition rather than invention from nothing.',
      'A material changes what can circulate',
      'Paper could be lighter than bundles of bamboo or wood and cheaper than silk, creating possibilities for copying, correspondence and later printing. Those advantages did not instantly remove older materials. Skilled production, reliable supply and the habits of writers mattered as much as a technical recipe. The historical change was an expanding material infrastructure for texts.',
      'Innovation and commemoration are different histories',
      'A named inventor gives a diffuse craft history a memorable protagonist. Cai Lun’s association with the court helped preserve his place in the written record, whereas generations of unnamed workers are harder to recover. The distinction becomes especially important when following paper westward: technologies spread through repeated adaptation and transmission, not necessarily through one heroic inventor or one famous battle.',
      '105 CE is the traditional report date. Earlier finds disprove a literal first-invention claim; the date when paper became dominant varied by place and use.',[wiki('Cai_Lun'),refs.paper]),
    'catalog-E_XIA_1':card(
      'Later tradition describes Yu’s establishment of Xia as a beginning of dynastic rule. The familiar 2070 BCE date belongs to a reconstructed chronology, not to a contemporary foundation document. This card preserves the workbook’s event while distinguishing remembered political origins from securely dated evidence.',
      'A story about the right to govern',
      'Yu earns authority by restoring a habitable world after flooding. That sequence makes service to people a foundation for rule, before the succession to his son introduces hereditary power. The narrative contains a tension later thinkers could use: should office pass to the most capable person or remain within a ruling family? Its importance extends beyond whether every episode can be verified.',
      'What archaeology can and cannot settle',
      'Evidence of early centres, elite buildings or ancient floods may illuminate the conditions in which political traditions developed. It cannot independently establish that a named hero founded a dynasty in a particular year. Connecting an environmental event, a settlement and a much later story requires several separate arguments. Preserving those distinctions makes the timeline an account of evidence as well as a sequence of names.',
      '2070 BCE is traditional and uncertain. This is not an asserted archaeological identification of Xia or an independently dated coronation.',[refs.xia,wiki('Xia_dynasty')],{approx:true}),
    'catalog-F_XIA_1':card(
      'Yu the Great is a culture hero remembered for controlling a catastrophic flood and ordering the landscape. Later traditions place him before or at the foundation of Xia. His conventional position here is not a verified birth year: it indicates the legendary antiquity in which these narratives situate him.',
      'Making the landscape governable',
      'Stories of channeling rivers and opening passages present political authority as practical labour on behalf of a wider community. The ruler brings order by working with a difficult environment. Those motifs offered later governments a language for explaining their own hydraulic projects and responsibilities. They also made failures of water management politically meaningful, rather than merely unfortunate natural events.',
      'A powerful memory is not a literal report',
      'The tradition survives in varied accounts assembled long after the supposed events. Geological research can identify ancient floods, but a flood deposit cannot identify the person who responded to it or authenticate an entire narrative. Historians therefore study Yu both as an uncertain figure of remote antiquity and as a demonstrably influential presence in later political and religious imagination.',
      'The workbook’s 2100 BCE reference is retained outside the plotted range. Yu’s identity, lifetime and connection with particular flood events are not securely established.',[wiki('Yu_the_Great'),refs.yu],{approx:true}),
    'catalog-E_SHANG_2':card(
      'King Wu’s defeat of Shang became the founding victory of Zhou. Bronze inscriptions and later texts preserve memories of the conquest, although its exact chronology remains disputed. Zhou consolidation continued after the initial battle, including a rebellion and further campaigns associated with the Duke of Zhou.',
      'Winning a battle was only the beginning',
      'A new ruling coalition had to manage conquered elites, reward allies and establish durable centres of authority. The survival of Shang ritual practices within Zhou society shows that conquest did not require a clean cultural break. Political replacement could proceed through selective incorporation: useful specialists, ceremonies and inherited prestige could all serve the new rulers.',
      'Victory became a moral precedent',
      'Later accounts explained Shang’s defeat as the result of lost virtue and Heaven’s favour passing to Zhou. That interpretation made successful rebellion compatible with legitimate authority. It also invited future critics to ask whether current rulers still deserved their position. The conquest therefore mattered twice: as a redistribution of power and as a remembered example through which subsequent generations argued about power.',
      '1046 BCE is a widely used conventional date. The subsequent consolidation is not compressed into a claim that the entire Zhou order began on one day.',[refs.memory,wiki('Battle_of_Muye')]),
    'catalog-R_ZHOU':card(
      'Zhou spans a long transformation from a royal network established after the conquest of Shang to an era of competing territorial kingdoms. Its western and eastern phases describe the location and circumstances of the royal house. They do not imply that the same institutions operated unchanged for nearly eight centuries.',
      'Authority outlived direct control',
      'The king’s practical reach eventually shrank, but Zhou titles, rituals and remembered ancestors continued to matter. This helps explain why powerful regional rulers sometimes sought recognition from a weakened centre. Prestige could coordinate relationships even when it could no longer reliably command armies. Political authority had several components, and losing one did not immediately erase all the others.',
      'An inheritance built through reinterpretation',
      'Later teachers appealed to Zhou as an age of exemplary government while responding to circumstances their predecessors had never faced. The appeal was selective: rituals, poems and stories became resources for new arguments. The dynasty’s cultural afterlife is therefore not simply a surviving copy of early institutions. It is also a history of how people reconstructed an authoritative past to address a changing present.',
      '1046–256 BCE dates the royal dynasty using the timeline’s convention. Its fall precedes the conclusion of Warring States politics in 221 BCE.',[wiki('Zhou_dynasty'),refs.memory]),
    'catalog-SR_SA':card(
      'The Spring and Autumn period takes its name from annals associated with the state of Lu. Following the Zhou court’s eastward relocation, regional houses competed through war, diplomacy and alliance. Strong rulers could claim leadership over other states while continuing to acknowledge Zhou ceremonial precedence.',
      'Competition within a shared language of rank',
      'Covenants, marriages, visits and ritual distinctions were tools of interstate politics. They could establish obligations and display hierarchy, even when participants violated them. Warfare and ceremony therefore belong in the same explanation. The period’s rulers were not simply waiting for ritual to disappear before “real” politics began; ceremonial expertise could itself provide political influence.',
      'Reading change without an abrupt break',
      'Over time, struggles within ruling houses and expansion between states changed the distribution of power. Later histories organized these developments into periods with sharply named boundaries. Those boundaries help comparison, but they cannot make every locality change at once. The transition to Warring States government was uneven, involving both inherited aristocratic practices and growing territorial administration. The later conquest states developed within this competitive world.',
      '770–481 BCE retains the workbook’s division.476/475 BCE and other boundaries appear in scholarship;481 BCE is not a universal switch in institutions.',[wiki('Spring_and_Autumn_period'),refs.ritual]),
    'catalog-SR_WS':card(
      'During the Warring States period, rival kingdoms developed stronger territorial governments and fought increasingly demanding wars. Officials, soldiers, farmers and thinkers became central to competing projects of state-building. Qin’s victory in 221 BCE ended the principal interstate contest, but that outcome should not obscure the alternatives that had existed.',
      'The household became a resource of the state',
      'Registration, taxation and military service connected ordinary people more directly to rulers. Agricultural output and effective administration could translate into armies and territorial expansion. This did not amount to a uniform “total war system” everywhere: states differed, and ritual, hereditary privilege and local interests continued to shape government alongside new methods of mobilization.',
      'Intellectual disagreement was part of the crisis',
      'Thinkers disputed whether order required moral cultivation, impartial care, exemplary institutions, strategic restraint or severe incentives. Their arguments addressed practical questions about violence and cooperation. They were not interchangeable expressions of one Chinese worldview. The later habit of grouping them into schools can be useful, provided those labels do not conceal textual diversity or the changing patronage that allowed ideas to circulate.',
      '481–221 BCE preserves the workbook convention. Common alternatives begin 475 or 403 BCE. The date range labels a historical period, not one government.',[wiki('Warring_States_period'),['https://www.persee.fr/doc/befeo_0336-1519_1997_num_84_1_2473','Bulletin de l’École française d’Extrême-Orient · Ritual origins of Warring States'],refs.warringMet,refs.warringEno,refs.legalism,refs.lordShang,refs.jixia,refs.changping,refs.logistics,refs.weiqi,refs.quYuan,refs.sunHistory]),
    'catalog-F_SUN':card(
      'The Art of War attributed to Sunzi presents warfare as a problem of information, organization and advantage. Its thirteen chapters discuss conditions under which force should be used and resources preserved. The traditional author Sun Wu is much less securely recoverable than the text’s existence and later influence.',
      'Restraint was a strategic argument',
      'Avoiding a costly siege or prolonged campaign could preserve the strength needed to achieve a ruler’s objective. Deception and intelligence mattered because fighting occurred under uncertainty. This is neither a simple celebration of violence nor a pacifist programme: the text asks how to secure political advantage while limiting unnecessary military expense and exposure.',
      'One tradition, not the Chinese mind',
      'Other early thinkers challenged the moral and practical value of deception. Comparing Sunzi with Xunzi reveals real disagreement within ancient China rather than a timeless national approach to strategy. Modern business adaptations often detach memorable sayings from armies, supplies and rulers. Returning to those conditions helps explain the work’s arguments without assuming that every maxim transfers unchanged to any competitive situation.',
      'Ca. 500 BCE remains a conventional reference, not a secure birth or composition date. The text’s formation and authorship are debated; Han tomb manuscripts establish early circulation.',[wiki('Sun_Tzu'),refs.sun],{approx:true}),
    'catalog-G_ALEX':card(
      'Alexander’s conquests between 334 and 323 BCE dismantled the Achaemenid Persian Empire and carried Macedonian armies into Central Asia and northwestern South Asia. The 330 BCE marker is a point within that campaign, included as wider-world context rather than an event occurring in the Chinese states.',
      'Conquest created an unstable inheritance',
      'After Alexander died in 323 BCE, his commanders fought over the empire and established successor kingdoms. Political fragmentation did not erase the cities, institutions and artistic exchanges associated with their rule. Hellenistic culture developed through those later societies as well as through conquest itself, combining royal patronage with different regional inheritances.',
      'Comparison is not evidence of contact',
      'Alexander and Warring States rulers faced problems of military supply, elite cooperation and governing conquered populations. Those similarities permit comparison; they do not establish direct influence between them. Connections linking the Mediterranean, Central Asia and China expanded through many later intermediaries. A global timeline should expose contemporaneous developments without drawing an imaginary road between every pair of events that happens to share a century.',
      '330 BCE is retained as a campaign reference. Alexander did not invade China; later Eurasian exchanges should not be attributed to a personal encounter that never occurred.',[['https://www.metmuseum.org/essays/art-of-the-hellenistic-age-and-the-hellenistic-tradition','Metropolitan Museum of Art · Hellenistic art and its contexts'],wiki('Alexander_the_Great')]),
    'catalog-S_QH':card(
      'The Qin–Han span groups the formation and consolidation of early imperial government. Qin established an empire in 221 BCE; Han rulers reworked that inheritance after civil war. The grouping is useful for examining institutional continuities across dynastic change, not for claiming that the two regimes were identical.',
      'Government depended on administrative routines',
      'Law, registration, records and systems for moving goods made extensive rule possible. The emperor stood at the apex, but local officials and their staff had to turn commands into decisions about taxes, service and disputes. Documents reveal a world of offices and procedures beneath the dramatic stories of founding rulers. Imperial power depended on that routine activity to reach households.',
      'A lasting ideal did not guarantee lasting unity',
      'Later dynasties repeatedly returned to the ambition of governing a single realm. That ambition survived periods when several states competed for authority, suggesting a distinction between an influential political ideal and continuous political control. Qin and Han supplied precedents for both administration and argument. Subsequent governments selected and adapted those precedents as their own fiscal, military and social circumstances changed.',
      '221 BCE–220 CE is an analytical grouping with the Xin interruption included. It is neither a dynasty nor a claim that later imperial history followed an inevitable path.',[refs.government,wiki('Government_of_the_Han_dynasty')]),
    'catalog-R_HAN_W':card(
      'Western Han rulers established their principal capital at Chang’an after the wars following Qin’s collapse. Liu Bang became emperor in 202 BCE, while 206 BCE conventionally dates the dynasty from his earlier title as king of Han. The period ended when Wang Mang founded Xin in 9 CE.',
      'Building a coalition and restraining it',
      'The early empire combined centrally governed commanderies with substantial kingdoms. Rewarding supporters helped secure victory, but powerful territorial rulers also posed future risks. The court progressively reduced those autonomous powers, especially after the rebellion of seven kingdoms in 154 BCE. The process illustrates a recurring problem of conquest: arrangements that recruit allies can become obstacles to a successor’s control.',
      'Expansion sharpened the question of cost',
      'Emperor Wu’s campaigns and frontier activity required sustained finance and supplies. Policies associated with monopolies, revenue extraction and classical learning formed part of a disputed programme of rule. Critics could attack the burdens of expansion without rejecting monarchy itself. Western Han political thought therefore belongs alongside its military history: arguments over how to govern were also arguments over what households should be made to support.',
      '206 BCE–9 CE follows the workbook.202 BCE is the imperial accession date. The dynasty’s institutions and territorial reach varied substantially over this span.',[wiki('History_of_the_Han_dynasty'),refs.han]),
    'catalog-R_HAN_E':card(
      'Liu Xiu proclaimed the restoration of Han in 25 CE and governed from Luoyang. Restoring the dynastic name did not simply restore the previous world: civil war had changed political alliances and local power. Eastern Han survived until 220 CE, though its final decades saw authority fragment among military leaders.',
      'Court politics and social foundations',
      'Imperial relatives, empresses’ families, eunuchs and officials all participated in struggles over access to the throne. These were not merely personal quarrels detached from government. Appointment and patronage connected the palace to resources and supporters beyond it. Local elite families also supplied administrative expertise and influence that the court needed but could not always easily direct.',
      'A long period beyond its collapse',
      'The final crises can overshadow two centuries of scholarship, material production and cross-regional contact. Ban Zhao’s writing and Zhang Heng’s work show an intellectual world combining historical knowledge, moral argument and technical inquiry. The dynasty’s eventual failure does not make those developments symptoms of decline. It asks instead how an enduring political order lost the ability to manage succession, armed force and competing interests.',
      '25–220 CE dates the restored dynasty; Liu Xiu’s reunification continued after 25. War between regional powers preceded formal abdication in 220.',[refs.restoration,wiki('Eastern_Han')]),
    'catalog-E_QIN_2':card(
      'Qin’s imperial government promoted common standards for writing, weights, measures and administrative practice after unification. The 220 BCE marker represents this programme rather than a single decree that accomplished everything at once. Material standards and written orders made conquered resources easier to classify and mobilize.',
      'A measure is also a relationship of authority',
      'A standard weight tells officials and traders what counts as an equivalent amount. When backed by government, it can reduce ambiguity while extending the ruler’s authority into ordinary transactions. Inscribed measures connected that practical function with an imperial announcement. Standardization therefore joins commerce, taxation and political display rather than belonging exclusively to one of them.',
      'Uniform instructions met a varied world',
      'People did not cease speaking different varieties of language because official writing was regularized. Nor does an order prove immediate compliance in every district. Qin documents reveal transfers, local records and distinct responsibilities within a larger administrative structure. The useful historical question is how far a standard travelled and how it was used, not whether one decree magically eliminated diversity.',
      '220 BCE is a reference year for a process following 221 BCE. Script standardization does not mean the creation of a uniform spoken language.',[refs.tomb,wiki('Qin_dynasty')]),
    'catalog-E_HAN_1':card(
      'Han courts increasingly supported classical scholarship and used inherited ethical language to discuss government. Emperor Wu established an imperial academy in 124 BCE. The workbook’s 130 BCE marker represents this broader development, not a documented day on which every rival teaching was abolished.',
      'Learning offered both service and criticism',
      'Classical expertise could qualify a person for political participation and supply precedents for court decisions. It could also authorize criticism of rulers who failed to meet those precedents. Official sponsorship thus did more than impose obedience: it created a recognized language within which scholars could disagree over expenditure, ritual and the welfare of the people.',
      'The label can hide the mixture',
      'Scholars debate what “the triumph of Confucianism” actually describes in Han society. Courts continued to use administrative law, coercion, cosmological interpretation and several intellectual traditions. Neither a simple conversion of the state nor a clean replacement of “Legalism” captures that mixture. The enduring change was the growing institutional importance of certain texts and specialists, whose meanings remained open to contest.',
      'Ca. 130 BCE is retained as a process marker.124 BCE dates the academy; a single exclusive ideology imposed everywhere is not assumed.',[refs.orthodoxy,refs.hanThought],{approx:true,name:'Classical learning and Han government'}),
    'catalog-E_HAN_2':card(
      'Han missions and frontier expansion strengthened connections between the imperial court and Central Asian societies in the second century BCE. Zhang Qian’s journeys became a landmark in that history. The routes already depended on local populations and earlier exchanges; no single traveller created them from nothing.',
      'Diplomacy, trade and war overlapped',
      'The search for allies against the Xiongnu encouraged the court to acquire information about distant peoples and resources. Envoys carried gifts, rulers exchanged prestige goods, and merchants used opportunities opened or constrained by politics. Separating a peaceful commercial road from a violent frontier would distort how these networks actually operated.',
      'A network rather than a highway',
      'Goods often passed through several hands and travelled along changing routes. Oasis agriculture, water supplies and local political arrangements made long-distance movement possible. The modern term “Silk Road” can obscure this dispersed infrastructure as well as the many commodities besides silk. Its value is to encourage connected history, provided connection does not erase the agency of communities between the large empires.',
      'Ca. 130 BCE is retained as a broad marker. Zhang Qian’s first mission is commonly dated 138–126 BCE; some sources use 139 BCE for departure.',[refs.silk,['https://www.unesco.org/en/silk-roads/about-silk-roads','UNESCO · About the Silk Roads']],{approx:true}),
    'catalog-E_BUD_ENTRY':card(
      'Buddhism reached communities within the Han world through travellers, merchants and religious specialists moving from South and Central Asia. The 50 CE marker is approximate. Secure evidence becomes clearer in the first and second centuries CE, especially as translators established a Chinese-language body of Buddhist teaching.',
      'Translation changed the terms of understanding',
      'Ideas about liberation, rebirth and disciplined religious life had to be expressed through unfamiliar languages and existing Chinese vocabularies. That process involved selection and explanation, not simply transporting an unchanged doctrine. Named translators such as An Shigao in the second century provide firmer historical anchors than a single story of Buddhism’s “arrival.”',
      'Contact was not immediate conversion',
      'The presence of Buddhist practitioners at particular centres does not establish wide popular adherence or uniform imperial support. Communities developed unevenly, drawing on patronage and exchange across political boundaries. Later traditions about emperors discovering Buddhism helped explain its place in China, but should not replace evidence for the more gradual work of teaching, translating and sustaining religious communities.',
      'Ca. 50 CE is a broad contact marker, not a verified introduction year. The familiar imperial dream narrative is a later tradition, not a contemporary arrival record.',[refs.buddhism,wiki('Silk_Road_transmission_of_Buddhism')],{approx:true,name:'Early Buddhist contact and translation'}),
    'catalog-C_QIN':card(
      'The First Emperor’s mausoleum complex contains thousands of terracotta soldiers, horses, weapons and other figures. Its construction began before imperial unification and continued into the end of his reign. The 210 BCE marker is his death year, not the date on which every figure was made.',
      'An afterlife organized like an empire',
      'The army belongs to a much larger landscape of burial facilities and supporting installations. It materializes an ambition to continue imperial command beyond death. Soldiers are therefore one part of the story: the complex also exposes the production, transport and skilled labour necessary to make a royal vision physically durable at extraordinary scale.',
      'What the objects let us see',
      'Variations in faces and equipment coexist with repeated components and organized manufacture. Individual appearance need not mean each figure was a portrait of an actual soldier. Archaeology can illuminate craft organization and military representation while leaving other questions unresolved. The unexcavated central burial chamber is especially important: later descriptions of its contents should not be presented as things archaeologists have already seen.',
      '210 BCE is a commemorative endpoint. UNESCO dates the beginning of the mausoleum project to 246 BCE; the warriors were discovered in 1974.',[refs.tomb,wiki('Terracotta_Army')]),
    'catalog-E_3K_2':card(
      'At Red Cliffs in the winter of 208–209 CE, forces associated with Sun Quan and Liu Bei checked Cao Cao’s advance along the Yangtze. Cao Cao already dominated the north and controlled the Han emperor. His defeat preserved space for southern rivals while the Han dynasty still formally existed.',
      'The river shaped political possibility',
      'Naval experience, disease, supply and the difficulties of campaigning away from familiar territory mattered alongside battlefield decisions. The result prevented the immediate extension of northern supremacy into the south. It did not by itself establish three kingdoms: the regimes later called Wei, Shu and Wu emerged through subsequent campaigns and claims to sovereignty.',
      'The remembered battle and the historical battle',
      'Later fiction made Red Cliffs a theatre of extraordinary stratagems and personalities. The historical record is more limited and does not warrant treating every famous episode as fact. That gap is productive: the battle’s later appeal reveals how stories of loyalty and intelligence were attached to a real political turning point. Literary influence and military evidence deserve attention, but require different kinds of questions.',
      '208 CE remains the conventional marker; the campaign extends into winter 208–209. Troop totals, exact location and several familiar stratagems are disputed.',[['https://www.usni.org/magazines/naval-history-magazine/2023/february/flaming-ships-red-cliffs','US Naval Institute · The Flaming Ships of Red Cliffs'],wiki('Battle_of_Red_Cliffs'),wiki('End_of_the_Han_dynasty')])
  };
  const iep = (slug,title) => ['https://iep.utm.edu/'+slug+'/', 'Internet Encyclopedia of Philosophy · '+title];
  const events=[];
  const pinyin={};
  const add = (id,name,nameZh,pronunciation,han,glyphPinyin,start,end,parent,ribbon,content) => {
    events.push({id,name,nameZh,han,start,end,parent,ribbon,label:false,color:'#987950',category:'culture',...content,source:content.sources[0]});
    pinyin[nameZh]=pronunciation;pinyin[han]=glyphPinyin;
  };
  add('laozi','Laozi and the making of the Daodejing','老子与道德经','Lǎozǐ yǔ Dàodéjīng','道','Dào',-400,-250,'eastern-zhou',true,card(
    'Laozi is the “Old Master” associated with the Daodejing, a short text central to later Daoist traditions. His historical identity and lifetime are uncertain. The range shown marks an approximate Warring States setting for the text’s formation, not the supposed lifespan of a securely documented individual.',
    'Power through restraint',
    'The text repeatedly questions aggressive striving, excessive desire and the confidence of those who would impose order by force. Its account of wuwei, often translated as non-action, does not simply mean doing nothing. It asks whether effective action can avoid coercive interference and self-defeating ambition. These arguments have political as well as personal implications, though interpreters disagree about their precise programme.',
    'An ancient book with a changing form',
    'Guodian manuscripts preserve related passages by around 300 BCE, while Mawangdui copies show arrangements different from the familiar received text. These discoveries make compilation and transmission central to understanding the work. Stories of a sage writing a complete book at a frontier pass belong to its later biography and reception. They should not replace the material evidence of textual plurality.',
    'Ca. 400–250 BCE is an interpretive composition range with uncertain boundaries. Tradition places Laozi earlier; this card does not assert an invented birth year or a single author.',[sep('laozi','Laozi'),iep('laozi','Laozi')],{approx:true,related:['confucius','zhuangzi','mawangdui-manuscripts']}));
  add('mozi','Mozi and impartial concern','墨子与兼爱','Mòzǐ yǔ Jiān’ài','墨','Mò',-450,-390,'eastern-zhou',true,card(
    'Mozi and the Mohist movement challenged warfare, luxury and inherited privilege during the Warring States era. Mozi probably flourished in the later fifth centuryBCE, but his precise dates are unknown. The surviving Mozi contains arguments developed by followers as well as teachings associated with its named master.',
    'Whose welfare should count?',
    'Mohist inclusive care challenged the assumption that obligations should stop at family or political borders. Aggressive war looked indefensible when judged by the harm it inflicted rather than the glory claimed by a ruler. The same attention to consequences informed criticism of extravagant funerals and musical display: labour and resources should serve collective benefit, not merely elite prestige.',
    'Universal concern did not imply liberal politics',
    'Mohists also favoured an ordered hierarchy, shared moral standards and the promotion of capable officials. Their appeal to Heaven and spirits coexisted with disciplined argument about practical effects. This combination prevents easy translation into a modern party platform. Their significance lies in forcing opponents to explain why some lives, expenditures and practices should receive greater consideration than others.',
    'Ca. 450–390 BCE marks the early movement, not securely established life dates. “Universal love” can mislead if it suggests identical feelings rather than inclusive ethical concern.',[sep('mohism','Mohism'),iep('mozi','Mozi')],{approx:true,related:['confucius','mencius','catalog-F_SUN']}));
  add('mencius','Mencius: livelihood and moral government','孟子与仁政','Mèngzǐ yǔ Rénzhèng','孟','Mèng',-370,-290,'eastern-zhou',false,card(
    'Mencius developed arguments about moral cultivation and benevolent government in the fourth centuryBCE. His dialogues with rulers present humane conduct as a basis for political authority. The text bearing his name was transmitted through followers and later editors; the conventional life dates remain approximate.',
    'Goodness needed conditions in which to grow',
    'The claim that human nature is good concerns moral capacities that require cultivation, not the assertion that people invariably behave well. Mencius linked ordinary conduct to the conditions of livelihood. A ruler who leaves people insecure and then punishes their resulting misconduct cannot simply blame defective character. Material government and ethical education therefore belong within the same political argument.',
    'Kingship had moral limits',
    'The text judges rulers by their responsibilities to the people and permits severe criticism of those who abandon them. This is not modern popular sovereignty: hereditary monarchy and differentiated social roles remain the setting. Nevertheless, it denies that possession of a throne automatically settles the question of rightful rule. Later thinkers could use that distinction either to instruct rulers or to condemn them.',
    'Ca. 370–290 BCE is a conventional approximate lifespan. The received Mencius is a layered transmission; familiar anecdotes are philosophical presentations, not verbatim court minutes.',[sep('mencius','Mencius'),iep('mencius','Mencius')],{approx:true,related:['confucius','mozi','xunzi']}));
  add('zhuangzi','Zhuangzi: perspectives and the art of living','庄子与逍遥','Zhuāngzǐ yǔ Xiāoyáo','庄','Zhuāng',-350,-250,'eastern-zhou',true,card(
    'The Zhuangzi uses stories, humour and startling shifts of perspective to question familiar judgments. Zhuang Zhou probably flourished in the later fourth centuryBCE; the surviving book includes work by other hands. Its approximate range here concerns that early textual world, rather than one established lifetime.',
    'A story can unsettle an argument',
    'Parables about skilled activity, transformation and apparently useless things ask who decides what counts as valuable. A tree useless to a carpenter may survive precisely because it cannot be made into something profitable. Such reversals expose the limits of judgments tied to a particular purpose. The reader is invited to examine the position from which a confident verdict is being made.',
    'Freedom within a dangerous political world',
    'Suspicion of ambition and office gains force in a landscape where rulers could demand service and punish failure. Yet the text is more than a manual for withdrawal: it explores how action can become responsive, skilled and less constrained by rigid distinctions. Later readings differ sharply, which makes a single slogan such as “everything is relative” a poor substitute for its arguments.',
    'Ca. 350–250 BCE is an approximate setting for early composition and development. Authorship of individual chapters and the relation between the historical figure and the book remain debated.',[sep('zhuangzi','Zhuangzi'),iep('zhuangzi-chuang-tzu-chinese-philosopher','Zhuangzi')],{approx:true,related:['laozi','mencius','xunzi']}));
  add('xunzi','Xunzi: learning makes an ethical world','荀子与礼法','Xúnzǐ yǔ Lǐfǎ','荀','Xún',-310,-238,'eastern-zhou',false,card(
    'Xunzi was a major third-centuryBCE thinker who defended learning, ritual and deliberate cultivation. He disagreed with Mencius about how moral order relates to human nature. His precise dates are uncertain; he was still alive after his patron Lord Chunshen was killed in 238 BCE.',
    'Institutions could educate desire',
    'Unchecked desires could produce conflict over limited resources. For Xunzi, teachers and inherited practices made it possible to transform how people responded to those desires. Ritual was therefore neither empty display nor mere repression: it organized distinctions, expectations and emotions so that cooperation could become sustainable. Ethical achievement depended on acquired practice rather than simply allowing an original goodness to unfold.',
    'Nature did not guarantee political justice',
    'Xunzi treated Heaven’s regularities as distinct from the moral successes and failures of government. People had to take responsibility for their own institutions. That position supported confidence in disciplined human effort, while retaining hierarchy and reverence for accomplished predecessors. His later marginalization within some orthodox traditions should not conceal how broad the early debate over Confucius’s inheritance actually was.',
    'Ca. 310 BCE is an estimated birth date;238 BCE is a latest securely attested activity marker, not a known death year. “Human nature is bad” requires the text’s distinction between nature and cultivated achievement.',[sep('xunzi','Xunzi'),iep('xunzi','Xunzi')],{approx:true,related:['mencius','confucius','han-fei']}));
  add('han-fei','Han Fei: standards, incentives and distrust','韩非与法家','Hán Fēi yǔ Fǎjiā','法','Fǎ',-280,-233,'catalog-SR_WS',false,card(
    'Han Fei, who died in 233 BCE, wrote about the difficulty of securing a ruler’s authority over ministers and subjects. The Han Feizi connects standards, rewards, punishments and techniques of administration. Later classification placed him among the “Legalists,” a label that should not imply one organized school with a single doctrine.',
    'The ruler’s agents had interests of their own',
    'Ministers might conceal information, exaggerate achievement or turn delegated authority into personal power. Han Fei therefore sought procedures that made performance answerable to stated duties. The argument begins with distrust of dependence on exceptional personal virtue. A government should function through reproducible arrangements, rather than waiting for unusually wise rulers and perfectly loyal officials.',
    'Impersonal rules did not create constitutional government',
    'Uniform standards could undermine inherited exemptions, but their purpose was to strengthen monarchical control, not establish equal political rights. The ruler retained command over the instruments of reward and punishment. Han Fei’s sophistication lies partly in recognizing the tensions inside concentrated power: the sovereign needed capable agents while fearing the autonomy that capability gave them.',
    'Ca. 280 BCE is a conventional approximate birth date;233 BCE is his death year. The surviving collection has disputed layers. “Legalism” is a retrospective classification, not modern rule of law.',[sep('chinese-legalism','Legalism in Chinese philosophy'),wiki('Han_Fei')],{approx:true,related:['xunzi','qin','unification']}));
  add('mawangdui-manuscripts','Mawangdui: an archive beneath the earth','马王堆帛书','Mǎwángduī Bóshū','帛','Bó',-168,-168,'han',true,card(
    'A tomb at Mawangdui near Changsha, sealed in 168 BCE, preserved manuscripts on silk alongside other burial materials. Excavations in 1972–1974 revealed a remarkable early Han intellectual world. The burial date provides a firm latest date for the deposited copies, not the original composition of everything they contain.',
    'Knowledge crossed our modern subject boundaries',
    'The manuscripts include philosophical, medical and technical materials as well as maps. Placing them together challenges a history confined to a few canonical books or celebrated court thinkers. Early readers could be interested in governing, health, cosmology and bodily practice within the same collection. Such evidence reveals what one elite environment assembled, rather than a universal curriculum followed throughout the empire.',
    'Surviving copies can change an ancient classic',
    'The Laozi manuscripts differ in wording and arrangement from the later received text. Their existence makes textual transmission visible: a familiar book was once available in alternative forms. The historian must therefore distinguish the authority a later edition acquired from the variety of earlier copies. Archaeology changes the questions asked of written traditions, rather than merely supplying illustrations for an already settled story.',
    '168 BCE dates tomb 3’s closure. It is not a date for every Mawangdui tomb, every manuscript’s composition or the invention of the practices described.',[['https://web.hnmuseum.com/en/content/changsha-mawangdui-han-dynasty-tombs-exhibition','Hunan Museum · Mawangdui Han tombs'],['https://mkern.scholar.princeton.edu/document/61','Martin Kern, Princeton University · Early manuscript production']],{related:['laozi','han','nine-chapters']}));
  add('sima-qian','Sima Qian and the Records of the Grand Historian','司马迁与史记','Sīmǎ Qiān yǔ Shǐjì','史','Shǐ',-109,-90,'han',true,card(
    'Sima Qian’s Shiji brought annals, tables, institutional studies and biographies into a vast account of the past. Composed during the later second and early first centuriesBCE, its 130 chapters extend beyond rulers to merchants, advisers and people whose lives do not fit a simple narrative of imperial success.',
    'A structure that permits more than one viewpoint',
    'The same political world can look different in an emperor’s annals, an economic treatise or the biography of a defeated rival. That arrangement requires readers to connect accounts rather than accept one uninterrupted story. Chronology remains essential, but it is accompanied by questions about conduct, social position and the mechanisms through which power and wealth accumulated.',
    'History could criticize the present',
    'Scholar Vincent Leung reads the economic chapters as a critique of imperial expansion under Emperor Wu. This is an interpretation of how the work deploys the past, not a claim that every passage has one hidden political message. It reminds us that an official historian’s access to government did not necessarily make him its uncomplicated spokesman. Writing about an empire could also expose its contradictions.',
    'Ca. 109–90 BCE is a working composition range, not a precise publication schedule. The received text includes transmission problems and later additions; Sima Qian’s own dates are also uncertain.',[['https://www.loc.gov/resource/gdcwdl.wdl_17876_003/?st=brief','Library of Congress · Shiji:130 juan'],['https://www.cambridge.org/core/books/abs/politics-of-the-past-in-early-china/sima-qians-critical-past/8090D0D0F8475E7C6751B536E6DFFC4F','Vincent Leung · Sima Qian’s critical past']],{approx:true,related:['han','salt-iron-debate','catalog-E_HAN_1']}));
  add('salt-iron-debate','The debate on salt and iron','盐铁之议','Yántiě zhī Yì','盐','Yán',-81,-81,'han',false,card(
    'In 81 BCE, a court conference debated policies associated with Emperor Wu, including state monopolies on salt and iron. The later Discourses on Salt and Iron, compiled by Huan Kuan, preserves a constructed account of these exchanges. Fiscal policy appears here as an argument about the purposes and burdens of imperial government.',
    'Security had a bill attached',
    'Defenders of state economic intervention connected revenue with frontier commitments and public power. Critics emphasized hardship, damaging incentives and the moral consequences of pursuing profit. The dispute therefore joined foreign policy with everyday production and consumption. A decision about distant military obligations could change the cost of goods and the demands imposed on households within the empire.',
    'Ancient arguments resist modern party labels',
    'It is tempting to classify the speakers as advocates of capitalism or socialism. Their disagreements arose within monarchy, agrarian social ideals and elite claims to moral expertise, not modern electoral or industrial politics. Moreover, the surviving book organizes positions for readers after the conference. It is evidence of political argument and literary framing, rather than a recording in which every participant’s words can be recovered unchanged.',
    '81 BCE dates the conference. The received text was compiled later; its speeches should not be treated as verbatim minutes or the complete views of all Han officials.',[['https://www.loc.gov/resource/gdcwdl.wdl_17196_001/?sp=3&st=list','Library of Congress · Discourses on Salt and Iron'],wiki('Discourses_on_Salt_and_Iron')],{category:'event',related:['sima-qian','catalog-R_HAN_W','catalog-E_HAN_2']}));
  add('ban-zhao','Ban Zhao: scholarship and women’s education','班昭与女诫','Bān Zhāo yǔ Nǚjiè','昭','Zhāo',92,116,'han',true,card(
    'Ban Zhao helped complete the Book of Han after the death of her brother Ban Gu in 92 CE and taught within the imperial court. Her Admonitions for Women became a much-read text on conduct. Her career shows a woman exercising scholarly authority within a social order that restricted women’s roles.',
    'An argument for education inside hierarchy',
    'Ban Zhao asks why learning should be provided for boys but neglected for girls. The argument rests on women’s responsibilities within marriage and ritual order, not a demand to abolish that order. Educational opportunity and subordination can therefore appear in the same work. Recognizing the tension is more illuminating than turning her into either a modern feminist or a passive mouthpiece of patriarchy.',
    'Prescription is not a photograph of society',
    'Advice about how women ought to behave cannot demonstrate that every household behaved that way. The text reveals concerns and expectations in a particular elite setting; its later influence belongs to another history of reading and teaching. Ban Zhao’s own scholarly achievement also exposes the inadequacy of treating ancient women as a single undifferentiated category without access to knowledge or political relationships.',
    '92–ca. 116 CE marks her later scholarly career, not a precisely dated composition interval. Her birth is variously dated 45 or 49 CE; her death is approximate.',[['https://afe.easia.columbia.edu/ps/cup/banzhao_admonitions.pdf','Columbia University · Ban Zhao, translated primary-source excerpts'],['https://historyofwomenphilosophers.org/project/directory-of-women-philosophers/zhao-ban-45-ca-116/','History of Women Philosophers and Scientists · Ban Zhao']],{approx:true,related:['catalog-R_HAN_E','sima-qian','catalog-E_HAN_1']}));
  add('zhang-heng','Zhang Heng and the earthquake detector','张衡与地动仪','Zhāng Héng yǔ Dìdòngyí','衡','Héng',132,132,'han',true,card(
    'In 132 CE, Zhang Heng presented a device intended to indicate the direction of a distant earthquake. He also worked in astronomy, mathematics and literature. His combination of interests belonged to a courtly world in which understanding natural phenomena had administrative and political significance.',
    'Observation mattered to government',
    'Earthquakes could signal disaster in distant regions and could also be interpreted as warnings about the quality of rule. A device that registered otherwise unfelt events promised a way to extend knowledge beyond immediate experience. Its importance therefore involved both technical ingenuity and the court’s relationship with a wider realm. Ancient scientific work need not be detached from cosmology to involve serious observation.',
    'The surviving account has limits',
    'No original instrument survives. Modern models reconstruct a mechanism from descriptions that do not settle every engineering detail. The device is better described as a seismoscope than a modern seismograph: it reportedly indicated an occurrence and direction, rather than recording a continuous trace or calculating a magnitude. Nor was it an earthquake predictor. Those distinctions preserve the achievement without replacing it with capabilities unsupported by evidence.',
    '132 CE is the traditional presentation date. The original mechanism and the precision of reported performance remain debated; modern reconstructions are not surviving Han machines.',[['https://mathshistory.st-andrews.ac.uk/Biographies/Zhang_Heng/','University of St Andrews, MacTutor · Zhang Heng'],wiki('Zhang_Heng')],{category:'event',related:['catalog-R_HAN_E','nine-chapters','paper']}));
  add('nine-chapters','Nine Chapters: mathematics for a working world','九章算术','Jiǔzhāng Suànshù','算','Suàn',-100,100,'han',false,card(
    'The Nine Chapters on the Mathematical Art assembled problems and procedures concerning areas, quantities, distribution, engineering and calculation. Its formation extended across generations; an approximate Han range is shown here rather than an invented publication year. Later commentary, especially Liu Hui’s in 263 CE, became integral to its transmission.',
    'Practical problems could carry general methods',
    'Surveying land or dividing resources required more than isolated numerical answers. Procedures could be applied to new cases, making the work a means of teaching transferable mathematical reasoning. Its organization connects abstraction with situations recognizable to administrators and producers. The presence of concrete settings does not make the mathematical work merely mechanical or intellectually unsophisticated.',
    'Different forms of explanation deserve attention',
    'Older comparisons sometimes judged Chinese mathematics by how closely it resembled the arrangement of Greek geometry. That approach can miss the reasoning expressed through procedures and their explanations. Historians now examine how problems, operations and commentaries worked together. The important distinction is between understanding a tradition’s own methods and ranking civilizations by a single inherited definition of what mathematics ought to look like.',
    'Ca. 100 BCE–100 CE is an approximate formation range; constituent material may be earlier. Liu Hui’s 263 CE commentary is a later layer, not evidence that he authored the entire original collection.',[['https://mathshistory.st-andrews.ac.uk/HistTopics/Nine_chapters/','University of St Andrews, MacTutor · Nine Chapters'],wiki('The_Nine_Chapters_on_the_Mathematical_Art')],{approx:true,related:['zhang-heng','mawangdui-manuscripts','han']}));
  return {events,revisions,pinyin};
})();
if(typeof module!=='undefined')module.exports=EARLY_RESEARCH;
