/* Reusable maps: captions distinguish composite geography from dated reconstructions. */
const HISTORY_MAPS = (() => {
 const canal={title:'The Grand Canal and China’s river regions',src:'https://upload.wikimedia.org/wikipedia/commons/e/ee/Grand-Canal.png',source:'https://commons.wikimedia.org/wiki/File:Grand-Canal.png',credit:'Groverlynn · 2016',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',caption:'Older and later canal courses connect the Yellow River and Yangtze regions. This composite map explains transport geography; it is not a map of a single year or of migration routes.'};
 const buddhism={title:'Buddhism’s connections across Asia',src:'https://upload.wikimedia.org/wikipedia/commons/8/8e/Buddhist_Expansion.svg',source:'https://commons.wikimedia.org/wiki/File:Buddhist_Expansion.svg',credit:'Gunawan Kartapranata · 2014',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',caption:'A schematic overview spanning many centuries. Arrows show broad connections, not exact journeys or a single arrival date. The map locates the regions discussed in the card but cannot reconstruct individual routes.'};
 const song={title:'Song, Liao and Western Xia in 1111',src:'https://upload.wikimedia.org/wikipedia/commons/b/ba/Song-Liao-Xixia-1111.png',source:'https://commons.wikimedia.org/wiki/File:Song-Liao-Xixia-1111.png',credit:'Douglasfrankfort and Wikimedia Commons contributors',license:'CC BY 3.0',licenseUrl:'https://creativecommons.org/licenses/by/3.0/',caption:'A later reconstruction of coexistence in 1111, more than a century after the Chanyuan agreement. It does not show the treaty’s boundaries in 1005.'};
 const xuanzang={title:'Xuanzang’s journey to Nalanda and return to China',src:'https://ancient-buddhist-texts.net/Maps/Silk-Routes/Chinese-Pilgrim-Xuanzang.jpg',source:'https://ancient-buddhist-texts.net/Maps/Silk-Routes/Chinese-Pilgrims.htm',credit:'Ānandajoti Bhikkhu · Ancient Buddhist Texts',license:'CC BY-SA 3.0',licenseUrl:'https://ancient-buddhist-texts.net/Miscellaneous/Copyright-Notice.htm',caption:'An indicative reconstruction of Xuanzang’s travels, 629–645. Red marks the outward journey and blue the return. Nalanda is marked in northern India. The map places his studies within journeys through Central and South Asia; it is not a complete or exact itinerary.'};
 const tang={title:'Tang administration and protectorates in 661',src:'https://upload.wikimedia.org/wikipedia/commons/9/9f/Tang_outline_map%2C_661.svg',source:'https://commons.wikimedia.org/wiki/File:Tang_outline_map,_661.svg',credit:'Kanguole · 2023',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',caption:'A reconstruction for 661, based on maps in The Cambridge History of China and Cultural Atlas of China. Dark red shows civil administration; the middle shade shows Anxi military administration; pale red shows briefly controlled protectorates. These areas were not uniformly or permanently governed. This is not a map of the later An Lushan Rebellion.'};
 const voyages={title:'Zheng He’s seventh voyage, 1431–1433',src:'https://upload.wikimedia.org/wikipedia/commons/8/81/Zheng-He-7th-expedition-map.svg',source:'https://commons.wikimedia.org/wiki/File:Zheng-He-7th-expedition-map.svg',credit:'Vmenkov · base map by Historicair',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',caption:'This map depicts the seventh voyage (1431–1433), not the first departure in 1405. The solid line traces the main fleet to Hormuz. Dashed lines reconstruct possible routes of Hong Bao’s detached squadron; dotted lines indicate a smaller party’s journey to Mecca and Medina, not Zheng He’s own travels. Red dots mark voyage ports; green dots mark biographical locations. Based on Edward L. Dreyer’s study.'};
 const kingdoms={title:'Three Kingdoms in 262',src:'https://upload.wikimedia.org/wikipedia/commons/7/7b/Three_Kingdoms.png',source:'https://commons.wikimedia.org/wiki/File:Three_Kingdoms.png',credit:'SY (Seasonsinthesun) · Wikimedia Commons',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',caption:'A modern reconstruction of Wei, Shu Han and Wu in 262, just before Shu Han’s conquest. Stars mark capitals. This dated snapshot helps locate the rival states; it does not represent fixed borders throughout the entire Three Kingdoms period.'};
 const jin={title:'Western Jin in 280',src:'https://upload.wikimedia.org/wikipedia/commons/3/37/Jin_occidentaux_280.svg',source:'https://commons.wikimedia.org/wiki/File:Jin_occidentaux_280.svg',credit:'Zunkir · 2016',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',caption:'A modern reconstruction of Western Jin provinces around 280, the year Jin conquered Wu and ended the Three Kingdoms division. The map shows the empire at reunification; its territory and internal divisions changed during the decades that followed.'};
 const fiveDynasties={title:'Five Dynasties and Ten Kingdoms, 907–960',src:'https://upload.wikimedia.org/wikipedia/commons/c/c9/The_Five_Dynasties_907-960_AD.jpg',source:'https://commons.wikimedia.org/wiki/File:The_Five_Dynasties_907-960_AD.jpg',credit:'Albert Herrmann and Georg Westermann · 1935',license:'Public domain',licenseUrl:'https://creativecommons.org/publicdomain/mark/1.0/',caption:'Four panels show the five northern dynasties from 907 to 960. The third panel combines Later Jin and Later Han because both were short-lived. The Ten Kingdoms began and ended at different times. Most lay south of the northern dynasties, while Northern Han was in the north. The map stops at Song’s founding in 960; reunification campaigns continued until 979.'};
 const warring={title:'Warring States around 350 BCE',src:'https://upload.wikimedia.org/wikipedia/commons/d/d6/%E6%88%98%E5%9B%BD%E5%BD%A2%E5%8A%BF%E5%9B%BE%EF%BC%88%E5%89%8D350%E5%B9%B4%EF%BC%89%EF%BC%88%E7%AE%80%EF%BC%89.png',source:'https://commons.wikimedia.org/wiki/File:战国形势图（前350年）（简）.png',credit:'玖巧仔 (Jiu Qiaozai)',license:'CC BY-SA 3.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',caption:'A reconstruction around 350 BCE, based on Chinese historical atlases and administrative history. Boxed names identify Qin (秦), Chu (楚), Qi (齐), Yan (燕), Han (韩), Zhao (赵) and Wei (魏). Red squares mark capitals; white dots mark counties or fiefs. This is an earlier political landscape, not Qin’s unification in 221 BCE.'};
 const dadu={title:'Plan of Yuan Dadu (元大都)',src:'https://upload.wikimedia.org/wikipedia/commons/0/0a/Dadu_Map.jpg',source:'https://commons.wikimedia.org/wiki/File:Dadu_Map.jpg',credit:'Bairuilong · cropped version uploaded by Zomba2022wataru',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',caption:'A modern plan of Yuan Dadu: the outer walled city appears in yellow, with the imperial city in orange and the palace enclosure within it. Streets and waterways show how the capital was organized. This is a reconstruction of Yuan Dadu, not a contemporary Yuan map or a plan of later Ming–Qing Beijing.'};
 return {'catalog-C_BEIJING_YUAN':dadu,'catalog-SR_WS':warring,'zheng-he':voyages,'three-kingdoms':kingdoms,'jin-early':jin,'five-dynasties':fiveDynasties,'xuanzang-return':xuanzang,'tang':tang,'southward-economic-shift':canal,'sui-grand-canal':canal,'catalog-E_BUD_ENTRY':buddhism,'chanyuan':song,'song':song};
})();
