// Medieval political diversity is treated as history in its own right.
const MEDIEVAL_RESEARCH = (() => {
  const refs={
    kingdoms:['https://www.chinaknowledge.de/History/Division/sanguo-event.html','Ulrich Theobald · Three Kingdoms political history'],
    military:['https://www.chinaknowledge.de/History/Division/sanguo-military.html','Ulrich Theobald · Three Kingdoms military organization'],
    admin:['https://www.chinaknowledge.de/History/Division/sanguo-admin.html','Ulrich Theobald · Three Kingdoms administration'],
    caocao:['https://www.chinaknowledge.de/History/Division/personscaocao.html','Ulrich Theobald · Cao Cao'],
    wei:['https://www.chinaknowledge.de/History/Division/caowei.html','Ulrich Theobald · Cao Wei'],
    shu:['https://www.chinaknowledge.de/History/Division/personszhugeliang.html','Ulrich Theobald · Zhuge Liang'],
    wu:['https://www.chinaknowledge.de/History/Division/wu.html','Ulrich Theobald · Sun Wu'],
    jin:['https://www.cambridge.org/core/books/cambridge-history-of-china/western-jin/C26640110C74E0B6FA215625AFBBA6B7','Cambridge History of China · Western Jin'],
    eastjin:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/eastern-jin/26B36E30FF9DDF420EE4B53D3D3E1752','Cambridge History of China · Eastern Jin'],
    literature:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/from-the-eastern-jin-through-the-early-tang-317649/B5376D99557121DA452CD26E4A03B9BA','Cambridge History of China · Literature, 317–649'],
    jinecon:['https://www.chinaknowledge.de/History/Division/jin-econ.html','Ulrich Theobald · Jin economy'],
    sixteen:['https://www.cambridge.org/core/books/cambridge-history-of-china/sixteen-kingdoms/EFA116423191EA9A0895B1BCEDD6B063','Charles Holcombe · Sixteen Kingdoms'],
    hanzao:['https://www.chinaknowledge.de/History/Division/rulers-qianzhao.html','Ulrich Theobald · Han Zhao rulers'],
    spells:['https://journals.ub.uni-heidelberg.de/index.php/jiabs/article/download/8958/2851/0','Richard McBride · Dhāraṇī and spells in medieval Buddhism'],
    palumbo:['https://agamaresearch.dila.edu.tw/wp-content/uploads/2025/12/Palumbo-2013.pdf','Antonello Palumbo · Early Chinese Buddhist translation and patronage'],
    xianbei:['https://www.chinaknowledge.de/History/Altera/xianbei.html','Ulrich Theobald · Xianbei'],
    formerqin:['https://en.wikipedia.org/wiki/Former_Qin','Former Qin · Overview and bibliography'],
    laterqin:['https://en.wikipedia.org/wiki/Later_Qin','Later Qin · Overview and bibliography'],
    kumara:['https://en.wikipedia.org/wiki/Kum%C4%81raj%C4%ABva','Kumarajiva · Translation history and bibliography'],
    south:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/southern-dynasties/73046E25FE5260872C600D4E325DF02B','Cambridge History of China · Southern dynasties'],
    songwen:['https://www.chinaknowledge.de/History/Division/personssongwendi.html','Ulrich Theobald · Liu Song emperor Wen'],
    nanqi:['https://www.chinaknowledge.de/History/Division/nanqi.html','Ulrich Theobald · Southern Qi'],
    liang:['https://www.chinaknowledge.de/History/Division/liang.html','Ulrich Theobald · Liang'],
    liangwu:['https://www.chinaknowledge.de/History/Division/personsliangwudi.html','Ulrich Theobald · Liang emperor Wu'],
    chen:['https://www.chinaknowledge.de/History/Division/chen.html','Ulrich Theobald · Chen'],
    beiwei:['https://www.chinaknowledge.de/History/Division/beiwei.html','Ulrich Theobald · Northern Wei'],
    'yungang':['https://whc.unesco.org/en/list/1039/','UNESCO · Yungang Grottoes'],
    eastwei:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/eastern-weinorthern-qi/ACA9DFF6C8EF6DC0B5CB7E89BEF2836E','Albert Dien · Eastern Wei and Northern Qi'],
    westwei:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/western-weinorthern-zhou/0E0549FA8294B31DEEA95BB796244EFA','Albert Dien · Western Wei and Northern Zhou'],
    lou:['https://www.cambridge.org/core/journals/journal-of-chinese-history/article/empress-dowager-lou-the-kingmaker-succession-marriage-identity-and-politics-in-northern-qi-550577/6F3EC16A5AEA78AF2FC390E2779A6DF4','Soojung Han · Empress Dowager Lou and Northern Qi'],
    graff:['https://www.cambridge.org/core/journals/journal-of-chinese-history/article/reach-of-the-military-tang/ECFE9C64AE6E73EC4319B165A606F88C','David Graff · The Reach of the Military: Tang'],
    five:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/five-dynasties/BED8234EA917268392A83E07FFE08EE7','Naomi Standen · Five Dynasties'],
    davis:['https://www.jstor.org/stable/10.7312/davi12826','Ouyang Xiu / Richard Davis · Historical Records of the Five Dynasties'],
    lorge:['https://assets.cambridge.org/97811070/84759/excerpt/9781107084759_excerpt.pdf','Peter Lorge · The Reunification of China: excerpt'],
    ten:['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/southern-kingdoms-between-the-tang-and-the-sung-907979/DA46EC4F957DC57884D32C133A9883C8','Hugh Clark · Southern kingdoms between Tang and Song'],
    table:['https://assets.cambridge.org/97805218/12481/excerpt/9780521812481_excerpt.pdf','Cambridge History of China · Tenth-century chronology'],
    kurz:['https://fass.ubd.edu.bn/staff/docs/JK/han-xizai.pdf','Johannes Kurz · Han Xizai and Southern Tang'],
    palaceNight:['https://www.dpm.org.cn/collection/paint/228200.html','Palace Museum · Night Revels of Han Xizai'],
    tangpop:['https://www.cuhk.edu.hk/ics/journal/articles/v19p389.pdf','Hans Bielenstein · The Population of T’ang China'],
    worldpop:['https://www.census.gov/data/tables/time-series/demo/international-programs/historical-est-worldpop.html','United States Census Bureau · Historical estimates of world population'],
    shu2:['https://www.cambriapress.com/pub.cfm?bid=462','Hongjie Wang · Power and Politics in Tenth-Century China'],
    brose:['https://doi.org/10.21313/hawaii/9780824853815.003.0005','Benjamin Brose · Buddhist institutions in Wuyue'],
    tea:['https://www.ocha-festival.jp/archive/english/conference/ICOS2001/files/PROC/I-015.pdf','International Conference on O-CHA · Tea trade in the tenth century'],
    coins:['https://www11.ihp.sinica.edu.tw/storage/w2_file/1479vPLumrx.pdf','Academia Sinica · Southern Han coinage and maritime evidence']
  };
  const revisions={};
  function c(id,description,a,b,d,e,keys,note,extra={}){
    const rr=keys.map(k=>refs[k]);
    revisions[id]={description,sections:[{title:a,text:b},{title:d,text:e}],sources:rr.map(x=>x[0]),sourceLabels:Object.fromEntries(rr),evidence:'Source-checked synthesis',note,...extra};
  }
  c('division','Between Han and Sui, competing courts ruled different parts of China. War and migration changed regional societies, while aristocratic lineages, religious institutions and administrative practices crossed political boundaries. “Age of division” is an editorial description of this plurality, not the name of a government.',
    'Continuity did not require unity','Successor states recruited officials and used institutions inherited from earlier governments. Their rulers disputed who could claim imperial authority rather than simply abandoning the idea of empire. A map of political fragmentation therefore does not imply that administration, scholarship or exchange stopped at every boundary.',
    'Regions developed their own centres','Migration helped reshape the lower Yangtze, while northern courts sustained military and religious connections with Inner Asia. These regional histories deserve attention on their own terms. Treating the period only as preparation for reunification makes cultural and institutional choices look inevitable when contemporaries faced several possible political futures.',
    ['literature','admin'],'220–581 is the overview frame; Sui’s conquest of the southern Chen occurred in 589.',{related:['three-kingdoms','sixteen','north-south','sui']});
  c('three-kingdoms','Wei, Shu and Wu emerged from the collapse of Han power. Their courts made competing claims to legitimate succession while governing unequal territories and resource bases. The formal division followed decades of military consolidation rather than beginning suddenly in 220.',
    'Three claims to one inheritance','Rulers used Han institutions, personnel and political language even as they fought one another. Shu’s restoration claim differed from Wei’s transfer of the imperial title, while Wu developed its own southern court. These were competing state projects, not three enduring national identities projected backwards from modern geography.',
    'Resources constrained strategy','Campaigns required dependable food, transport and manpower. River systems, agricultural settlements and relationships with local elites helped determine what armies could sustain. Later literary stories make individual cunning vivid; institutional and economic history explains why even talented commanders faced limits they could not overcome through strategy alone.',
    ['kingdoms','military'],'220–280 is the conventional dynastic frame. Wu’s imperial proclamation came in 229, although its separate kingship is often dated 222.');
  c('catalog-E_3K_1','Cao Pi accepted the Han emperor’s abdication in 220 and established Wei. The formal transfer concluded a long erosion of imperial control. Cao Cao had already built a powerful military government while retaining the Han emperor and ruling in his name.',
    'Title and power moved at different speeds','Possessing the emperor could authorize appointments and campaigns without immediately replacing the dynasty. Abdication converted practical supremacy into a claim of lawful succession. The ritual mattered because military victory alone did not make a new regime’s legitimacy self-evident to officials or rival leaders.',
    'The end was also a beginning','Shu and Wu answered the transfer with competing arrangements and claims. Han’s institutional legacy consequently became a resource used by several successors rather than disappearing with its last emperor. The event marks a legal and ideological change inside a political fragmentation that had already advanced much further on the ground.',
    ['kingdoms','caocao'],'220 dates the formal end of Han; the breakdown of effective central rule began earlier.',{related:['han','three-kingdoms','catalog-R_WEI']});
  c('catalog-R_WEI','Cao Wei controlled much of northern China after Cao Pi’s accession in 220. Its rulers inherited Cao Cao’s military and agricultural organization. The Sima family gradually displaced Cao authority before formally founding Jin in 266.',
    'Food made military power durable','Agricultural colonies supplied soldiers and helped organize displaced people and land. Such arrangements reveal how closely the work of cultivation and the demands of war could be joined. A large territory became useful to a court only when revenue and provisions could be collected and moved reliably.',
    'An office could become a route to succession','The secretariat, military commands and regency provided positions from which powerful families could accumulate authority. Wei’s eventual replacement therefore was not simply defeat by an external enemy. Its own institutions supplied the resources and political language through which a successor coalition could claim control.',
    ['wei','admin'],'220–265 follows the inherited convention for Wei; the Jin accession falls in 266 in common Gregorian chronologies.',{related:['three-kingdoms','jin-early']});
  c('catalog-R_SHU','Liu Bei’s court in Sichuan claimed to restore Han legitimacy. Zhuge Liang helped administer the state and directed campaigns against Wei. Shu’s restricted resource base and the difficulty of northern campaigning constrained its ambition; Wei conquered it in 263.',
    'A restoration claim needed material support','Invoking the Han line could attract allegiance but could not remove the costs of mobilizing a smaller population. Sichuan offered productive land and defensible approaches, yet sending armies beyond that base required difficult supply arrangements. Geography protected the state while limiting the scale of sustained expansion.',
    'The historical official and the literary sage','Zhuge Liang’s later reputation in drama and fiction magnified foresight and personal ingenuity. His historical significance also rests on administration, recruitment and the maintenance of a fragile regime. Distinguishing those levels does not diminish his importance; it explains how public memory converted statecraft into an ideal of exemplary service.',
    ['shu','military'],'221–263 dates Shu Han as an imperial court. Literary portrayals are later interpretations, not direct transcripts of campaigns.',{related:['three-kingdoms','catalog-R_WEI']});
  c('catalog-R_WU','The Sun family built an enduring state in the lower Yangtze. Sun Quan’s kingship in 222 preceded his imperial proclamation in 229. Wu survived both Shu and Wei before Jin conquered it in 280.',
    'Southern rule depended on negotiated alliances','Military leaders needed powerful local families whose estates and followers supplied resources. Marriage, office and other arrangements bound these interests to the court without eliminating their independent influence. The resulting government was a coalition with tensions, not simply an emperor extending uniform command over an empty southern frontier.',
    'Development also involved coercion','Expansion into hill regions drew communities into taxation and military service. What a state’s records present as pacification or productive development could mean forced incorporation for those affected. Holding these perspectives together prevents southern economic growth from becoming a story that leaves the people bearing its costs invisible.',
    ['wu','military'],'222 marks kingship; 229 marks the imperial title. Both conventions describe stages of a longer consolidation.',{related:['three-kingdoms','jin-early']});
  c('jin-early','The Jin dynasty founded by the Sima family reunited the main successor states in 280. Court conflict and northern upheaval fractured that achievement. A Jin court continued in the south until 420, making the dynasty’s history much longer than its brief period of broad unification.',
    'Unity did not resolve succession','Granting imperial relatives military and regional authority could appear to secure a ruling house. In a contested succession it also supplied rivals with independent resources. The relationship between family protection and political fragmentation helps explain why a successful conquest could be followed by destructive struggles within the dynasty.',
    'Restoration required a new coalition','The southern court inherited the Jin name, but depended on émigré families and established local interests under changed conditions. Institutional continuity was therefore negotiated rather than automatic. The distinction between Western and Eastern Jin captures a transformation in the social and territorial foundations of government, not merely a change of address.',
    ['jin','eastjin'],'266–420 includes Western and Eastern Jin; reunification in 280 did not last throughout the dynasty.',{related:['catalog-R_JIN_W','catalog-R_JIN_EASTERN_JIN','sixteen']});
  c('catalog-R_JIN_W','Western Jin followed the Sima family’s long ascendancy within Wei. Its conquest of Wu in 280 briefly ended the Three Kingdoms division. Rivalries among imperial princes and other military powers later destabilized the court, which lost Luoyang and then Chang’an.',
    'A dynasty built within another government','The Sima takeover unfolded through officeholding and command before the imperial title changed. That history demonstrates why a founding date cannot by itself explain state formation. The new rulers inherited both the administrative resources and the unresolved relationships of the government they displaced.',
    'Land, service and the reach of the court','Changes in agricultural settlements and elite landholding affected the relationship between households and government. The ability to command labour or military service depended on registration and intermediaries. Political collapse should therefore be examined alongside these social arrangements rather than attributed solely to the character of individual princes.',
    ['jin','jinecon'],'266–316 dates Western Jin. Luoyang fell in 311; the final western court at Chang’an fell in 316.',{related:['jin-early','catalog-E_JIN_1']});
  c('catalog-E_JIN_1','The capture of Chang’an in 316 ended the remaining Western Jin court. Luoyang had already fallen in 311. These successive defeats drove political displacement and helped transform northern and southern centres of power.',
    'There was no single moment of collapse','Different cities, armies and communities experienced the breakdown on different timetables. A dynasty’s formal endpoint compresses that sequence into a convenient date. Restoring the sequence distinguishes the destruction of a court from the longer loss of effective control over territory and resources.',
    'The name survived through reconstruction','Sima Rui’s southern regime preserved the Jin title, but had to establish relationships with displaced elites and local families. Continuity rested on their cooperation as well as ancestry. The event is thus both an endpoint for Western Jin and part of the creation of a different political society in the Yangtze region.',
    ['jin','eastjin'],'316 is the end of Western Jin, not all Jin rule. Ancient descriptions of devastation are not reliable modern demographic totals.',{name:'Western Jin loses Chang’an',related:['jin-early','catalog-R_JIN_EASTERN_JIN']});
  c('catalog-R_JIN_EASTERN_JIN','A Jin court was re-established south of the Yangtze under Sima Rui. Northern émigré families and established southern elites shaped its government. Jiankang became a political and cultural centre while northern recovery remained an aspiration pursued unevenly.',
    'The court governed through powerful families','Lineage prestige, office and military resources were distributed among groups whose cooperation the emperor needed. This did not make the state unreal, but it limited how directly a ruler could command. Describing the period as aristocratic government is useful only if the competing interests within that aristocracy remain visible.',
    'Migration remade culture as well as politics','Movements of people and texts helped create new intellectual and artistic settings in the south. Literary achievement developed within these material and social conditions. Cultural history consequently belongs inside the story of displacement and coalition building, rather than serving as decoration around a supposedly unimportant political interval.',
    ['eastjin','literature'],'317 marks Sima Rui’s kingship and southern restoration; his imperial accession followed in 318.',{related:['jin-early','north-south']});
  c('sixteen','The label Sixteen Kingdoms groups a larger and changing set of northern and western regimes between the Jin breakdown and Northern Wei consolidation. They were neither all simultaneous nor uniform in size, organization or relations with imperial tradition.',
    'Ethnicity does not explain the whole state','Founders associated with different communities adopted imperial titles, recruited officials and governed mixed populations. An ethnic label is not a complete account of how a court ruled. Military coalitions, inherited institutions and religious patronage often explain more than a simple opposition between Chinese and non-Chinese power.',
    'A retrospective count simplifies plurality','Later historical classification selected a manageable set of regimes from a more complicated field. The number is therefore a guide to historiography, not a census of governments existing at one moment. Reading individual courts restores the distinct possibilities that disappear when the period is treated only as disorder before reunification.',
    ['sixteen','xianbei'],'304–439 is a conventional framework. More than sixteen significant regimes can be identified depending on the criteria.',{related:['catalog-R_SIXTEEN_HAN_ZHAO_FORMER_ZHAO','catalog-R_SIXTEEN_LATER_QIN','catalog-R_NS_NORTHERN_WEI']});
  c('catalog-R_SIXTEEN_HAN_ZHAO_FORMER_ZHAO','Liu Yuan established a regime using the Han name in 304. Later rulers and a Zhao designation mark changes within the polity conventionally grouped as Han Zhao or Former Zhao. It competed for imperial authority amid the destruction of Western Jin power.',
    'Ancestry and succession were political resources','The adoption of Han language and lineage claims placed the new court within an existing vocabulary of legitimate empire. It was not simply a rejection of every inherited institution. Such claims sought cooperation from constituencies beyond the founder’s original following and made the past an instrument of present rule.',
    'Names can conceal internal change','A single timeline band joins phases with different rulers, capitals and territorial circumstances. The distinction from Later Zhao is especially important because similar names do not indicate a single dynasty. Tracking these changes shows the instability of military coalitions while avoiding the misleading impression that all northern regimes were interchangeable.',
    ['hanzao','sixteen'],'304–329 follows the conventional combined Han Zhao chronology. Detailed ruler tables differ; this card avoids treating every reign-year entry as settled.',{related:['sixteen','catalog-R_SIXTEEN_LATER_ZHAO']});
  c('catalog-R_SIXTEEN_LATER_ZHAO','Shi Le and his successors built Later Zhao into a major northern power. Their court’s connections with the Buddhist monk Fotudeng helped establish an important relationship between political authority and religious institutions.',
    'Religious expertise could open the court','Biographical accounts credit Fotudeng with ritual powers and influence over rulers. These stories reveal expectations about protection and legitimate authority, even where miracles cannot be independently verified. Buddhist prominence was built through patronage and personal access as well as the movement of doctrines and texts.',
    'A military regime could have a cultural afterlife','The state’s short political life did not confine the consequences of the institutions it supported. Monks, disciples and stories could circulate beyond the regime’s borders and survive its defeat. This is one reason dynastic duration is a poor measure of cultural influence in an era of frequent political replacement.',
    ['spells','palumbo'],'319–351 is the inherited dynastic frame. Accounts of supernatural acts are evidence of religious biography, not independently established events.',{related:['sixteen','catalog-E_BUD_SPREAD']});
  c('catalog-R_SIXTEEN_FORMER_YAN','The Murong-led Former Yan regime grew from a northeastern base into a major contender in northern China. Its rulers combined military expansion with titles and recognition connecting them to the wider imperial political world.',
    'Sovereignty could be built in stages','Princely and imperial claims did not always begin together. Recognition from another court could offer useful legitimacy before more ambitious claims became practical. The state’s development therefore illustrates how diplomacy and titulature could support expansion rather than merely describing a fixed status already achieved by force.',
    'The frontier was a political centre','Calling the northeast peripheral assumes the perspective of a particular capital. For the Murong coalition it was the base from which resources, alliances and power were organized. Reversing the viewpoint makes the regime intelligible as a state project, rather than simply an intrusion into someone else’s history.',
    ['xianbei','sixteen'],'337 marks the princely foundation convention; an imperial title followed later. The regime ended in 370.',{related:['sixteen','catalog-R_SIXTEEN_FORMER_QIN']});
  c('catalog-R_SIXTEEN_FORMER_QIN','Former Qin under Fu Jian brought much of northern China under one rule before its defeat by Eastern Jin at the Fei River in 383. The dynasty continued after that battle, but its enlarged political coalition rapidly fragmented.',
    'Conquest was easier than integration','Military success brought diverse populations and commanders under a common ruler without necessarily creating durable shared interests. A severe defeat could expose those unresolved relationships. The state’s reversal demonstrates why maps showing a maximum territorial extent should not be mistaken for evidence of equally secure control throughout that territory.',
    'A battle can become too complete an explanation','The Fei River story is often told through dramatic tactics and enormous army totals. Those accounts can obscure the political conditions that made defeat so destabilizing. The more useful question is why commanders and communities could pursue different futures once the central coalition’s capacity to reward or compel them weakened.',
    ['formerqin','sixteen'],'351–394 dates the regime; 383 is a turning point, not its formal endpoint. Exact army strengths in traditional accounts are uncertain.',{related:['sixteen','catalog-R_JIN_EASTERN_JIN','catalog-R_SIXTEEN_LATER_QIN']});
  c('catalog-R_SIXTEEN_LATER_QIN','Later Qin ruled from Chang’an under the Yao family. Yao Xing’s patronage enabled Kumarajiva and collaborators to conduct influential Buddhist translation work after the monk’s arrival in 401. The state ended in 417, but the texts had a much longer history.',
    'Translation was organized labour','Rendering Buddhist works into Chinese required discussion, interpretation and collaboration, not a solitary scholar replacing words mechanically. A court could supply the conditions for that work through resources and protection. Intellectual transmission therefore depended in part on institutions created by rulers whose own political position remained insecure.',
    'The text outlasted the patron','Later readers encountered the translations in contexts very different from their original courtly setting. Cultural transmission does not fit neatly inside a dynasty’s chronological band. The example joins political and religious history while showing why the collapse of one sponsoring state need not terminate the influence of what it helped produce.',
    ['laterqin','kumara'],'384–417 dates Later Qin. Traditional translation totals and attributions require caution; this card does not treat every attributed work as certainly his.',{related:['sixteen','catalog-E_BUD_SPREAD']});
  c('north-south','From 420, a succession of southern dynasties coexisted with northern courts. Both regions developed political institutions and cultural centres. Their histories were connected by migration, diplomacy and war without being reducible to one government waiting to be restored.',
    'The south had its own political logic','Jiankang’s courts depended on military commanders, elite families and resources of the Yangtze world. Their legitimacy and ambitions cannot be understood only by measuring failed northern conquests. Attention to their internal society restores achievements and conflicts obscured by a narrative centred exclusively on eventual reunification.',
    'Northern change was also institutional','Northern rulers experimented with registration, land arrangements, military organization and religious patronage. These practices helped shape later governments, but did not develop according to a single plan leading inevitably to Sui. Comparison reveals several competing solutions to the problem of ruling diverse populations after the collapse of earlier imperial structures.',
    ['south','westwei'],'420–589 marks the conventional Southern and Northern Dynasties frame. Northern Wei began earlier, in 386.',{related:['catalog-R_NS_LIU_SONG','catalog-R_NS_NORTHERN_WEI','reunification']});
  c('catalog-R_NS_LIU_SONG','Liu Yu converted a successful military career into the founding of Liu Song in 420. The dynasty governed from Jiankang. Emperor Wen’s reign (424–453) sought administrative recovery after the founding wars, and later succession conflicts repeatedly disrupted the court.',
    'Military achievement could create a dynasty','A commander able to defend or extend an existing state could accumulate the resources to replace its ruling house. Abdication ritual gave that transformation a language of lawful succession. The pattern shows how dynastic change could emerge from service within a government rather than invasion by an entirely separate political community.',
    'A reign is not a whole dynasty','In 450, Northern Wei forces reached Guabu near the Yangzi. The costs of war pressed directly on the fiscal system: Wen cut officials’ salaries by one-third and imposed levies on wealthy households and Buddhist clergy. The burden therefore fell beyond the battlefield, making the relationship between military defence, elite privilege and public revenue a central question of his reign. The court’s survival depended on managing imperial relatives, commanders and elite cooperation, relationships that could change sharply at each succession.',
    ['songwen','south'],'420–479 dates Liu Song, distinct from the much later Song dynasty founded in 960.',{related:['north-south','catalog-R_NS_SOUTHERN_QI']});
  c('catalog-R_NS_SOUTHERN_QI','Xiao Daocheng founded Southern Qi in 479. The court faced practical problems of supervising princely governors and maintaining household registers, through which people and resources became available to government.',
    'Registration was a political struggle','A household omitted from a register could mean lost revenue or labour for the state and greater autonomy for an intermediary. Administrative records were consequently a contested claim over people, not neutral paperwork. The struggle helps explain how the power of local families affected the reach of a court that formally asserted sovereignty over them.',
    'The ruler needed eyes beyond the palace','Household document officials helped supervise princely establishments, illustrating attempts to control relatives entrusted with regional authority. Such arrangements could limit one danger while creating another source of influence. Institutional history makes these short dynasties more than a sequence of rulers by identifying the recurring problems their governments tried to solve.',
    ['nanqi','south'],'479–502 dates Southern Qi; it should not be confused with Northern Qi, founded in 550.',{related:['north-south','catalog-R_NS_LIANG']});
  c('catalog-R_NS_LIANG','Xiao Yan founded Liang in 502 and supported a prominent Buddhist and scholarly court. The acceptance of the defecting commander Hou Jing brought a dangerous military actor into southern politics; his capture of Jiankang in 549 devastated the court’s authority.',
    'Patronage was part of government','Support for religious and literary institutions helped an emperor present moral and cultural leadership. It also connected the court to communities and resources beyond its immediate administration. Liang’s Buddhist prominence should therefore be studied as a political relationship as well as an expression of personal devotion.',
    'A defector changed the balance of risk','Receiving a northern commander promised strategic advantage but brought forces and ambitions the court could not fully control. The catastrophe was not adequately explained by blaming religion or luxury. It reveals the hazards of a political system dependent on military coalitions whose loyalty could change faster than their resources could be restrained.',
    ['liang','liangwu'],'502–557 dates the principal Liang dynasty. A smaller Western/Later Liang court at Jiangling survived until 587.',{related:['north-south','catalog-R_NS_CHEN','catalog-E_BUD_SPREAD']});
  c('catalog-R_NS_CHEN','Chen Baxian founded the last southern dynasty in 557 after years of devastation and fragmented military authority. Chen governed a reduced southern domain before its conquest by Sui in 589.',
    'Reconstruction was an achievement','The court had to rebuild effective rule in a landscape damaged by earlier warfare. Its limited territorial scale should not make that work invisible. Taxation, appointments and the management of regional commanders were conditions for political survival, even when later histories judged the dynasty mainly by its final defeat.',
    'Conquest joined unequal regional systems','Sui’s victory ended a southern court but did not instantly eliminate the social and administrative differences formed during centuries of separation. The end of Chen is therefore a military turning point within a longer process of integration. It connects the history of regional recovery to the logistical and institutional demands faced by the reunifying state.',
    ['chen','south'],'557–589 dates Chen. Sui’s founding in 581 preceded the conquest of this southern government.',{related:['north-south','reunification','sui']});
  c('catalog-R_NS_NORTHERN_WEI','The Tuoba-led Northern Wei completed its conquest of northern China in 439. Land and household reforms expanded government claims over resources, while the court’s move to Luoyang in 494 signalled a major political and cultural reorientation.',
    'Registration linked land and authority','The equal-field system introduced in 485 allocated land according to household categories and tied cultivation to taxation and labour obligations. Household organization sought to strengthen the fiscal and social foundations of rule. Their historical importance lies in the attempt to make populations legible and obligations collectable. A decree describes a governing ambition, however, and should not be treated as proof of uniform redistribution or administration in every locality.',
    'Cultural change did not erase identity','Adoption of Chinese court practices and patronage of monumental Buddhism created new forms of legitimacy. These changes did not simply dissolve Xianbei identities or political tensions. The court’s transformation is better understood as an attempt to govern a diverse society, with consequences that could create conflict as well as integration.',
    ['beiwei','yungang'],'386–534 dates the dynasty; the court split produced Eastern and Western Wei. The 494 capital move was one stage in a longer transformation.',{related:['north-south','catalog-R_NS_EASTERN_WEI','catalog-R_NS_WESTERN_WEI']});
  c('catalog-R_NS_EASTERN_WEI','Eastern Wei preserved the Wei imperial title while the Gao military household exercised effective power. Its eastern territory included substantial agricultural and urban resources and experienced armies.',
    'An emperor could authorize another family’s power','Keeping a dynastic name allowed a dominant household to govern through inherited legitimacy. The distinction between formal sovereignty and effective command is essential here. Treating the emperor as the only political actor would conceal the coalition that actually supplied the state’s military and administrative capacity.',
    'Division did not mean equal weakness','The eastern and western successors inherited different resources and relationships. Eastern wealth did not guarantee eventual victory, but neither was this simply an insignificant remnant. Its history invites comparison of how resources were organized and commanders held together, rather than assuming territorial fragmentation made every successor equally powerless.',
    ['eastwei','beiwei'],'534–550 dates Eastern Wei. Northern Qi replaced the imperial title in 550 while continuing Gao-family power.',{related:['catalog-R_NS_NORTHERN_WEI','catalog-R_NS_NORTHERN_QI']});
  c('catalog-R_NS_WESTERN_WEI','Western Wei developed under Yuwen Tai’s military leadership after the northern split. Its western coalition had fewer resources than its eastern rival, but became a setting for institutional experiments that influenced Northern Zhou and later Sui.',
    'Scarcity could encourage reorganization','A government unable to rely on sheer resource superiority had reasons to reshape recruitment and command. These reforms should not be read as a perfectly designed blueprint for later success. They were responses to immediate problems whose institutions changed as later regimes adapted them to different populations and military demands.',
    'Formal continuity concealed new power','The Wei title linked the court to the preceding dynasty while the Yuwen leadership organized effective authority. Political history therefore needs both the imperial genealogy and the military coalition. The relationship explains how a successor state could maintain legitimacy through one ruling house before another formally assumed the throne.',
    ['westwei','graff'],'535–557 dates Western Wei. Later military systems should not be projected backwards as one uniform and unchanged institution.',{related:['catalog-R_NS_NORTHERN_WEI','catalog-R_NS_NORTHERN_ZHOU']});
  c('catalog-R_NS_NORTHERN_QI','The Gao family formally replaced Eastern Wei with Northern Qi in 550. The dynasty ruled a resource-rich eastern region until Northern Zhou conquered it in 577. Court and family relationships mattered alongside competition between armies.',
    'Marriage could organize succession','Research on Empress Dowager Lou shows how kinship and marriage helped manage authority within the ruling household. Women’s political agency cannot be recovered if history treats the palace only as a setting for male rulers’ decisions. Succession depended on relationships that connected domestic hierarchy to the survival of a state.',
    'Wealth did not guarantee cohesion','A richer territorial base still required effective command, reliable alliances and decisions about rival centres of influence. The defeat of Northern Qi is therefore not explained by comparing resources alone. Nor do sensational anecdotes about emperors substitute for examining how the institutions governing those resources worked.',
    ['eastwei','lou'],'550–577 dates Northern Qi, distinct from Southern Qi in 479–502.',{related:['catalog-R_NS_EASTERN_WEI','catalog-R_NS_NORTHERN_ZHOU']});
  c('catalog-R_NS_NORTHERN_ZHOU','Northern Zhou succeeded Western Wei under the Yuwen family in 557. It conquered Northern Qi in 577 and created the immediate northern political platform inherited by Sui in 581.',
    'Success built on earlier experiments','The dynasty’s military strength developed from the western coalition rather than appearing at its founding. Institutions linked recruitment and command to political relationships that later governments would revise. Following these connections across dynastic names explains continuity without pretending that every later arrangement already existed in a finished form.',
    'A conqueror could be replaced from within','Victory over the eastern rival did not secure the Yuwen house indefinitely. Sui’s succession shows that an enlarged state could supply the resources for a new ruling coalition. The state’s capacity and the dynasty’s survival were related but distinct: stronger institutions did not automatically protect the family that had consolidated them.',
    ['westwei','graff'],'557–581 dates Northern Zhou; northern conquest in 577 preceded southern reunification in 589.',{related:['catalog-R_NS_WESTERN_WEI','sui','reunification']});
  c('five-dynasties','Five successive northern dynasties ruled between the formal end of Tang in 907 and the founding of Song in 960. Their short reigns coexisted with longer regional states. Commanders’ alliances and access to revenue shaped the pace of political replacement.',
    'The military household was a political institution','Personal connections linked commanders to troops and to the resources needed to support them. These relationships could sustain a government and also enable its overthrow. Rapid changes of dynastic title should not conceal the persistence of administrative practices, military organizations and regional centres of power across those changes.',
    'Consolidation preceded the Song name','Later Zhou’s campaigns and reforms helped create conditions inherited by Song. Reunification was a cumulative and contested process rather than a clean reversal of chaos in 960. Later historians organized the interval around legitimacy and succession; their framework is valuable evidence, but not the only way to understand its political development.',
    ['five','lorge','davis','ten','table','kurz','palaceNight','tangpop','worldpop'],'907–960 concerns the five northern dynasties. The wider Five Dynasties and Ten Kingdoms period conventionally extends to 979. Population estimates for Tang China and the world vary considerably.',{end:979,nameZh:'五代十国',related:['tang','jiedushi','an-lushan','huang-chao','catalog-S_TEN','catalog-R_FIVE_LATER_LIANG','catalog-R_FIVE_LATER_TANG','catalog-R_FIVE_LATER_JIN','catalog-R_FIVE_LATER_HAN','catalog-R_FIVE_LATER_ZHOU','catalog-R_TEN_WU_YANG_WU','catalog-R_TEN_SOUTHERN_TANG','catalog-R_TEN_WUYUE','catalog-R_TEN_MIN','catalog-R_TEN_SOUTHERN_HAN','catalog-R_TEN_CHU_MA_CHU','catalog-R_TEN_FORMER_SHU','catalog-R_TEN_LATER_SHU','catalog-R_TEN_JINGNAN_NANPING','catalog-R_TEN_NORTHERN_HAN','liao','southward-economic-shift','song']});
  c('catalog-R_FIVE_LATER_LIANG','Zhu Wen, a former rebel who became a Tang military commander, founded Later Liang in 907. His control over the Tang emperor preceded the formal replacement of the dynasty. Rival powers contested the new court’s legitimacy.',
    'Service and rebellion were not fixed identities','A military actor could move from opposing a dynasty to defending and then displacing it. Such changes reflected negotiated survival and opportunity as well as personal ambition. The sequence warns against reading the eventual founder’s early career as though a new dynasty had always been its clear destination.',
    'Control of the court did not settle the realm','Possession of the imperial title gave a language for appointments and tribute, but other commanders retained independent resources. The state had to fight for recognition as well as territory. Its history therefore joins a formal dynastic succession to a more dispersed struggle among military and regional coalitions.',
    ['five','davis'],'907–923 dates Later Liang, distinct from the sixth-century southern Liang dynasty.',{related:['five-dynasties','tang-end','catalog-R_FIVE_LATER_TANG']});
  c('catalog-R_FIVE_LATER_TANG','Li Cunxu founded Later Tang in 923 after defeating Later Liang. His Shatuo military inheritance and claim to restore Tang authority brought different sources of legitimacy together. The conquest of Sichuan in 925 enlarged the regime’s reach.',
    'Restoration could construct a new order','Using the Tang name did not make this court a simple continuation of the Li dynasty that ended in 907. A restoration claim could recruit allegiance while legitimating a new military coalition. The relationship between ancestry, titles and actual institutions has to be examined rather than inferred from the shared name.',
    'Expansion did not ensure loyalty','New conquests supplied resources but also required supervision, rewards and cooperation from commanders. The coalition remained vulnerable to internal conflict despite military success. The case illustrates why the largest extent of a dynasty on a map says little by itself about the durability of its governing relationships.',
    ['five','davis'],'923–936 dates Later Tang. Its name expresses a restoration claim, not uninterrupted survival of the original Tang court.',{related:['five-dynasties','catalog-R_TEN_LATER_SHU','catalog-R_FIVE_LATER_JIN']});
  c('catalog-R_FIVE_LATER_JIN','Shi Jingtang established Later Jin in 936 with Khitan military support. In exchange, Shi ceded the Sixteen Prefectures, including the region around present-day Beijing, and accepted a subordinate relationship to the Khitan ruler. Conflict over that relationship contributed to its destruction and the Khitan occupation of the capital in 947.',
    'An alliance could constitute sovereignty','External support was not merely an optional diplomatic supplement to a finished state. It helped make the accession possible and imposed continuing obligations. The regime’s room for manoeuvre therefore depended on maintaining or renegotiating a bargain whose terms its successors did not simply choose freely.',
    'Later judgment can obscure immediate choices','Retrospective accounts condemn concessions to a foreign power, but explaining the decision requires reconstructing the founder’s alternatives and military dependence. That explanation does not endorse the bargain. It shows how a struggle for domestic power could reshape the strategic position of subsequent governments.',
    ['five','davis'],'936–947 dates Later Jin, distinct from both the earlier Sima Jin and the later Jurchen Jin.',{related:['five-dynasties','liao','catalog-R_FIVE_LATER_HAN']});
  c('catalog-R_FIVE_LATER_HAN','Liu Zhiyuan established Later Han in 947 amid the political vacuum following Khitan withdrawal. His early death left a young successor confronting powerful commanders. Guo Wei’s takeover brought the dynasty to an end in 951.',
    'Founding strength was difficult to inherit','A commander’s authority rested on relationships formed through his own career. A successor could inherit the title without automatically inheriting the same trust or capacity to distribute rewards. The short dynasty makes visible the problem of converting personal military leadership into a stable arrangement of succession.',
    'A brief court could leave a longer branch','The Northern Han state subsequently maintained a related claim in Shanxi. Political continuity therefore cannot always be represented by one uninterrupted territorial band. Distinguishing the northern kingdom from the short imperial dynasty prevents similar names from flattening the varied outcomes of the same succession struggle.',
    ['five','table'],'947–951 dates Later Han; Northern Han survived separately until 979.',{related:['five-dynasties','catalog-R_TEN_NORTHERN_HAN','catalog-R_FIVE_LATER_ZHOU']});
  c('catalog-R_FIVE_LATER_ZHOU','Guo Wei founded Later Zhou in 951; Chai Rong continued military and administrative consolidation. Their government expanded its reach and strengthened resources that Song subsequently inherited.',
    'Reunification required preparation','Command, revenue and the sequencing of campaigns mattered before the Song founder assumed the throne. A south-first strategy appears in contemporary proposals, but later accounts can make planning look more coherent than events actually were. The historian must distinguish an articulated objective from a guaranteed programme unfolding without reversals.',
    'A new dynasty inherited an old capacity','The change of ruling house in 960 did not erase the military and fiscal work of the preceding regime. This continuity makes Later Zhou important despite its short duration. It also separates the survival of a state’s institutions from the survival of the family occupying its highest offices.',
    ['five','lorge'],'951–960 dates Later Zhou. Its consolidation continued a longer process and did not itself reunite all regional states.',{related:['five-dynasties','song']});
  c('catalog-S_TEN','The Ten Kingdoms label groups regional states flourishing around the Tang-Song transition. Their dates and political forms varied; one, Northern Han, was in the north. They did not all exist simultaneously.',
    'A northern chronology hides regional durability','A list of rapidly changing northern dynasties can make the entire period look uniformly unstable. Some regional courts sustained longer political and cultural projects. Reading their history from their own centres brings maritime exchange, agriculture, patronage and local institutions into view alongside interstate warfare.',
    'A category is not a map of ten equal units','The regimes differed in size, titles and relations with stronger neighbours. Some submitted through negotiation, while others were conquered. The conventional count is useful for orientation, but should not substitute for examining how each court assembled resources and managed the constraints of its particular position.',
    ['ten','table'],'902–979 is the inherited broad regional frame, extending beyond the northern Five Dynasties period of 907–960.',{related:['five-dynasties','catalog-R_TEN_WUYUE','catalog-R_TEN_SOUTHERN_TANG']});
  c('catalog-R_TEN_WU_YANG_WU','Yang Xingmi’s regional power developed under late Tang titles; his princely recognition in 902 supplies the starting convention for Wu. The Xu military household later dominated the Yang rulers before the founding of Southern Tang in 937.',
    'A title could recognize an existing power','The starting date marks one stage in a longer consolidation, not the instant creation of a state from nothing. Tang appointment and regional military control could reinforce each other. This helps explain how independent regimes emerged through the institutions of the empire they eventually outlasted.',
    'The dynasty changed before the administration did','The replacement of the Yang house by the Xu/Li leadership altered legitimacy and succession while retaining a developed regional base. Tracing this continuity makes the transition to Southern Tang more intelligible than treating two adjacent names as wholly disconnected states.',
    ['kurz','table'],'902 marks princely recognition; the imperial title came later. This is Yang Wu, not the third-century Sun Wu.',{related:['catalog-S_TEN','catalog-R_TEN_SOUTHERN_TANG']});
  c('catalog-R_TEN_FORMER_SHU','Wang Jian founded Former Shu in Sichuan in 907 after building a strong regional military position. The state lasted until Later Tang conquered it in 925. Its protected geography supported autonomy without isolating it from diplomacy and interstate competition.',
    'A basin was a resource, not a complete explanation','Sichuan’s approaches could impede invading armies, while its productive base sustained a court. Those advantages still required political organization and relationships with commanders. Geography explains some opportunities and constraints; it does not make a state’s success or failure automatic.',
    'Regional courts participated in a wider order','Diplomatic activity and claims to imperial standing connected Shu to other regimes. Cultural patronage should be understood within that competition for legitimacy rather than imagined as an escape from politics. The kingdom was a deliberate state project whose history cannot be reduced to its eventual incorporation into a larger empire.',
    ['shu2','ten'],'907–925 dates Former Shu; Later Shu was a different ruling house, founded in 934.',{related:['catalog-S_TEN','catalog-R_TEN_LATER_SHU']});
  c('catalog-R_TEN_LATER_SHU','Meng Zhixiang turned his position in Later Tang’s conquered Sichuan territory into a new court in 934. Later Shu sustained a regional government and literary culture under Meng Chang until Song conquest in 965.',
    'A governorship could become a dynasty','The collapse of reliable supervision from the north gave a regional commander opportunities to claim greater independence. The new regime therefore grew from an imperial administrative position as well as local resources. Dynastic fragmentation could preserve institutions even while changing the centre to which they answered.',
    'Continuity was regional rather than genealogical','The later Shu state occupied much of the same geographical world as Wang Jian’s earlier court, but did not restore the same family. Distinguishing regional institutions from dynastic ancestry clarifies both continuity and change. It also explains why cultural practices could survive political replacement and acquire new patrons.',
    ['table','ten'],'934–965 dates Later Shu; it followed the Later Tang occupation after Former Shu’s fall in 925.',{related:['catalog-S_TEN','catalog-R_TEN_FORMER_SHU','song']});
  c('catalog-R_TEN_WUYUE','The Qian family governed Wuyue in the lower Yangtze region from 907 until negotiated submission to Song in 978. Diplomacy, regional resources and religious patronage helped sustain a comparatively durable state.',
    'Accommodation could protect autonomy','Relations with northern courts offered titles and recognition while allowing substantial local continuity. Survival did not always require a successful claim to universal empire. Wuyue illustrates a strategy in which accepting a place in a larger diplomatic hierarchy could help preserve a regional ruling house and its resources.',
    'Buddhist patronage changed over time','Early rulers supported diverse Buddhist and Daoist institutions; particular Chan lineages gained more concentrated support under the last king. Treating the entire dynasty as having one fixed religious policy misses those changes. Patronage was a sequence of relationships shaped by rulers and communities, not an unchanging cultural essence.',
    ['brose','ten'],'907–978 dates Wuyue. Its final submission to Song was negotiated, not a violent conquest.',{related:['catalog-S_TEN','song']});
  c('catalog-R_TEN_CHU_MA_CHU','Ma Yin’s Chu ruled from Hunan and drew revenue from regional production and exchange, including tea. The Ma court ended in 951, although political autonomy in the region did not disappear immediately.',
    'A commodity could sustain diplomacy','Tea connected producers, merchants and courts across political boundaries. Revenue from such exchange could support a regime whose survival also depended on relations with stronger neighbours. The example places commerce inside state formation, rather than assuming political division simply interrupted economic connections.',
    'The endpoint depends on what is being dated','The fall of one ruling house does not necessarily mean immediate administrative absorption into a larger state. Local commanders could preserve regional power after the formal dynasty ended. Historians’ longer chronologies for Hunan can therefore describe a different object from the narrower dates assigned to the Ma family’s court.',
    ['tea','ten'],'907–951 dates Ma Chu. Broader accounts extend the history of autonomous Hunan beyond 951.',{related:['catalog-S_TEN','catalog-R_TEN_SOUTHERN_TANG']});
  c('catalog-R_TEN_MIN','The Wang family’s Min regime developed in Fujian, where coastal exchange contributed to regional resources. Conflict within the ruling house fragmented the state before its conventional endpoint in 945; some local centres continued under separate leadership.',
    'A maritime region needed inland politics','Access to sea routes did not remove the need to govern land, recruit supporters and manage family succession. Trade could strengthen a court while leaving it vulnerable to internal conflict. Political history and commercial history therefore explain different parts of the same state’s capacity.',
    'Fragmentation had more than one scale','The end of the Min dynasty did not make every port and district follow an identical timetable. Following regional leaders after the court’s fall reveals continuity hidden by a single endpoint. The case cautions against equating the disappearance of a dynastic title with the sudden dissolution of all institutions beneath it.',
    ['ten','table'],'909–945 follows the inherited dynastic convention. Local port rulers survived the fragmentation of the Wang court.',{related:['catalog-S_TEN','catalog-R_TEN_SOUTHERN_TANG']});
  c('catalog-R_TEN_SOUTHERN_HAN','Southern Han governed from Guangzhou and participated in maritime and regional commercial networks. Material evidence, including coinage and fiscal records, offers a view of the state beyond later accounts focused on rulers’ behaviour.',
    'Objects can change the questions','Lead coins issued in Guangzhou from 917 and silver ingots wrapped in receipts record specific practices of exchange and taxation. The receipts identify salt-tax payments and specify weight and purity: evidence of procedures for turning revenue into accountable stores of value. Such finds do not measure the entire economy, but they disclose administrative work largely absent from stories about palace excess. The state’s coastal position mattered through institutions connecting trade to public resources.',
    'A regional empire had several audiences','Imperial titles addressed other rulers and domestic subjects, while merchants and local elites interacted with the state through different interests. Understanding Southern Han requires bringing these perspectives together. A court’s legitimacy and its economic reach were related without being identical or equally visible in surviving historical writing.',
    ['coins','ten'],'917–971 dates Southern Han. Archaeological finds are selective evidence, not a complete statistical record of trade.',{related:['catalog-S_TEN','song']});
  c('catalog-R_TEN_JINGNAN_NANPING','Jingnan, also called Nanping, was a small state centred on Jiangling and important river routes. Its rulers navigated among stronger neighbours through diplomacy and access to exchange.',
    'Small size could make brokerage valuable','A strategically located court could draw influence from connections it helped manage, even without a large army or expansive territory. Tribute relationships and trade belonged to the same political environment. The state’s survival is better explained through its position among neighbours than by measuring its area against theirs.',
    'Independence was not an all-or-nothing condition','A ruler could accept titles and make payments while retaining meaningful local control. The relationship between formal hierarchy and practical autonomy varied across the region. Jingnan makes that distinction particularly clear because its bargaining position was narrow but still sufficient to sustain a separate court for decades.',
    ['ten','tea'],'924 marks the princely-title convention; the regional governorship began earlier. The state was absorbed in 963.',{related:['catalog-S_TEN','song']});
  c('catalog-R_TEN_SOUTHERN_TANG','Southern Tang inherited Wu’s regional administrative world in 937. Its rulers claimed imperial standing, expanded into neighbouring territories and later lost ground to northern powers. The final ruler Li Yu’s poetry became a major part of the state’s cultural memory.',
    'A restoration claim required explanation','The dynasty’s relationship to the earlier Tang house was a matter of constructed genealogy and political argument. A shared name should not be treated as proof of an uncomplicated line of descent. Claims to continuity were tools for governing and competing, whose credibility varied among different audiences.',
    'Literary fame can eclipse government','Li Yu’s later reputation makes the fallen court vivid, but the state also had military, fiscal and diplomatic institutions. Reading poems alongside administrative history restores those dimensions. Cultural achievement and political defeat can coexist without one providing a sufficient explanation of the other.',
    ['kurz','ten'],'937–975 retains the conquest-year convention. Some scholarly titles use 976 owing to chronological conventions; the original date is preserved.',{related:['catalog-S_TEN','catalog-R_TEN_WU_YANG_WU','song']});
  c('catalog-R_TEN_NORTHERN_HAN','Northern Han preserved a Liu-family court in Shanxi after Later Han fell. Its rulers relied on ties with Liao while asserting imperial authority of their own. Song conquered it in 979.',
    'Dependence and ambition could coexist','A small state could need a stronger ally and still claim a sovereign title. These positions were not necessarily experienced as a contradiction in the same way later national histories might suggest. Diplomatic relations provided protection and recognition while also constraining the choices available to the court.',
    'The category breaks its own geography','Northern Han is conventionally included among the Ten Kingdoms despite being in the north. Its survival beyond 960 also complicates a neat ending for the era at Song’s foundation. The state shows why the exhibition’s groupings must be treated as reading aids rather than exact descriptions of contemporary political organization.',
    ['table','ten'],'951–979 dates Northern Han, distinct from the Earlier Han empire and the short Later Han dynasty.',{related:['catalog-S_TEN','liao','song']});
  refs.sui=['https://www.cambridge.org/core/books/abs/cambridge-history-of-china/sui-dynasty-581617/5A2EC762FFB0E26FDB1462DF7CB5BA82','Arthur Wright · The Sui Dynasty'];
  refs.sculpture=['https://www.metmuseum.org/ja/essays/chinese-buddhist-sculpture','Denise Patry Leidy · Chinese Buddhist Sculpture'];
  refs.exemption=['https://soas-repository.worktribe.com/output/351650/exemption-not-granted-the-confrontation-between-buddhism-and-the-chinese-state-in-late-antiquity-and-the-first-great-divergence-between-china-and-western-eurasia','Antonello Palumbo · Buddhism and the Chinese state'];
  refs.islam=['https://www.metmuseum.org/fr/essays/the-birth-of-islam','Metropolitan Museum of Art · The Birth of Islam'];
  c('sui','The Sui dynasty began in 581 and conquered Chen in 589, ending the principal northern-southern division. It joined regions with different recent political histories and undertook major administrative, military and transport projects.',
    'Integration was more than conquest','Collecting resources and moving officials, grain and armies demanded institutions that could work across former political boundaries. The canal network is the most visible example, but effective government also depended on registration, appointments and inherited administrative practices. A new map of sovereignty did not immediately produce uniform rule.',
    'Capacity could become overmobilization','The ability to demand labour and supplies supported canal works and repeated campaigns against Goguryeo in 612–614. It also exposed communities to burdens that could undermine the dynasty’s stability. The short life of Sui should not erase its institutional legacy, while that legacy should not be used to excuse the immediate costs borne by its subjects.',
    ['sui','graff'],'581–618 follows the conventional dynastic span. Some scholarship ends its main political narrative in 617; southern conquest occurred in 589.',{related:['reunification','sui-grand-canal','tang']});
  c('reunification','Sui conquered the southern Chen court in 589. The victory ended a major political division, bringing the northern dynasty authority over the lower Yangtze and other southern regions.',
    'A military endpoint began administrative work','Conquest removed a rival ruler but did not erase local institutions or regional social differences. The government had to make appointments, obtain cooperation and establish reliable flows of resources. The distinction explains why reunification is both a dramatic event and a much longer process whose success cannot be read directly from a battlefield outcome.',
    'The south was incorporated, not created','Centuries of southern state formation and cultural development preceded Sui victory. Describing the conquest only as restoration risks making those histories disappear. The reunited empire drew on regional capacities already built under earlier courts, even as it reoriented them toward a new centre of imperial command.',
    ['sui','south'],'589 dates Chen’s conquest, not Sui’s foundation in 581 or immediate completion of all regional integration.',{related:['sui','catalog-R_NS_CHEN','sui-grand-canal']});
  c('catalog-S_ST','The Sui-Tang grouping highlights institutional connections across the dynastic change of 618. Both courts drew on northern military and administrative traditions and governed a reunited imperial space, but the three centuries encompassed major changes.',
    'Inheritance was selective','New rulers retained useful practices while changing personnel, priorities and the relationships sustaining power. Treating Sui and Tang together can illuminate this continuity. It becomes misleading if it turns institutions into fixed mechanisms that operated identically under every ruler and in every phase of expansion or crisis.',
    'The later Tang was a different configuration','The An Lushan war and subsequent fiscal and military adjustments altered the balance between court and provinces. A single golden-age label conceals that transformation. This grouping is best used as a comparative frame, linking initial consolidation to later adaptations rather than asserting one uniform political economy from 581 to 907.',
    ['sui','graff'],'581–907 is an editorial grouping, not one dynasty or a claim that the state’s institutions remained unchanged.',{related:['sui','tang','an-lushan','two-tax']});
  c('catalog-E_BUD_SPREAD','Buddhist communities and texts were present before the fourth century. During the age of division, translation, patronage and image making expanded their presence in different regions. The year 350 is an illustrative anchor for this uneven process.',
    'Transmission required local institutions','Texts needed translators and readers; images needed patrons and makers; monasteries needed resources and protection. Buddhism’s expansion therefore involved work within Chinese political and social settings, not simply the arrival of a finished foreign doctrine. Regional variation is part of the story rather than an obstacle to a single diffusion map.',
    'Religious authority could challenge government','Monastic obligations and claims to distinct status raised questions about taxation, service and allegiance. Court patronage did not eliminate these tensions. The history of Buddhism’s growth consequently includes negotiation and conflict with rulers as well as devotion, intellectual exchange and the production of enduring art.',
    ['sculpture','exemption'],'350 is approximate and represents broader fourth-century expansion, not Buddhism’s first arrival in China.',{related:['catalog-E_BUD_ENTRY','catalog-R_SIXTEEN_LATER_QIN','catalog-R_NS_NORTHERN_WEI']});
  c('catalog-G_ISLAM','Islamic tradition dates Muhammad’s first revelations to 610. The Hijra to Medina in 622 and the growth of the early Muslim community belong to a sequence distinct from later caliphal expansion. This world-context card places Tang China within a changing wider Eurasian environment.',
    'A religious community became a political force','The community’s development involved institutions and relationships as well as belief. Later expansion carried those relationships into new regions, where forms of government and material culture developed through encounter. Compressing the process into a single birth date would obscure the different stages and actors involved.',
    'Connections to China developed later','Commercial and diplomatic networks eventually connected Muslim societies and Chinese ports and courts. The shared seventh-century setting should not imply that Islam arrived in China at the date of the first revelations. World comparison is most useful when it connects documented routes and exchanges rather than assuming simultaneity proves contact.',
    ['islam'],'610 is the traditional revelation date, not an independently dated arrival of Islam in China. This entry is global context.',{related:['tang','talas']});
  const islamSource='https://www.iranicaonline.org/articles/chinese-iranian-vii/';
  revisions['catalog-G_ISLAM'].sources.push(islamSource);
  revisions['catalog-G_ISLAM'].sourceLabels[islamSource]='Encyclopaedia Iranica · Persian settlements in China';
  return {events:[],revisions,pinyin:{}};
})();
if(typeof module!=='undefined')module.exports=MEDIEVAL_RESEARCH;
