// Modern history: distinguish institutions, lived experience and official commemorations.
const MODERN_RESEARCH = (() => {
  const sources = {
    nixon:['https://history.state.gov/milestones/1969-1976/rapprochement-china','U.S. Office of the Historian · Rapprochement with China, 1972'],
    shanghai:['https://history.state.gov/historicaldocuments/frus1969-76v17/d203','U.S. diplomatic documents · Shanghai Communiqué, 1972'],
    abdicate:['https://history.state.gov/historicaldocuments/frus1912/ch11?start=1','U.S. diplomatic documents · Abdication and republican transition, 1912'],
    puyi:['https://history.state.gov/historicaldocuments/frus1924v01/d356','U.S. diplomatic report · Puyi’s expulsion, 1924'],
    republic:['https://history.state.gov/countries/china','U.S. Office of the Historian · Recognition and diplomatic relations'],
    revolution:['https://history.state.gov/milestones/1945-1952/chinese-rev','U.S. Office of the Historian · Chinese Revolution of 1949'],
    civil:['https://www.nationalarchives.gov.uk/education/resources/the-chinese-civil-war/','UK National Archives · Chinese Civil War documents'],
    may:['https://afe.easia.columbia.edu/special/china_1750_mayfourth.htm','Columbia Asia for Educators · May Fourth'],
    march:['https://afe.easia.columbia.edu/special/china_1900_mao_march.htm','Columbia · Snow and Mao on the Long March'],
    leaders:['https://afe.easia.columbia.edu/special/china_1950_leaders.htm','Columbia · Leaders of the People’s Republic'],
    land:['https://chineseposters.net/themes/land-reform','Chinese Posters · Land reform and collectivization'],
    marriage:['https://chineseposters.net/themes/marriage-law','Chinese Posters · New Marriage Law'],
    leap:['https://chineseposters.net/themes/great-leap-forward','Chinese Posters · Great Leap Forward'],
    culture:['https://mao-static.kdl.kcl.ac.uk/object-biographies/mao-posters/index.html','King’s College London · Mao Era in Objects: posters'],
    death:['https://chineseposters.net/themes/mao-after','Chinese Posters · After Mao'],
    reform:['https://blogs.worldbank.org/en/eastasiapacific/reflections-on-forty-years-of-china-reforms','World Bank · Forty years of reforms'],
    zones:['https://documents1.worldbank.org/curated/en/310891468018256346/pdf/WPS5583.pdf','World Bank · China’s special economic zones'],
    tiananmen:['https://nsarchive2.gwu.edu/NSAEBB/NSAEBB16/','National Security Archive · Tiananmen: declassified history'],
    tiananmen2:['https://history.state.gov/milestones/1989-1992/tiananmen-square','U.S. Office of the Historian · Tiananmen, 1989'],
    hongkong:['https://www.cmab.gov.hk/en/issues/jd2.htm','Hong Kong government · Sino-British Joint Declaration'],
    handover:['https://www.yearbook.gov.hk/1997/ch2/e2a.htm','Hong Kong Yearbook 1997 · Handover'],
    space:['https://en.cmse.gov.cn/missions/shenzhouv/','China Manned Space Agency · Shenzhou V mission'],
    xi:['https://www.congress.gov/crs_external_products/IF/PDF/IF10854/IF10854.2.pdf','Congressional Research Service · China’s 2018 constitutional changes'],
    belt:['https://documents.worldbank.org/en/publication/documents-reports/documentdetail/448361569922674511','World Bank · Belt and Road Economics'],
    belt2:['https://blogs.worldbank.org/en/eastasiapacific/managing-the-risks-of-the-belt-and-road','World Bank · Managing Belt and Road risks'],
    taiwan:['https://1997-2001.state.gov/background_notes/taiwan_0010_bgn.html','U.S. State Department · Taiwan historical background (2000)'],
    democracy:['https://www.president.gov.tw/qrcode/19e','Taiwan Presidential Office · Democratization chronology'],
    war:['https://history.state.gov/milestones/1937-1945/pearl-harbor','U.S. Office of the Historian · War in China and the Pacific'],
    luxun:['https://www.marxists.org/archive/lu-xun/1918/04/x01.htm','Lu Xun · A Madman’s Diary (translated primary text)'],
    wto:['https://www.wto.org/english/thewto_e/countries_e/china_e.htm','World Trade Organization · China membership'],
    wto2:['https://www.wto.org/english/news_e/pres01_e/pr243_e.htm','World Trade Organization · China accession commitments']
  };
  const revisions = {};
  function card(id,description,t1,p1,t2,p2,keys,note,extra={}) {
    const refs=keys.map(k=>sources[k]);
    revisions[id]={description,sections:[{title:t1,text:p1},{title:t2,text:p2}],
      sources:refs.map(s=>s[0]),sourceLabels:Object.fromEntries(refs),note,
      evidence:'Source-checked synthesis',...extra};
  }
  card('republic',
    'The Republic of China began in 1912 after the Qing monarchy fell. Its mainland history encompassed parliamentary experiments, military fragmentation, Nationalist state building, invasion and civil war. In 1949 its government moved to Taiwan; the continuing name should not obscure this profound change in the territory it governed.',
    'A republic before a consolidated state','Ending hereditary monarchy did not settle who could command armies, collect revenue or represent citizens. Rival constitutional claims operated alongside regional military power. The Nationalists’ later attempt at national consolidation consequently involved both institution building and political coercion. A republican title alone tells us little about the distribution of effective authority.',
    'One label, changing political orders','The timeline preserves the Republic’s institutional continuity into Taiwan. That continuity encompasses authoritarian rule and later democratization, not an unchanged regime. Reading the mainland and Taiwan together requires distinguishing a government’s constitutional claims from the places it actually administered and the political rights available to the people living there.',
    ['republic','taiwan'],'1912 is the foundation year. The ribbon’s present-day endpoint is a display horizon, not a claim of continuous ROC government over mainland China.',{related:['abdication','catalog-E_MOD_MAY4','civil-war','roc-taiwan']});
  card('abdication',
    'On 12 February 1912 the Qing emperor Puyi abdicated. Negotiation between revolutionaries, northern military leaders and the imperial court helped turn the 1911 uprising into a transfer of sovereign authority. The child emperor’s departure from government ended dynastic monarchy without immediately eliminating imperial institutions or social hierarchies.',
    'A negotiated end to monarchy','Sun Yat-sen relinquished the provisional presidency in favour of Yuan Shikai as part of the settlement. Yuan’s military position mattered as much as constitutional principle. The transition therefore linked republican aspirations to the power of officials trained within the old order, leaving an unresolved question about how civilian institutions could control armed force.',
    'Subjects became citizens unevenly','The republic promised a new relationship between people and state. Establishing that relationship required electoral rules, representative institutions and enforceable rights, not simply an abdication document. The episode is a useful distinction between a decisive legal break and the much slower remaking of everyday authority in villages, households and provincial administrations.',
    ['republic','abdicate','puyi'],'The abdication occurred in 1912, following the revolution of 1911. Puyi remained in the Forbidden City under the settlement until 1924.',{related:['catalog-E_QING_1911','republic']});
  card('catalog-S_MODERN',
    'Modern China is an editorial grouping, not a state that began fully formed in 1912. It brings together revolution, war, competing national projects and economic transformation. The Republic of China and People’s Republic follow different institutional histories that cannot be collapsed into one uninterrupted government.',
    'More than a succession of leaders','Schools, factories, print culture, migration and changing family relations widened the settings in which politics operated. State building increasingly involved organizing populations and resources through parties, campaigns and bureaucracies. These processes reached people unevenly: a rural household, a treaty-port worker and a refugee could experience the same political turning point very differently.',
    'Development had multiple paths','Mainland China, Taiwan and Hong Kong underwent distinct combinations of external pressure, industrialization and political change. Comparisons are illuminating when they identify institutions and constraints, rather than treating any one path as inevitable. The cards in this section separate wars and campaigns from longer social transformations and make their overlapping chronologies visible.',
    ['republic','reform','taiwan'],'1912 is a convenient exhibition boundary. Intellectual, economic and political roots extend into the Qing; the present-day endpoint does not forecast an outcome.',{related:['republic','prc','roc-taiwan','catalog-E_MOD_HK_RETURN']});
  card('catalog-E_MOD_MAY4',
    'Student protests in Beijing on 4 May 1919 challenged the Versailles settlement’s handling of German rights in Shandong and the conduct of Chinese officials. Boycotts, strikes and public organizing widened the movement beyond campuses. Its name also became associated with a broader intellectual transformation already under way.',
    'International betrayal, domestic mobilization','The peace conference made sovereignty a practical question: who could decide the fate of territory and inherited foreign privileges? Students connected diplomatic grievances to criticism of domestic political authority. Workers and merchants joined for reasons shaped by their own positions, making the movement a coalition rather than a single programme with a uniform social base.',
    'A movement with competing futures','Advocates of vernacular literature, scientific inquiry, liberalism, anarchism and Marxism disputed what renewal required. Later political narratives often select one strand as the movement’s destination. Reading contemporary writing restores the openness of the moment and distinguishes the specific May demonstrations from the longer New Culture debates over education, language and family authority.',
    ['may','luxun'],'4 May 1919 dates the protest. “May Fourth” also names a broader cultural movement whose boundaries vary by historian.',{related:['republic','lu-xun','civil-war'],ribbon:true,label:false});
  card('catalog-E_MOD_LONG_MARCH',
    'Communist forces abandoned threatened base areas and undertook several difficult retreats during 1934–1936. The best-known column left Jiangxi in 1934 and reached northern Shaanxi in 1935. Heavy losses accompanied a journey later presented as a founding ordeal of Communist victory.',
    'Survival was contingent','Retreat was a response to military pressure, not a predetermined route toward success. Securing food, crossing hostile territory and negotiating with local communities shaped survival. Distinguishing the routes of different armies prevents a single heroic itinerary from standing in for a much more fragmented history of flight, conflict and regrouping.',
    'Memory helped constitute authority','Mao’s poem and Edgar Snow’s account are influential sources for how the march was remembered and explained. They also have literary and political purposes. The episode strengthened Mao’s position over time, but a commemorative story of inevitable leadership should not erase disputes and uncertainty within the movement during the retreat itself.',
    ['march','leaders'],'1934–1936 includes the principal Communist army retreats; 1934–1935 is often used for the First Front Army. Snow’s account relies substantially on participants’ retrospective testimony.',{end:1936,catalogDates:{start:1934,end:1934},related:['civil-war','prc']});
  card('prc',
    'Mao Zedong proclaimed the People’s Republic of China on 1 October 1949 after Communist military victories on the mainland. The new state pursued land redistribution, socialist transformation and industrialization under Communist Party leadership. Later market reforms altered economic organization profoundly while preserving the party’s monopoly of national political power.',
    'Revolution became administration','Winning a civil war and governing a vast population demanded different capacities. The party extended its reach through local organization, campaigns, work units and state planning. Redistribution and improvements in basic services coexisted with coercion and catastrophic policy failures; evaluating the period requires holding these experiences together rather than turning achievements or suffering into an all-purpose verdict.',
    'Continuity through major reversals','The Great Leap Forward, Cultural Revolution and post-1978 reforms were not interchangeable stages of one economic programme. The regime survived by changing policies and reworking institutions. Its continuing name marks institutional persistence, while individual cards show the sharp breaks that shaped work, family life, education and relations with the outside world.',
    ['revolution','leaders','reform'],'1949 dates the proclamation, not the end of all fighting or the completion of territorial consolidation. The endpoint is the exhibition horizon.',{related:['land-reform','marriage-law','great-leap','cultural-revolution','reform-opening']});
  card('roc-taiwan',
    'The Republic of China government relocated to Taiwan in 1949 after defeat on the mainland. Taiwan had passed from Japanese rule to ROC administration in 1945. Martial law and repression shaped the postwar order, while land reform, industrial growth and later democratic movements transformed society.',
    'Continuity of government, discontinuity of experience','Officials and refugees arriving from the mainland encountered a population with its own history under Qing and Japanese rule. The state’s claim to represent China did not remove these differences. Understanding postwar Taiwan requires attention to coercion and local experience as well as the government’s constitutional continuity and Cold War alliances.',
    'Democracy was a process','The lifting of martial law in 1987 and direct presidential election in 1996 were important steps, not a single instantaneous transition. Opposition organizing, social movements and institutional reforms changed who could compete for authority. Economic development created resources and new social demands, but did not make democratization automatic or settle cross-strait political disputes.',
    ['taiwan','democracy'],'1949 marks relocation of the ROC government, not the start of Taiwan’s history or an adjudication of contested sovereignty claims.',{related:['republic','taiwan-democratization','civil-war']});
  card('great-leap',
    'The Great Leap Forward sought rapid industrial and agricultural expansion through communes, mass mobilization and ambitious production targets. Launched in 1958, it contributed to a devastating famine. Procurement demands, distorted reporting and coercive administration made shortages far harder to identify and correct.',
    'The failure of feedback','Officials faced incentives to report success and pressure to demonstrate political commitment. Inflated harvest claims could justify grain extraction beyond what villages could bear. The crisis was therefore more than a failure of technology or effort: institutions made accurate information dangerous and allowed policy errors to become cumulative rather than self-correcting.',
    'Reading abundance against scarcity','Campaign posters depict plentiful harvests and extraordinary productivity. Their value as evidence lies in the expectations and mobilization they promoted, not in treating their images as measurements of output. Famine experiences varied by locality and social position. Explaining that variation requires examining access to food and administrative power as well as aggregate agricultural production.',
    ['leap','leaders'],'1958–1962 covers the campaign and famine crisis. Narrower campaign and famine chronologies differ. Mortality estimates vary substantially; no falsely precise total is supplied.',{related:['land-reform','prc','reform-opening']});
  card('cultural-revolution',
    'Mao launched the Cultural Revolution in 1966, mobilizing attacks on supposed enemies within the party and society. Red Guard activity, factional struggles, persecution and later military intervention disrupted institutions and lives. The decade contained sharply different phases, ending conventionally with Mao’s death and the arrest of the Gang of Four in 1976.',
    'Authority attacked itself','The call to rebel against established officials did not create unrestricted political freedom. Participants claimed authorization from Mao, while factions fought over the meaning of revolutionary legitimacy. This produced a destructive instability: authority could be challenged in the leader’s name and then reimposed through institutions that the movement had helped discredit.',
    'Culture was an instrument and an experience','Posters, model performances and daily rituals made political commitments visible. Such materials reveal efforts to organize feeling and behaviour, but cannot tell us by themselves what every viewer believed. A full account must also attend to damaged education, forced migration, family separation and the uneven opportunities people found within a tightly constrained cultural world.',
    ['culture','death'],'1966–1976 is a conventional frame, not a claim that the same institutions or intensity of violence prevailed everywhere for ten years.',{related:['great-leap','catalog-E_MOD_MAO_DEATH','reform-opening']});
  card('catalog-E_MOD_MAO_DEATH',
    'Mao Zedong died on 9 September 1976. Within a month Hua Guofeng and allies arrested the Gang of Four. These events closed one phase of leadership struggle without immediately establishing the direction of the later reform era.',
    'Succession without an uncontested rule','Mao’s extraordinary personal authority complicated the transfer of power. His successors needed to claim revolutionary legitimacy while deciding which policies and personnel to retain. The arrest of the Gang of Four resolved an immediate struggle, but it did not itself supply a settled economic programme or a durable formula for collective leadership.',
    'A break that had to be narrated','Public mourning and later images of the post-Mao leadership show how political change was presented as continuity as well as correction. The distinction matters because a regime can repudiate major practices without repudiating its founding identity. Reform emerged through subsequent disputes and experiments, not simply as the automatic consequence of one leader’s death.',
    ['death','leaders'],'1976 marks Mao’s death and the succession crisis. The policy shift conventionally associated with 1978 developed afterwards.',{related:['cultural-revolution','reform-opening']});
  card('reform-opening',
    'Decisions at the Communist Party’s December 1978 plenum marked a change in priorities toward economic development. Rural reforms, enterprise experiments and opening to investment developed unevenly over subsequent years. There was no single blueprint implemented nationwide on the day reform began.',
    'Experiments changed incentives','Household farming arrangements allowed families to retain more of the returns to their labour, while local enterprises and selective market pricing expanded room for economic initiative. Policy learning mattered: practices could be tested, contested and extended. This helps explain why reform altered incentives substantially without first abolishing the institutions of party rule.',
    'Growth redistributed opportunity','New investment and migration connected villages, coastal cities and overseas markets. These changes created income and mobility but also uneven access to jobs, welfare and housing. Aggregate growth cannot explain who benefited or bore adjustment costs. The political economy of reform lies in the changing relations among households, local authorities, state firms and emerging businesses.',
    ['reform','zones'],'1978 is a political turning point in an extended process. Individual reforms have different starting dates; this card does not treat market reform as political democratization.',{related:['catalog-E_MOD_SEZ','wto-accession','great-leap']});
  card('catalog-E_MOD_SEZ',
    'Shenzhen, Zhuhai, Shantou and Xiamen became the first four special economic zones in 1980. They offered selected locations room to attract investment and experiment with economic rules. Shenzhen’s proximity to Hong Kong helped connect local transformation to overseas capital and commercial networks.',
    'A boundary made experimentation possible','A special zone gave policymakers a way to permit unfamiliar practices within a defined jurisdiction. The boundary separated an experiment from a commitment to immediate nationwide change. Its success depended on transport, labour, administration and connections to markets, not simply on drawing a line on a map or offering a tax concession.',
    'The city was built by migration','Factories and construction drew workers into rapidly growing urban economies. Investment statistics alone miss the labour and household adjustments that made industrialization possible. Zones therefore belong in social history as well as business history: they reorganized where people worked, how families sustained themselves and how local governments pursued revenue and development.',
    ['zones','reform'],'1980 dates the first formal SEZ designations. Preparatory opening policies in Guangdong and Fujian began in 1979; a later wave created other types of development zones.',{related:['reform-opening','catalog-E_MOD_HK_RETURN','wto-accession']});
  card('catalog-E_MOD_TIANANMEN',
    'Protests in 1989 brought students, workers and other residents into public political action in Beijing and other cities. Demands included action against corruption and greater accountability. On the night of 3–4 June, troops used lethal force in Beijing to end the movement, followed by arrests and repression.',
    'A coalition with different demands','The movement cannot be reduced to one programme shared equally by all participants. Concerns about prices, privilege, representation and political reform intersected without becoming identical. Examining workers alongside students changes the social picture and makes clear why economic reform could generate demands for accountability as well as support for further market change.',
    'The geography of evidence matters','Much of the killing occurred on streets approaching the square, so the familiar name should not confine the event to a single location. Declassified diplomatic reports offer contemporary observations but also incomplete information and the interests of their authors. The sources establish lethal repression while leaving important uncertainties about the full number and identities of victims.',
    ['tiananmen','tiananmen2'],'1989 covers the protests and suppression. Casualty totals remain disputed; uncertainty over totals does not imply uncertainty that troops killed civilians.',{related:['reform-opening','prc','taiwan-democratization'],ribbon:true,label:false});
  card('catalog-E_MOD_HK_RETURN',
    'On 1 July 1997 Hong Kong passed from British to Chinese sovereignty and became a Special Administrative Region. The 1984 Sino-British Joint Declaration provided the negotiated framework. Its promises of institutional continuity made the transition more than a change of flag.',
    'Sovereignty and institutions were separated','The settlement envisaged continued capitalist arrangements and a distinct legal system under Chinese sovereignty. The political importance lay in whether institutions could preserve meaningful differences inside one state. A treaty’s language is evidence of the commitments made, not proof that all later disputes about their interpretation had already been resolved.',
    'A city within wider economic networks','Hong Kong’s commercial and financial connections linked it to the mainland’s opening long before 1997. The handover should therefore be read alongside the growth of neighbouring Shenzhen. Political boundaries and economic integration moved on different timetables, shaping expectations among residents, businesses and the governments negotiating the transition.',
    ['hongkong','handover'],'This card concerns the 1997 transfer and its agreed framework. Later constitutional and political changes require their own dates and evidence.',{related:['catalog-E_MOD_SEZ','nanking','prc']});
  card('catalog-E_MOD_SPACE',
    'Shenzhou 5 launched Yang Liwei into orbit on 15 October 2003 and returned him safely the next day. China became the third country to send a person into orbit using its own launch system. The flight followed a sequence of uncrewed tests.',
    'A mission depended on a system','The visible achievement was one astronaut’s journey, but reliable launch, tracking, life support and recovery demanded coordination across many organizations. Human spaceflight is therefore evidence of accumulated industrial and administrative capacity. Celebrating a launch should not obscure the years of testing and less visible technical labour that made it possible.',
    'Technology also communicated status','The mission carried symbolic significance at home and abroad. Its political meaning came partly from demonstrating membership in a small group of states with independent crewed launch capability. That symbolism does not diminish the engineering achievement, but it explains why governments commit resources to projects whose returns include prestige as well as scientific and operational knowledge.',
    ['space'],'15–16 October 2003 dates the mission. “First” refers to a crewed mission launched by China, not to the first person of Chinese ancestry in space.',{end:2003,related:['prc','reform-opening']});
  card('catalog-E_MOD_XI',
    'Xi Jinping became Communist Party general secretary in November 2012 and state president in March 2013. These are different offices. Subsequent changes increased the emphasis on centralized party leadership; the 2018 constitutional amendment removed the two-term limit for the state presidency.',
    'Titles do not carry equal power','Political authority rests on party and military leadership as well as the formal presidency. Describing 2018 simply as the removal of a limit on all Chinese leadership would therefore misstate the institutions involved. The change mattered because it removed a particular succession constraint and altered expectations, not because it created presidential government from nothing.',
    'Centralization as a governing choice','Central leadership can seek tighter coordination and discipline while also making policy correction depend more heavily on signals from the top. This is an analytical tradeoff rather than a prediction of inevitable outcomes. The card treats 2012 as the beginning of a leadership phase and 2018 as a documented institutional change, without projecting later developments into the original accession.',
    ['xi'],'2012 is an accession date, not a single moment when consolidation was complete. The presidency began in 2013; the term-limit change occurred in 2018. This is a historical account of those changes.',{name:'Xi Jinping assumes party leadership',approx:false,related:['prc','catalog-E_MOD_BRI']});
  card('catalog-E_MOD_BRI',
    'The Belt and Road Initiative was proposed in 2013 as a framework for connectivity, investment and cooperation across countries. It encompasses many projects and agreements, rather than a single centrally executed construction plan. Transport corridors are one important component.',
    'Infrastructure has conditional benefits','Shorter journeys can lower trading costs, but benefits depend on border procedures, maintenance, financing and connections to productive activity. A railway or port is not automatically an economic transformation. The World Bank’s analysis is useful precisely because its projected gains depend on complementary reforms rather than treating construction spending as sufficient evidence of success.',
    'Who carries the risks?','Borrowers, lenders, contractors and neighbouring countries can receive different shares of benefits and liabilities. Debt sustainability, transparency and environmental and social effects therefore belong inside the economic assessment. Evaluating individual projects is more informative than assuming every agreement is either a development success or an instrument with identical geopolitical consequences.',
    ['belt','belt2'],'2013 dates the initiative’s launch. Project membership and scope have changed; modelled benefits are scenarios rather than observed outcomes for every participating country.',{related:['catalog-E_MOD_XI','wto-accession']});

  const events=[];
  function addition(id,name,nameZh,han,start,end,parent,pinyin,description,t1,p1,t2,p2,keys,note,ribbon=false){
    card(id,description,t1,p1,t2,p2,keys,note);
    events.push({id,name,nameZh,han,start,end,parent,color:'#9e3c2e',category:'event',...revisions[id],source:revisions[id].sources[0],related:[parent],ribbon,label:false});
    delete revisions[id]; readings[nameZh]=pinyin;
  }
  const readings={};
  addition('lu-xun','Lu Xun publishes A Madman’s Diary','鲁迅与狂人日记','书',1918,1918,'republic','lǔ xùn yǔ kuáng rén rì jì',
    'Lu Xun’s A Madman’s Diary appeared in 1918 and became a landmark of modern Chinese vernacular fiction. Its disturbed narrator reads cannibalism into the social world around him. The story uses literary form to challenge the moral authority claimed for inherited customs.',
    'A voice that unsettles authority','The diary’s vernacular voice sits within a frame written in classical language. That contrast makes language itself part of the conflict over credibility. Readers must judge a narrator whose apparent madness may reveal violence that respectable society refuses to recognize. The work asks how moral language can conceal cruelty, without offering a straightforward political manifesto.',
    'Literature was part of public change','New journals and debates over written language widened the audience for experimental prose. Yet a literary break should not be mistaken for an immediate transformation of everyday literacy or social relations. Lu Xun’s importance lies partly in keeping uncomfortable questions open, rather than supplying one simple cultural cure for national weakness.',
    ['luxun','may'],'1918 is publication, not the beginning of vernacular writing. The story’s narrator should not be treated as a transparent statement of the author’s biography.',true);
  addition('civil-war','Civil war and the division of governments','国共内战','战',1927,1949,'republic','guó gòng nèi zhàn',
    'The Nationalist-Communist alliance broke in 1927, opening a prolonged civil conflict. Cooperation against Japan interrupted but did not resolve the struggle. Full-scale fighting resumed after 1945; Communist victory on the mainland and the Nationalist government’s relocation to Taiwan transformed the political map in 1949.',
    'Military outcomes had social foundations','Armies required recruitment, supplies and the cooperation or coercion of civilian populations. Land policy, inflation and the costs of protracted war affected those relationships. Explaining the outcome therefore requires more than comparing commanders: the ability to organize resources and sustain political credibility under extreme pressure was central to both sides’ fortunes.',
    'An international war without an external script','The Soviet Union and United States influenced the conflict, but their preferences did not determine every Chinese decision. Diplomatic documents reveal foreign expectations and misunderstandings as well as intervention. The resulting division of governments outlasted the main mainland campaigns, making 1949 a decisive turning point without constituting a comprehensive peace settlement.',
    ['civil','revolution'],'1927–1949 is the conventional principal conflict; major war resumed in 1946, and armed confrontations continued after 1949.',true);
  addition('war-japan','Full-scale war with Japan','全面抗战','战',1937,1945,'republic','quán miàn kàng zhàn',
    'Fighting after the Marco Polo Bridge incident in July 1937 expanded into full-scale war between China and Japan. The conflict brought occupation, mass displacement and atrocities, including the Nanjing massacre. Nationalist and Communist forces resisted Japan while maintaining separate political organizations.',
    'Survival changed the geography of government','Retreat inland shifted institutions, industry and populations away from occupied coastal and northern centres. Maintaining resistance meant sustaining civilians and armies in severely disrupted conditions. The war thus remade education, economic life and local administration as well as military strategy, with profound differences between occupied areas, rear areas and Communist bases.',
    'A Chinese war became part of a world war','The conflict predated the Pacific War that began in 1941. Later Allied cooperation changed resources and diplomacy but did not erase those earlier years. Reading 1937–1945 in this wider frame restores China’s long wartime experience and helps explain why Japan’s defeat left a devastated society in which renewed civil war was possible.',
    ['war','civil'],'1937 dates full-scale war; Japanese occupation of Manchuria began in 1931. This distinction should not imply that aggression began only in 1937.',true);
  addition('land-reform','Land reform and rural power','土地改革','田',1950,1953,'prc','tǔ dì gǎi gé',
    'The 1950 Land Reform Law extended redistribution in the new People’s Republic, building on earlier Communist campaigns. Land and other property were transferred, and rural households were assigned class categories. The process involved coercion and killings as well as redistribution.',
    'Property change was political change','Campaigns did more than rearrange fields. They identified enemies, recruited activists and altered who could exercise authority in a village. Class labels could persist beyond the original redistribution, shaping later treatment of families. The political effects therefore cannot be measured only by the amount of land transferred or by immediate agricultural output.',
    'Redistribution was not collectivization','Giving households land and subsequently organizing collective agriculture were different transformations. Treating them as one undifferentiated reform hides the changing balance between household control and state extraction. Posters offer evidence of official promises and mobilization, while the actual experience of villages requires attention to local conflicts, implementation and the use of violence.',
    ['land','leap'],'1950–1953 follows the early PRC campaign. Earlier base-area reforms preceded it; later collectivization should be dated separately.',false);
  addition('marriage-law','The new Marriage Law','新婚姻法','法',1950,1950,'prc','xīn hūn yīn fǎ',
    'The People’s Republic’s 1950 Marriage Law promoted freedom of marriage, monogamy and equal rights for women and men. It challenged coercive family practices and expanded grounds for seeking divorce. Enforcing these principles required intervention in relationships that law alone could not transform.',
    'Rights entered the household','The family was a site of labour, property and authority, not merely private affection. New legal claims could change a woman’s bargaining position, but dependence on relatives and local officials constrained their use. The law therefore belongs to the history of state building as well as gender: government offered new remedies while extending its involvement in domestic life.',
    'The poster and the difficult practice','Public images of freely chosen, harmonious marriages reveal the desired social order. They do not establish how safely people could exercise their rights or how consistently officials enforced them. Distinguishing legal aspiration from practical access helps explain why a radical reform could have uneven consequences across class, locality and generation.',
    ['marriage','land'],'1950 dates the new law. Legal equality is not evidence that unequal household practices immediately disappeared.',false);
  addition('nixon-china','Nixon visits China','尼克松访华','访',1972,1972,'prc','ní kè sōng fǎng huá',
    'U.S. President Richard Nixon visited China on 21–28 February 1972. He met Mao Zedong and held talks with Premier Zhou Enlai. The visit produced the Shanghai Communiqué and opened a path toward better relations after decades of hostility.',
    'Cold War interests brought the governments together','China’s tensions with the Soviet Union and U.S. concerns over Vietnam helped create reasons for talks. Henry Kissinger’s visits in 1971 prepared the way for Nixon’s journey. The presidential visit made this diplomatic opening visible to the public.',
    'The communiqué set out agreements and differences','Both governments supported progress toward normal relations while stating their separate positions on Taiwan. They also proposed wider contacts in trade, science, culture and sport. Formal U.S.–PRC diplomatic relations followed in 1979; the 1972 visit was an earlier step in that process.',
    ['nixon','shanghai'],'21–28 February 1972 is the visit itself, as recorded in the joint communiqué.',true);
  Object.assign(events.find(event=>event.id==='nixon-china'),{
    dateLabel:'21–28 February 1972',
    dateReview:{status:'confirmed',note:'The joint communiqué records the visit as 21–28 February 1972; the Office of the Historian gives the same dates.',sources:[sources.nixon[0],sources.shanghai[0]]}
  });
  readings['访']='fǎng';
  addition('taiwan-democratization','Taiwan’s democratic transition','台湾民主化','民',1987,1996,'roc-taiwan','tái wān mín zhǔ huà',
    'Martial law was lifted in Taiwan in 1987. Subsequent reforms changed legislative representation and presidential selection, culminating in the first direct presidential election in 1996. Opposition and civil-society activity helped make these institutional changes possible.',
    'The electorate changed the basis of legitimacy','Representatives elected on the mainland decades earlier could no longer provide a plausible indefinitely renewed mandate. Replacing that arrangement shifted the practical basis of government toward Taiwan’s electorate. Direct election made political competition visible at the highest level while leaving important disputes over identity and cross-strait relations unresolved.',
    'A transition with a longer prehistory','Opposition organizing and state repression preceded 1987; further democratic consolidation followed 1996. The selected range marks institutional milestones rather than the complete history of political freedom. Official commemorations emphasize the achievement, while a fuller account also asks how activists, voters and leaders contested the pace and limits of change.',
    ['taiwan','democracy'],'1987–1996 is a selected transition window, not an assertion that democracy began or was completed on one date.',true);
  addition('wto-accession','China joins the World Trade Organization','中国加入世贸组织','贸',2001,2001,'prc','zhōng guó jiā rù shì mào zǔ zhī',
    'China became a WTO member on 11 December 2001 after lengthy negotiations. Accession included commitments on tariffs, market access and trade rules. It connected domestic reform to a multilateral institutional framework rather than inaugurating foreign trade from nothing.',
    'External commitments could shape domestic reform','Predictable access to markets helped firms plan investment, while negotiated obligations gave reformers additional arguments for changing domestic arrangements. The agreement mattered through rules and expectations as well as tariff schedules. Implementation remained an ongoing political and administrative task, not an automatic consequence of signing accession documents.',
    'Integration changed the distribution of gains','Expanded trade created opportunities for exporters, workers and consumers but also exposed firms and regions to adjustment. The scale and distribution of those effects require empirical evidence; membership alone cannot explain every subsequent economic trend. This card marks an institutional turning point within the longer history of opening, investment and global production networks.',
    ['wto','wto2'],'2001 is formal accession. The commitments had different transition schedules; later disputes should not be read backwards as settled features of the original agreement.',true);
  const esa='https://www.esa.int/Newsroom/Press_Releases/ESA_Director_General_salutes_China_s_first_human_space_flight';
  revisions['catalog-E_MOD_SPACE'].sources.push(esa);
  revisions['catalog-E_MOD_SPACE'].sourceLabels[esa]='European Space Agency · First Chinese human spaceflight, 2003';
  return {events,revisions,pinyin:{...readings,'田':'tián','法':'fǎ'}};
})();
if(typeof module!=='undefined')module.exports=MODERN_RESEARCH;
