// Tone-marked Mandarin readings, stored locally so the page needs no transliteration service.
const PINYIN = {
  "儒家与道家": "rú jiā yǔ dào jiā",
  "永乐迁都北京": "yǒng lè qiān dū běi jīng",
  "京": "jīng",
  "隋代大运河": "suí dài dà yùn hé",
  "河": "hé",
  "玄武门之变": "xuán wǔ mén zhī biàn",
  "门": "mén",
  "玄奘归国": "xuán zàng guī guó",
  "奘": "zàng",
  "怛罗斯之战": "dá luó sī zhī zhàn",
  "两税法": "liǎng shuì fǎ",
  "税": "shuì",
  "会昌灭佛": "huì chāng miè fó",
  "黄巢攻入长安": "huáng cháo gōng rù cháng ān",
  "城": "chéng",
  "唐朝灭亡": "táng cháo miè wáng",
  "武则天称帝": "wǔ zé tiān chēng dì",
  "金刚经刊印": "jīn gāng jīng kān yìn",
  "中": "zhōng",
  "中国历史": "zhōng guó lì shǐ",
  "温故知新": "wēn gù zhī xīn",
  "夏": "xià",
  "商": "shāng",
  "西周": "xī zhōu",
  "周": "zhōu",
  "东周": "dōng zhōu",
  "战": "zhàn",
  "秦": "qín",
  "汉": "hàn",
  "新": "xīn",
  "分": "fēn",
  "隋": "suí",
  "唐": "táng",
  "武": "wǔ",
  "五代": "wǔ dài",
  "五代十国": "wǔ dài shí guó",
  "五": "wǔ",
  "宋": "sòng",
  "元": "yuán",
  "明": "míng",
  "清": "qīng",
  "中华民国": "zhōng huá mín guó",
  "民": "mín",
  "中华人民共和国": "zhōng huá rén mín gòng hé guó",
  "共": "gòng",
  "三国": "sān guó",
  "三": "sān",
  "晋": "jìn",
  "晋朝": "jìn cháo",
  "十六国": "shí liù guó",
  "国": "guó",
  "南北朝": "nán běi cháo",
  "南北": "nán běi",
  "辽": "liáo",
  "西夏": "xī xià",
  "金": "jīn",
  "甲骨文": "jiǎ gǔ wén",
  "文": "wén",
  "孔子": "kǒng zǐ",
  "孔": "kǒng",
  "秦统一六国": "qín tǒng yī liù guó",
  "统": "tǒng",
  "纸": "zhǐ",
  "隋朝统一": "suí cháo tǒng yī",
  "合": "hé",
  "安史之乱": "ān shǐ zhī luàn",
  "乱": "luàn",
  "经": "jīng",
  "澶渊之盟": "chán yuān zhī méng",
  "盟": "méng",
  "靖康之变": "jìng kāng zhī biàn",
  "变": "biàn",
  "航": "háng",
  "约": "yuē",
  "终": "zhōng",
  "大禹建夏": "dà yǔ jiàn xià",
  "大": "dà",
  "大禹": "dà yǔ",
  "武王伐纣": "wǔ wáng fá zhòu",
  "春秋": "chūn qiū",
  "春": "chūn",
  "战国": "zhàn guó",
  "孙子": "sūn zǐ",
  "孙": "sūn",
  "亚历山大": "yà lì shān dà",
  "亚": "yà",
  "秦汉": "qín hàn",
  "西汉": "xī hàn",
  "西": "xī",
  "东汉": "dōng hàn",
  "东": "dōng",
  "秦代标准化": "qín dài biāo zhǔn huà",
  "儒学与汉代政治": "rú xué yǔ hàn dài zhèng zhì",
  "儒": "rú",
  "丝绸之路": "sī chóu zhī lù",
  "丝": "sī",
  "佛教传入": "fó jiào chuán rù",
  "佛": "fó",
  "兵马俑": "bīng mǎ yǒng",
  "兵": "bīng",
  "曹魏": "cáo wèi",
  "曹": "cáo",
  "蜀汉": "shǔ hàn",
  "蜀": "shǔ",
  "孙吴": "sūn wú",
  "汉朝终结": "hàn cháo zhōng jié",
  "赤壁之战": "chì bì zhī zhàn",
  "赤": "chì",
  "西晋": "xī jìn",
  "西晋灭亡": "xī jìn miè wáng",
  "佛教传播": "fó jiào chuán bō",
  "隋唐": "suí táng",
  "伊斯兰教兴起": "yī sī lán jiào xīng qǐ",
  "伊": "yī",
  "元大都": "yuán dà dū",
  "明代北京": "míng dài běi jīng",
  "清代北京": "qīng dài běi jīng",
  "明代宦官权力": "míng dài huàn guān quán lì",
  "魏忠贤专权": "wèi zhōng xián zhuān quán",
  "魏": "wèi",
  "第一次鸦片战争": "dì yī cì yā piàn zhàn zhēng",
  "第": "dì",
  "太平天国运动": "tài píng tiān guó yùn dòng",
  "太": "tài",
  "第二次鸦片战争": "dì èr cì yā piàn zhàn zhēng",
  "洋务运动": "yáng wù yùn dòng",
  "洋": "yáng",
  "甲午战争": "jiǎ wǔ zhàn zhēng",
  "甲": "jiǎ",
  "戊戌变法": "wù xū biàn fǎ",
  "戊": "wù",
  "义和团运动": "yì hé tuán yùn dòng",
  "义": "yì",
  "辛亥革命": "xīn hài gé mìng",
  "辛": "xīn",
  "经济特区": "jīng jì tè qū",
  "一带一路": "yī dài yī lù",
  "一": "yī",
  "习近平执政": "xí jìn píng zhí zhèng",
  "习": "xí",
  "现代中国": "xiàn dài zhōng guó",
  "现": "xiàn",
  "五四运动": "wǔ sì yùn dòng",
  "长征": "cháng zhēng",
  "长": "cháng",
  "毛泽东逝世": "máo zé dōng shì shì",
  "毛": "máo",
  "天安门抗议与镇压": "tiān ān mén kàng yì yǔ zhèn yā",
  "天": "tiān",
  "香港回归": "xiāng gǎng huí guī",
  "香": "xiāng",
  "神舟五号": "shén zhōu wǔ hào",
  "神": "shén",
  "宋与并立政权": "sòng yǔ bìng lì zhèng quán",
  "北宋": "běi sòng",
  "北": "běi",
  "南宋": "nán sòng",
  "南": "nán",
  "南宋建立": "nán sòng jiàn lì",
  "东晋": "dōng jìn",
  "汉赵（前赵）": "hàn zhào (qián zhào)",
  "后赵": "hòu zhào",
  "后": "hòu",
  "前燕": "qián yān",
  "前": "qián",
  "前秦": "qián qín",
  "后秦": "hòu qín",
  "刘宋": "liú sòng",
  "刘": "liú",
  "南齐": "nán qí",
  "梁": "liáng",
  "陈": "chén",
  "北魏": "běi wèi",
  "东魏": "dōng wèi",
  "西魏": "xī wèi",
  "北齐": "běi qí",
  "北周": "běi zhōu",
  "后梁": "hòu liáng",
  "后唐": "hòu táng",
  "后晋": "hòu jìn",
  "后汉": "hòu hàn",
  "后周": "hòu zhōu",
  "吴（杨吴）": "wú (yáng wú)",
  "吴": "wú",
  "前蜀": "qián shǔ",
  "吴越": "wú yuè",
  "楚（马楚）": "chǔ (mǎ chǔ)",
  "楚": "chǔ",
  "闽": "mǐn",
  "南汉": "nán hàn",
  "荆南（南平）": "jīng nán (nán píng)",
  "荆": "jīng",
  "后蜀": "hòu shǔ",
  "南唐": "nán táng",
  "北汉": "běi hàn",
  "十国": "shí guó",
  "十": "shí",
  "毕升与活字印刷": "bì shēng yǔ huó zì yìn shuā",
  "印": "yìn",
  "清明上河图": "qīng míng shàng hé tú",
  "画": "huà",
  "马尼拉与白银贸易": "mǎ ní lā yǔ bái yín mào yì",
  "贸": "mào",
  "红楼梦首次刊印": "hóng lóu mèng shǒu cì kān yìn",
  "书": "shū",
  "大跃进": "dà yuè jìn",
  "跃": "yuè",
  "文化大革命": "wén huà dà gé mìng",
  "革": "gé",
  "改革开放": "gǎi gé kāi fàng",
  "改": "gǎi"
};
if(typeof module!=="undefined")module.exports=PINYIN;
